/**
 * Libellés de l'interface — source unique de vérité.
 * Aucun texte affiché ne doit être écrit en dur dans un composant.
 * Ton : professionnel et direct, phrases courtes.
 */
export const LABELS = {
  app: {
    name: "CentroManager",
    metaDescription: "Abonnements, paiements et présences de votre centre de langue ou de soutien scolaire.",
  },
  common: {
    loading: "Chargement…",
    retry: "Réessayer",
    cancel: "Annuler",
    confirm: "Confirmer",
    save: "Enregistrer",
    search: "Rechercher",
    back: "Retour",
    close: "Fermer",
    more: "Plus",
    openMenu: "Ouvrir le menu",
    skipToContent: "Aller au contenu principal",
  },
  theme: {
    toggleToDark: "Passer au thème sombre",
    toggleToLight: "Passer au thème clair",
  },
  currency: {
    code: "MAD",
  },
  status: {
    upToDate: "À jour",
    overdue: "En retard",
    pending: "En attente",
    paid: "Payé",
    present: "Présent",
    absent: "Absent",
    absence: "Absence",
    followUp: "Relance à faire",
  },
  roles: {
    admin: "Administrateur",
    assistant: "Assistant",
    teacher: "Professeur",
  },
  nav: {
    mainLabel: "Navigation principale",
    styleguideTokens: "Charte",
    styleguideComponents: "Composants",
    styleguideStates: "États",
  },
  table: {
    rowActions: "Actions",
  },
  errors: {
    genericTitle: "Impossible d'afficher cette page",
    genericDescription: "Vérifiez votre connexion internet, puis réessayez. Si le problème continue, contactez l'administrateur du centre.",
    notFoundTitle: "Page introuvable",
    notFoundDescription: "Cette page n'existe pas ou a été déplacée.",
    backHome: "Revenir à l'accueil",
  },
  styleguide: {
    tokens: {
      title: "Charte graphique",
      description: "Couleurs, typographie et formes de CentroManager.",
    },
    components: {
      title: "Composants",
      description: "Boutons, pastilles, photos, tableaux et indicateurs.",
    },
    states: {
      title: "États",
      description: "États vides, de chargement et d'erreur. Notifications.",
    },
    sections: {
      colors: "Couleurs",
      textShades: "Nuances de texte accessibles",
      typography: "Typographie",
      spacing: "Espacement",
      buttons: "Boutons",
      callButtons: "Boutons du mode appel",
      badges: "Pastilles de statut",
      avatars: "Photos élèves",
      table: "Tableau",
      stats: "Indicateurs",
      emptyState: "État vide",
      loading: "État de chargement",
      error: "État d'erreur",
      toasts: "Notifications",
    },
    swatches: {
      primary: "Bleu nuit principal",
      brand: "Bleu vif",
      highlight: "Ambre accent",
      success: "Vert succès",
      danger: "Rouge alerte",
      warning: "Orange attention",
      background: "Fond d'application",
      border: "Bordures",
      secondaryText: "Texte secondaire",
      text: "Texte principal",
    },
    textShadesHint: "Nuances plus sombres de la même teinte, utilisées pour le texte afin d'atteindre un contraste de 4,5:1.",
    typography: {
      title: "Titre de page — 28 px, 700",
      section: "Titre de section — 20 px, 600",
      body: "Corps — 15 px, 400. Les élèves à jour de leurs paiements portent une pastille verte.",
      caption: "Légende — 13 px, gris secondaire",
      amount: "Montant",
      date: "Date",
    },
    buttons: {
      primary: "Enregistrer",
      secondary: "Secondaire",
      outline: "Contour",
      ghost: "Discret",
      destructive: "Supprimer",
      highlight: "Faire l'appel",
      link: "Voir la fiche",
    },
    avatars: {
      list: "Liste — 40 px",
      profile: "Fiche — 96 px",
      call: "Appel — 200 px",
    },
    table: {
      student: "Élève",
      level: "Niveau",
      amount: "Montant dû",
      dueDate: "Échéance",
      status: "Statut",
    },
    stats: {
      collected: "Encaissé ce mois",
      expected: "Attendu ce mois",
      unpaid: "Impayés",
      absencesToday: "Absences aujourd'hui",
      vsLastMonth: "vs mois dernier",
    },
    emptyState: {
      title: "Aucun élève pour le moment",
      description: "Les élèves inscrits apparaîtront ici. Ajoutez votre premier élève.",
      action: "Ajouter un élève",
    },
    errorState: {
      title: "Chargement des élèves impossible",
      description: "La connexion au serveur a échoué. Vérifiez votre connexion internet, puis réessayez.",
    },
    toasts: {
      successTrigger: "Notification de succès",
      success: "Paiement enregistré",
      successDescription: "La facture est marquée comme payée.",
      errorTrigger: "Notification d'erreur",
      error: "Enregistrement impossible",
      errorDescription: "Vérifiez votre connexion, puis réessayez.",
    },
  },
} as const;
