import { DEFAULT_VOCABULARY, translateTree, translator, type VocabularyTerms } from "@/lib/vocabulary";

/**
 * Libellés de l'interface — source unique de vérité.
 * Aucun texte affiché ne doit être écrit en dur dans un composant.
 * Ton : professionnel et direct, phrases courtes.
 */
const TEXTS = {
  app: {
    name: "CentroManager",
    metaDescription: "Abonnements, paiements et présences de votre centre de langue ou de soutien scolaire.",
  },
  common: {
    loading: "Chargement…",
    retry: "Réessayer",
    cancel: "Annuler",
    confirm: "Confirmer",
    save: "Enregistrer",
    search: "Rechercher",
    back: "Retour",
    close: "Fermer",
    more: "Plus",
    openMenu: "Ouvrir le menu",
    skipToContent: "Aller au contenu principal",
    signOut: "Se déconnecter",
    seeAll: "Voir tout",
    show: "Afficher",
    none: "—",
  },
  theme: {
    toggleToDark: "Passer au thème sombre",
    toggleToLight: "Passer au thème clair",
  },
  currency: {
    code: "MAD",
  },
  status: {
    upToDate: "À jour",
    overdue: "En retard",
    pending: "En attente",
    paid: "Payé",
    present: "Présent",
    absent: "Absent",
    absence: "Absence",
    followUp: "Relance à faire",
    followedUp: "Relance faite",
  },
  notifications: {
    title: "Notifications",
    open: (count: number) => (count === 0 ? "Notifications" : `Notifications — ${count} nouvelle(s)`),
    description: "Relances et notes des 14 derniers jours, alertes à traiter.",
    empty: "Aucune notification pour le moment.",
    kinds: { followUp: "Relance", note: "Note de fiche", absenceAlert: "Alerte d'absences" },
    by: (name: string) => `par ${name}`,
  },
  attendanceSheet: {
    title: "Assiduité",
    description: "Présences et absences de l'élève, par matière.",
    filtersLabel: "Filtres de l'assiduité",
    period: "Période",
    periods: { month: "Ce mois-ci", quarter: "Ce trimestre", all: "Tout l'historique" },
    subject: "Matière",
    allSubjects: "Toutes les matières",
    totalAbsences: "Absences",
    sessions: "Séances enregistrées",
    rate: "Taux de présence",
    noRate: "—",
    bySubject: "Par matière",
    absencesCount: (count: number) => (count <= 1 ? `${count} absence` : `${count} absences`),
    sessionsCount: (count: number) => (count <= 1 ? `${count} séance` : `${count} séances`),
    streaksTitle: "Absences consécutives",
    streak: (length: number, subject: string) => `${length} absences consécutives en ${subject}`,
    streakRange: (from: string, to: string) => `du ${from} au ${to}`,
    streakOngoing: "Série en cours",
    streaksEmpty: "Aucune série d'absences consécutives sur cette période.",
    alertTriggered: "Alerte déclenchée",
    alertHint: "Une alerte est créée à la 3ᵉ absence consécutive dans une même matière.",
    listTitle: "Séances manquées",
    listCaption: "Séances manquées, de la plus récente à la plus ancienne",
    date: "Date",
    time: "Horaire",
    teacher: "Professeur",
    note: "Motif ou note",
    noNote: "Aucun motif",
    noTime: "Horaire non planifié",
    position: (position: number, length: number) => `${position === 1 ? "1ʳᵉ" : `${position}ᵉ`} sur ${length} consécutives`,
    emptyTitle: "Aucune absence",
    emptyDescription: "Aucune séance manquée sur cette période.",
    noSessionsTitle: "Aucune séance enregistrée",
    noSessionsDescription: "Les présences apparaîtront après les premiers appels.",
    followUpsTitle: "Relances d'absence",
    followUpsEmpty: "Aucune relance d'absence envoyée au responsable.",
    followUpBy: (name: string) => `par ${name}`,
    editNote: "Motif",
    editNoteLabel: (date: string) => `Motif de l'absence du ${date}`,
    notePlaceholder: "Ex. malade, certificat médical reçu",
    noteSaved: "Motif enregistré",
    noteTooLong: "300 caractères maximum.",
    exportPdf: "Exporter en PDF",
    pdfTitle: "Fiche d'assiduité",
    pdfStudent: "Élève",
    pdfLevel: "Niveau",
    pdfGuardian: "Responsable",
    pdfPeriod: "Période",
    pdfGeneratedOn: (date: string) => `Édité le ${date}`,
    pdfPage: (page: number, total: number) => `Page ${page} / ${total}`,
    viewAttendance: "Voir l'assiduité",
    teacherScope: "Vous voyez uniquement les absences de vos matières.",
  },
  absencesPage: {
    title: "Absences",
    description: (date: string) => `Élèves absents le ${date}.`,
    date: "Date",
    today: "Aujourd'hui",
    count: (count: number) => (count <= 1 ? `${count} absence` : `${count} absences`),
    subject: "Matière",
    teacher: "Professeur",
    openFile: "Voir la fiche",
    emptyTitle: "Aucune absence",
    emptyDescription: "Aucun élève n'a été marqué absent ce jour-là.",
    streak: (count: number) => `${count} absences consécutives`,
  },
  dashboard: {
    statsTitle: "Statistiques",
    detail: "Voir le détail",
    moreActions: (label: string) => `Actions — ${label}`,
    students: {
      title: "Liste des élèves",
      caption: "Élèves du centre",
      name: "Nom",
      level: "Niveau",
      subjects: "Matière",
      status: "Statut",
      phone: "Téléphone parent",
      actions: "Actions",
      sortBy: (column: string) => `Trier par ${column}`,
      search: "Rechercher dans la liste",
      searchPlaceholder: "Nom de l'élève",
      openFile: "Voir la fiche",
      call: "Appeler",
      whatsapp: "WhatsApp",
      rowActions: (name: string) => `Actions — ${name}`,
      emptyTitle: "Aucun élève",
      emptyDescription: "Les élèves inscrits apparaîtront ici.",
      noMatch: "Aucun élève ne correspond à cette recherche.",
    },
    reminder: {
      title: "Rappel",
      cardTitle: "Relances du jour",
      cardDescription: (count: number) =>
        count === 0
          ? "Aucun élève à relancer aujourd'hui."
          : count === 1
            ? "1 élève en retard à contacter aujourd'hui."
            : `${count} élèves en retard à contacter aujourd'hui.`,
      link: "Voir la liste",
      dismiss: "Masquer le rappel",
    },
    presence: {
      title: "Présences par matière",
      ring: "présence",
      detail: (level: string, students: number) => `${level} · ${students <= 1 ? `${students} élève` : `${students} élèves`}`,
      link: "Voir les détails",
      emptyTitle: "Aucune présence saisie",
      emptyDescription: "Les taux apparaîtront après les premiers appels.",
    },
  },
  roles: {
    admin: "Administrateur",
    super_admin: "Propriétaire de la plateforme",
    assistant: "Assistant",
    teacher: "Professeur",
  },
  nav: {
    mainLabel: "Navigation principale",
    searchStudent: "Rechercher un élève",
    styleguideTokens: "Charte",
    styleguideComponents: "Composants",
    styleguideStates: "États",
    dashboard: "Tableau de bord",
    students: "Élèves",
    newStudent: "Nouvel élève",
    newTeacher: "Nouveau professeur",
    home: "Accueil",
    schedule: "Emploi du temps",
    subjects: "Niveaux et matières",
    planning: "Planning",
    users: "Utilisateurs",
    reports: "Rapports",
    absences: "Absences",
    platformCenters: "Centres",
    platformBilling: "Facturation",
    platformSettings: "Réglages",
    branding: "Marque",
    settings: "Réglages",
    payroll: "Paie",
    expenses: "Charges",
    short: {
      dashboard: "Accueil",
      subjects: "Matières",
      newStudent: "Inscrire",
      newTeacher: "Professeur",
    },
  },
  auth: {
    login: {
      title: "Connexion",
      description: "Accédez à l'espace de votre centre.",
      email: "Email",
      emailPlaceholder: "nom@centre.ma",
      password: "Mot de passe",
      showPassword: "Afficher le mot de passe",
      hidePassword: "Masquer le mot de passe",
      submit: "Se connecter",
      submitting: "Connexion…",
      forgotten: "Mot de passe oublié ? Contactez l'administrateur de votre centre.",
    },
    validation: {
      emailRequired: "Saisissez votre email.",
      emailInvalid: "Cet email n'est pas valide.",
      passwordRequired: "Saisissez votre mot de passe.",
    },
    errors: {
      invalidInput: "Vérifiez les champs du formulaire.",
      invalidCredentials: "Email ou mot de passe incorrect.",
      rateLimited: "Trop de tentatives. Patientez quelques minutes, puis réessayez.",
      unavailable: "Connexion impossible pour le moment. Vérifiez votre connexion internet, puis réessayez.",
      inactive: "Ce compte est désactivé. Contactez l'administrateur de votre centre.",
      wrongCenter: "Ce compte n'appartient pas à ce centre. Connectez-vous depuis l'adresse de votre centre.",
    },
    inactive: {
      title: "Compte inactif",
      description:
        "Votre compte est désactivé ou n'est rattaché à aucun centre. Contactez l'administrateur de votre centre pour le réactiver.",
      retry: "Vérifier à nouveau",
    },
    userMenu: {
      label: "Menu du compte",
      myPhoto: "Ma photo",
      signOut: "Se déconnecter",
    },
    photo: {
      title: "Ma photo",
      description: "Visible par l'équipe de votre centre.",
      adminTitle: (name: string) => `Photo de ${name}`,
      adminDescription: "Visible par l'équipe du centre.",
      label: "Photo",
      hint: "Prise avec l'appareil photo, ou choisie dans vos fichiers.",
      save: "Enregistrer la photo",
      remove: "Retirer la photo",
      saved: "Photo enregistrée",
      removed: "Photo retirée",
      change: (name: string) => `Changer la photo — ${name}`,
      uploadFailed: "La photo n'a pas pu être envoyée. Réessayez.",
    },
  },
  branding: {
    title: "Marque",
    description: "Nom, logo et couleurs de votre interface, de l'écran de connexion et des courriels.",
    standardOnly: "Formule standard : l'interface est aux couleurs de la plateforme. La marque blanche s'active sur demande.",
    identity: "Identité",
    brandName: "Nom de marque",
    brandNameHint: "Affiché dans l'onglet du navigateur, l'écran de connexion et les courriels.",
    images: "Images",
    logo: "Logo",
    logoHint: "PNG, SVG ou WebP, fond transparent de préférence, 2 Mo maximum.",
    favicon: "Icône d'onglet (favicon)",
    faviconHint: "Carré, PNG ou ICO, 64 × 64 px conseillés.",
    loginBackground: "Fond de l'écran de connexion",
    loginBackgroundHint: "Image paysage, 1920 × 1080 px conseillés.",
    choose: "Choisir une image",
    replace: "Remplacer",
    remove: "Retirer",
    uploading: "Envoi…",
    uploadFailed: "L'image n'a pas pu être envoyée (format PNG, JPEG, WebP, SVG ou ICO, 2 Mo maximum).",
    colors: "Couleurs",
    primary: "Couleur principale",
    primaryHint: "Barre latérale, boutons, liens, focus.",
    secondary: "Couleur secondaire",
    secondaryHint: "Dégradés et fond de l'application.",
    accent: "Couleur d'accent",
    accentHint: "Mises en avant et indicateurs.",
    colorInvalid: "Couleur au format #RRGGBB.",
    preview: "Aperçu",
    previewButton: "Bouton principal",
    emails: "Courriels",
    senderName: "Nom de l'expéditeur",
    supportEmail: "Adresse de réponse et de support",
    supportPhone: "Téléphone de support",
    domain: "Domaine personnalisé",
    domainHint: (target: string) =>
      `Le client crée un enregistrement CNAME de son domaine (ex. app.moncentre.ma) vers ${target}, puis vous vérifiez.`,
    domainInvalid: "Domaine invalide (ex. app.moncentre.ma).",
    domainVerified: "Domaine vérifié",
    domainPending: "En attente de vérification",
    verify: "Vérifier le domaine",
    verifying: "Vérification…",
    verifiedOk: "Domaine vérifié : il pointe bien vers la plateforme.",
    verifiedKo: (target: string) => `Le domaine ne pointe pas encore vers ${target} (la propagation DNS peut prendre quelques heures).`,
    noTarget: "Cible DNS non configurée : définissez PLATFORM_CNAME_TARGET ou PLATFORM_ROOT_DOMAIN.",
    save: "Enregistrer la marque",
    saving: "Enregistrement…",
    saved: "Marque enregistrée",
    edit: "Modifier la marque",
    optional: "facultatif",
  },
  platform: {
    brand: "CentroManager",
    centerStatus: {
      trial: "Essai",
      active: "Actif",
      past_due: "En retard",
      suspended: "Suspendu",
      cancelled: "Résilié",
    },
    plan: {
      standard: "Standard",
      white_label: "Marque blanche",
    },
    interval: {
      month: "par mois",
      year: "par an",
    },
    intervalShort: {
      month: "/ mois",
      year: "/ an",
    },
    paymentMethod: {
      bank_transfer: "Virement",
      cash: "Espèces",
      card: "Carte",
    },
    noDueDate: "Sans échéance",
    notSet: "Non renseigné",
    daysRemaining: (days: number) =>
      days === 0 ? "Échéance aujourd'hui" : days > 0 ? `${days} j restant${days > 1 ? "s" : ""}` : `${-days} j de retard`,
    dashboard: {
      title: "Tableau de bord de la plateforme",
      description: "Vue d'ensemble des centres, des abonnements et des encaissements.",
      centersByStatus: "Centres par statut",
      mrr: "Revenu mensuel récurrent",
      mrrDetail: "Centres actifs et en retard, formules annuelles ramenées au mois",
      collected: "Encaissé ce mois-ci",
      students: "Apprenants sur la plateforme",
      users: "Comptes utilisateurs",
      overdueTitle: "Centres en retard de paiement",
      overdueDescription: "Échéance dépassée, du retard le plus ancien au plus récent.",
      overdueEmpty: "Aucun centre en retard",
      overdueEmptyDescription: "Toutes les échéances sont à jour.",
      daysLate: (days: number) => `${days} jour${days > 1 ? "s" : ""} de retard`,
      dueSince: (date: string) => `Échéance du ${date}`,
      amountDue: "Montant dû",
      director: "Directeur",
      call: "Appeler",
      email: "Écrire",
      callLabel: (name: string) => `Appeler le directeur de ${name}`,
      emailLabel: (name: string) => `Écrire au directeur de ${name}`,
      openCenter: "Voir la fiche",
      upcomingTitle: "Échéances des 7 prochains jours",
      upcomingEmpty: "Aucune échéance dans les 7 prochains jours.",
      dueOn: (date: string) => `Échéance le ${date}`,
      remindersTitle: "Rappels préparés",
      remindersDescription:
        "Courriels préparés chaque nuit (J-7, J-1, jour J, suspension). L'envoi automatique sera activé avec le service de courriel.",
      remindersEmpty: "Aucun rappel préparé récemment.",
      reminderKinds: {
        due_in_7: "Échéance dans 7 jours",
        due_in_1: "Échéance demain",
        due_today: "Échéance aujourd'hui",
        suspended: "Accès suspendu",
        owner_digest: "Récapitulatif",
      },
      reminderPending: "À envoyer",
      reminderSent: "Envoyé",
      noRecipient: "Sans courriel",
    },
    centers: {
      title: "Centres",
      description: "Tous les centres de la plateforme.",
      searchLabel: "Rechercher un centre",
      searchPlaceholder: "Nom ou adresse du centre",
      search: "Rechercher",
      filterStatus: "Filtrer par statut",
      filterType: "Filtrer par type d'établissement",
      filterPlan: "Filtrer par formule",
      allStatuses: "Tous les statuts",
      allTypes: "Tous les types",
      allPlans: "Toutes les formules",
      caption: "Liste des centres",
      name: "Centre",
      type: "Type",
      plan: "Formule",
      status: "Statut",
      activatedAt: "Activation",
      dueDate: "Échéance",
      remaining: "Délai",
      students: "Apprenants",
      price: "Tarif",
      count: (n: number) => `${n} centre${n > 1 ? "s" : ""}`,
      empty: "Aucun centre",
      emptyDescription: "Aucun centre ne correspond à ces critères.",
    },
    center: {
      back: "Tous les centres",
      notFound: "Centre introuvable",
      identity: "Informations",
      slug: "Adresse",
      loginUrl: "Adresse de connexion du centre",
      type: "Type d'établissement",
      createdAt: "Créé le",
      activatedAt: "Activé le",
      cancelledAt: "Résilié le",
      contact: "Contact du directeur",
      notes: "Notes internes",
      noNotes: "Aucune note.",
      subscription: "Abonnement",
      plan: "Formule",
      price: "Tarif",
      dueDate: "Échéance",
      periodStart: "Période en cours depuis le",
      graceDays: "Délai de grâce",
      graceDaysValue: (days: number) => `${days} jour${days > 1 ? "s" : ""}`,
      autoRenew: "Renouvellement automatique",
      yes: "Oui",
      no: "Non",
      students: "Apprenants",
      users: "Comptes",
      payments: "Historique des paiements",
      paymentsEmpty: "Aucun paiement enregistré.",
      paidAt: "Payé le",
      amount: "Montant",
      periodCovered: "Période couverte",
      method: "Mode",
      reference: "Référence",
      recordedBy: "Saisi par",
      history: "Historique",
      historyEmpty: "Aucun événement.",
      automatic: "Automatique",
      branding: "Marque blanche",
      brandingStandard: "Formule standard : l'interface est aux couleurs de CentroManager.",
      brandingEmpty: "Aucun réglage de marque enregistré.",
      brandName: "Nom de marque",
      colors: "Couleurs",
      customDomain: "Domaine personnalisé",
      domainVerified: "Vérifié",
      domainPending: "En attente de vérification",
      supportContact: "Support",
      usersTitle: "Comptes du centre",
      usersEmpty: "Aucun compte.",
      userName: "Nom",
      userEmail: "Courriel",
      userRole: "Rôle",
      userState: "État",
      userActive: "Actif",
      userInactive: "Désactivé",
      lastSignIn: "Dernière connexion",
      never: "Jamais",
      vocabulary: "Vocabulaire",
      periodRange: (from: string, to: string) => `Du ${from} au ${to}`,
    },
    events: {
      "center.created": "Centre créé",
      "center.status_changed": "Statut modifié",
      "center.period_changed": "Échéance modifiée",
      "center.pricing_changed": "Tarif modifié",
      "center.vocabulary_changed": "Type d'établissement modifié",
      "center.identity_changed": "Nom ou adresse modifiés",
      "subscription.plan_changed": "Formule modifiée",
      "subscription.auto_renew_changed": "Renouvellement modifié",
      "subscription.payment_recorded": "Paiement enregistré",
      "branding.updated": "Marque blanche modifiée",
      "center.details_changed": "Informations modifiées",
      "center.admin_invited": "Administrateur invité",
      "platform.settings_changed": "Réglages modifiés",
      "center.password_link_sent": "Lien de mot de passe envoyé",
      "support.started": "Accès support ouvert",
      "support.ended": "Accès support fermé",
    },
    eventFallback: "Action",
    reason: (text: string) => `Motif : ${text}`,
    validation: {
      nameRequired: "Saisissez un nom.",
      tooLong: "Ce texte est trop long.",
      phoneInvalid: "Numéro invalide (ex. 06 12 34 56 78).",
      emailRequired: "Saisissez un courriel.",
      emailInvalid: "Ce courriel n'est pas valide.",
      slugInvalid: "2 à 63 caractères : lettres minuscules, chiffres et tirets.",
      slugReserved: "Cette adresse est réservée à la plateforme.",
      typeRequired: "Choisissez un type d'établissement.",
      termRequired: "Saisissez ce terme.",
      amountInvalid: "Montant invalide (ex. 490 ou 490,50).",
      graceInvalid: "Entre 0 et 60 jours.",
      dateInvalid: "Date invalide.",
      dueAfterActivation: "L'échéance doit suivre la date d'activation.",
      reasonRequired: "Indiquez un motif.",
    },
    errors: {
      emailExists: "Ce courriel a déjà un compte sur la plateforme.",
      inviteFailed: "L'invitation n'a pas pu être envoyée. Réessayez.",
      slugTaken: "Cette adresse est déjà utilisée par un autre centre.",
    },
    newCenter: {
      title: "Nouveau centre",
      open: "Nouveau centre",
      steps: ["Identité", "Type d'établissement", "Formule et tarif", "Compte administrateur"],
      progress: (current: number, total: number) => `Étape ${current} sur ${total}`,
      previous: "Précédent",
      next: "Suivant",
      submit: "Créer le centre et inviter l'admin",
      submitting: "Création…",
      success: "Centre créé",
      successDescription: (email: string) => `Invitation envoyée à ${email}.`,
      name: "Nom du centre",
      namePlaceholder: "Centre Al Amal — Rabat",
      slug: "Adresse du centre",
      slugHint: "Sert au sous-domaine du centre (ex. al-amal). Lettres minuscules, chiffres et tirets.",
      ownerName: "Nom du directeur",
      ownerPhone: "Téléphone du directeur",
      ownerEmail: "Courriel du directeur",
      notes: "Notes internes",
      notesHint: "Visibles uniquement dans la console.",
      optional: "facultatif",
      typeLegend: "Type d'établissement",
      typeHint: "Détermine le vocabulaire de toute l'interface du centre.",
      customTitle: "Vocabulaire personnalisé",
      customHint: "Saisissez chaque terme au singulier et au pluriel, avec son genre pour les accords.",
      termKeys: {
        learner: "Apprenant",
        group: "Groupe",
        course: "Cours",
        instructor: "Encadrant",
        session: "Session",
      },
      singular: "Singulier",
      plural: "Pluriel",
      gender: "Genre",
      masculine: "Masculin",
      feminine: "Féminin",
      preview: (learners: string, instructors: string, courses: string) => `${learners} · ${instructors} · ${courses}`,
      plan: "Formule",
      planHint: {
        standard: "Interface aux couleurs de CentroManager.",
        white_label: "Interface entièrement aux couleurs du client.",
      },
      price: "Montant (MAD)",
      interval: "Durée facturée",
      intervalOptions: { month: "Mensuel", year: "Annuel" },
      graceDays: "Délai de grâce (jours)",
      graceHint: "Après l'échéance, le centre reste utilisable ce nombre de jours avant la suspension.",
      status: "Démarrage",
      statusOptions: { trial: "Période d'essai", active: "Actif dès l'activation" },
      activationDate: "Date d'activation",
      firstDueDate: "Première échéance",
      firstDueHint: "Proposée automatiquement : activation + un mois (ou un an). Modifiable.",
      adminName: "Nom de l'administrateur du centre",
      adminEmail: "Courriel de l'administrateur",
      adminEmailHint: "Il reçoit une invitation et choisit son mot de passe au premier accès.",
      adminPhone: "Téléphone de l'administrateur",
      summary: "Récapitulatif",
    },
    accessLink: {
      title: "Lien d'accès à transmettre",
      description: (email: string) =>
        `Le service de courriel n'a pas pu envoyer le message (limite d'envoi atteinte). Copiez ce lien et envoyez-le à ${email}, par exemple par WhatsApp : il permet de choisir son mot de passe.`,
      personal: "Lien personnel et à usage unique : ne le partagez qu'avec cette personne.",
      copy: "Copier le lien",
      copied: "Lien copié",
      continue: "Continuer",
    },
    actions: {
      title: "Actions",
      recordPayment: "Enregistrer un paiement",
      dueDate: "Modifier l'échéance",
      pricing: "Formule et tarif",
      details: "Modifier les informations",
      suspend: "Suspendre",
      reactivate: "Réactiver",
      cancel: "Résilier",
      resendInvitation: "Renvoyer l'invitation",
      invitationSent: "Invitation renvoyée",
      passwordLink: "Envoyer un lien de mot de passe",
      passwordLinkSent: "Lien de mot de passe envoyé",
      saved: "Modifications enregistrées",
      save: "Enregistrer",
      saving: "Enregistrement…",
      paymentTitle: "Enregistrer un paiement",
      paymentDescription: (period: string) => `Le paiement couvre ${period} à partir de l'échéance en cours et remet le centre en service.`,
      periodMonth: "un mois",
      periodYear: "un an",
      paymentAmount: "Montant (MAD)",
      paymentDate: "Date du paiement",
      paymentMethod: "Mode de paiement",
      paymentReference: "Référence",
      paymentReferenceHint: "N° de virement, de reçu… (facultatif)",
      paymentSaved: "Paiement enregistré",
      dueDateTitle: "Modifier l'échéance",
      dueDateDescription: "Fixer ou prolonger l'échéance. Un centre en retard dont l'échéance redevient future repasse actif.",
      newDueDate: "Nouvelle échéance",
      reasonOptional: "Motif (facultatif)",
      reason: "Motif",
      reasonPlaceholder: "Ex. délai accordé jusqu'au virement",
      pricingTitle: "Formule et tarif",
      detailsTitle: "Informations du centre",
      statusTitle: {
        active: "Réactiver le centre",
        suspended: "Suspendre le centre",
        cancelled: "Résilier le centre",
      },
      support: "Accès support (lecture seule)",
      supportTitle: "Accès support en lecture seule",
      supportDescription:
        "Vous consultez l'espace administration du centre pendant 1 heure, sans pouvoir rien modifier. L'accès est journalisé et un bandeau reste affiché.",
      supportSubmit: "Ouvrir l'accès support",
      supportReasonPlaceholder: "Ex. le directeur signale un problème sur le planning",
      statusDescription: {
        active:
          "Les comptes du centre retrouvent l'accès immédiatement. Si l'échéance est dépassée, prolongez-la : sinon le contrôle quotidien suspendra à nouveau le centre.",
        suspended: "La connexion sera bloquée pour tous les comptes du centre. Les données sont conservées.",
        cancelled:
          "Action définitive : le centre ne pourra plus être réactivé. Les données restent exportables pendant 90 jours.",
      },
      statusSaved: {
        active: "Centre réactivé",
        suspended: "Centre suspendu",
        cancelled: "Centre résilié",
      },
    },
    settings: {
      title: "Réglages de la plateforme",
      description: "Contact affiché aux centres suspendus pour régulariser leur abonnement.",
      contactTitle: "Contact de régularisation",
      name: "Nom affiché",
      namePlaceholder: "Service client CentroManager",
      phone: "Téléphone",
      email: "Courriel",
      saved: "Réglages enregistrés",
      updatedAt: (date: string) => `Dernière modification : ${date}`,
    },
    billing: {
      title: "Facturation",
      description: "Paiements d'abonnement de tous les centres.",
      monthsTitle: "Encaissé par mois",
      monthsDescription: "Prévisionnel du mois en cours : échéances du mois des centres en service, au tarif de leur formule.",
      month: "Mois",
      collected: "Encaissé",
      expected: "Prévisionnel",
      gap: "Écart",
      currentMonth: "Ce mois-ci",
      paymentsTitle: "Tous les paiements",
      center: "Centre",
      empty: "Aucun paiement",
      emptyDescription: "Les paiements d'abonnement enregistrés apparaîtront ici.",
    },
  },
  welcome: {
    title: "Bienvenue",
    description: "Choisissez votre mot de passe pour accéder à votre espace.",
    checking: "Vérification du lien…",
    invalidTitle: "Lien invalide ou expiré",
    invalidDescription: "Demandez une nouvelle invitation au responsable de la plateforme.",
    password: "Mot de passe",
    passwordHint: "8 caractères minimum.",
    confirm: "Confirmer le mot de passe",
    submit: "Enregistrer et accéder à mon espace",
    submitting: "Enregistrement…",
    tooShort: "8 caractères minimum.",
    mismatch: "Les deux mots de passe ne correspondent pas.",
    weak: "Mot de passe trop faible : choisissez-en un plus long ou plus varié.",
    failed: "Enregistrement impossible. Réessayez.",
    signedInAs: (email: string) => `Compte : ${email}`,
  },
  suspended: {
    title: "Accès suspendu",
    description: (center: string) =>
      `L'accès${center ? ` à ${center}` : ""} est suspendu : l'abonnement n'est pas réglé. Vos données sont conservées et l'accès sera rétabli dès la régularisation.`,
    cancelledTitle: "Abonnement résilié",
    cancelledDescription: (center: string) =>
      `L'abonnement${center ? ` de ${center}` : ""} a été résilié. Les données restent disponibles à l'export pendant 90 jours sur demande.`,
    contact: (name: string | null) => (name ? `Pour régulariser, contactez ${name} :` : "Pour régulariser, contactez-nous :"),
    retry: "J'ai régularisé, réessayer",
    restoredTitle: "Accès rétabli",
    restoredDescription: "Votre centre est de nouveau actif.",
    continue: "Continuer",
  },
  pastDueBanner: {
    message: (days: number, date: string) =>
      days > 0
        ? `Abonnement en retard de paiement : l'accès sera suspendu dans ${days} jour${days > 1 ? "s" : ""} (le ${date}).`
        : `Abonnement en retard de paiement : l'accès sera suspendu aujourd'hui.`,
    due: (date: string) => `Échéance du ${date}.`,
  },
  supportBanner: {
    message: (center: string, time: string) => `Mode support — lecture seule — ${center} (jusqu'à ${time}).`,
    leave: "Quitter le mode support",
  },
  spaces: {
    assistant: "Espace accueil",
    teacher: "Espace professeur",
    admin: "Espace administration",
    platform: "Console de la plateforme",
  },
  placeholder: {
    title: "Écran en préparation",
    description: "Cet écran sera disponible dans une prochaine étape du projet.",
  },
  actions: {
    errors: {
      forbidden: "Action non autorisée pour votre compte.",
      invalid: "Vérifiez les champs du formulaire.",
      notFound: "Élément introuvable. Actualisez la page.",
      unexpected: "Une erreur est survenue. Réessayez dans un instant.",
    },
  },
  contact: {
    call: "Appeler",
    whatsapp: "WhatsApp",
    callLabel: (name: string) => `Appeler ${name}`,
    whatsappLabel: (name: string) => `Écrire à ${name} sur WhatsApp`,
  },
  billing: {
    cycle: { 1: "Cycle du 1er", 15: "Cycle du 15" } as Record<number, string>,
    perMonth: "/ mois",
    period: (start: string, end: string) => `Du ${start} au ${end}`,
    daysOverdue: (days: number) => (days <= 1 ? "1 jour de retard" : `${days} jours de retard`),
    invoicesCount: (count: number) => (count <= 1 ? "1 facture" : `${count} factures`),
    studentsCount: (count: number) => (count <= 1 ? "1 élève" : `${count} élèves`),
  },
  packs: {
    pack: "Pack",
    label: (name: string) => `Pack ${name}`,
    includes: (subjects: string) => `Comprend : ${subjects}`,
    subscribers: (count: number) => (count <= 1 ? `${count} abonné` : `${count} abonnés`),
    inactive: "Plus proposé",
    coveredByPack: (name: string) => `Incluse dans le pack ${name}`,
  },
  discounts: {
    title: "Remises",
    badge: (value: string, reason: string) => `Remise ${value} — ${reason}`,
    more: (count: number) => `+${count}`,
    reasons: {
      sibling: "fratrie",
      social: "situation sociale",
      merit: "mérite",
      referral: "parrainage",
      other: "autre",
    },
    reasonOptions: {
      sibling: "Fratrie",
      social: "Situation sociale",
      merit: "Mérite",
      referral: "Parrainage",
      other: "Autre",
    },
    types: { percentage: "Pourcentage", fixed_amount: "Montant fixe" },
    scopes: { all_subjects: "Toutes les matières", specific_subject: "Une matière" },
    scopeAll: "toutes les matières",
    appliesTo: (target: string) => `Sur ${target}`,
    validFrom: (date: string) => `Depuis le ${date}`,
    validRange: (from: string, to: string) => `Du ${from} au ${to}`,
    grantedBy: (name: string, date: string) => `Accordée par ${name} le ${date}`,
    grantedOn: (date: string) => `Accordée le ${date}`,
    states: { active: "En cours", inactive: "Désactivée", expired: "Terminée", upcoming: "À venir" },
    conflict: "Chevauche une autre remise : la plus favorable à l'élève est appliquée.",
    emptyTitle: "Aucune remise",
    emptyDescription: "Les remises accordées par la direction apparaissent ici.",
    emptyAdminDescription: "Accordez une remise : le net à encaisser est recalculé sur les factures à régler.",
    readOnlyHint: "Seule la direction accorde ou modifie une remise.",
    add: "Accorder une remise",
    edit: "Modifier la remise",
    activate: "Réactiver",
    deactivate: "Désactiver",
    delete: "Supprimer",
    form: {
      title: "Accorder une remise",
      editTitle: "Modifier la remise",
      description: "Le net à encaisser est recalculé sur les factures non réglées. Les factures réglées ne changent pas.",
      type: "Type de remise",
      percentValue: "Pourcentage (%)",
      amountValue: "Montant retiré (MAD)",
      amountHint: "Retiré chaque mois de chaque facture concernée.",
      scope: "Portée",
      target: "Matière ou pack",
      chooseTarget: "Choisir…",
      reason: "Motif",
      reasonNote: "Précision",
      reasonNoteHint: "Obligatoire pour le motif « Autre ».",
      validFrom: "Début",
      validTo: "Fin (facultatif)",
      validToHint: "Vide : remise sans date de fin.",
      save: "Enregistrer la remise",
      saved: "Remise enregistrée",
      activated: "Remise réactivée",
      deactivated: "Remise désactivée",
      deleted: "Remise supprimée",
      deleteTitle: "Supprimer cette remise ?",
      deleteDescription:
        "Les factures non réglées sont recalculées sans elle. Les factures déjà réglées gardent la remise appliquée. Pour garder une trace, préférez « Désactiver ».",
    },
    validation: {
      valueRequired: "Indiquez une valeur supérieure à 0.",
      percentMax: "Un pourcentage ne dépasse pas 100.",
      amountMax: "Montant trop élevé.",
      targetRequired: "Choisissez la matière ou le pack.",
      noteRequired: "Précisez le motif.",
      noteTooLong: "200 caractères au maximum.",
      dateInvalid: "Date invalide.",
      endBeforeStart: "La fin doit être après le début.",
    },
    invoice: {
      full: "Tarif plein",
      discount: "Remise",
      net: "Net à encaisser",
      conflict: "Plusieurs remises possibles : la plus favorable est appliquée.",
    },
  },
  paymentMethods: { cash: "Espèces", bank_transfer: "Virement", card: "Carte" },
  receipts: {
    title: "Reçu de paiement",
    cancellationTitle: "Reçu d'annulation",
    number: (number: string) => `Reçu n° ${number}`,
    cancellationNumber: (number: string) => `Annulation n° ${number}`,
    issuedAt: (date: string) => `Émis le ${date}`,
    student: "Élève",
    level: "Niveau",
    period: "Période",
    subject: "Matière",
    rate: "Tarif",
    paid: "Payé",
    lines: "Détail",
    linePeriod: (from: string, to: string) => `du ${from} au ${to}`,
    totalFull: "Total au tarif plein",
    totalDiscount: "Remises",
    total: "Total payé",
    totalCancelled: "Total annulé",
    method: "Mode de paiement",
    balanceDue: "Reste dû",
    nothingDue: "Aucun reste dû",
    cashier: "Encaissé par",
    cancelledBy: "Annulé par",
    cancels: (number: string) => `Annule le reçu n° ${number}`,
    cancelReason: "Motif",
    cancelledNotice: (number: string, date: string) => `Reçu annulé le ${date} (reçu d'annulation n° ${number}).`,
    thanks: "Merci de votre confiance.",
    phone: (phone: string) => `Tél. ${phone}`,
    print: "Imprimer",
    printAgain: "Réimprimer",
    close: "Fermer",
    back: "Retour",
    whatsapp: "Partager sur WhatsApp",
    whatsappAgain: "Renvoyer sur WhatsApp",
    view: "Voir le reçu",
    printed: (date: string) => `Imprimé le ${date}`,
    sent: (date: string) => `Envoyé sur WhatsApp le ${date}`,
    cancelled: "Annulé",
    cancellation: "Annulation",
    sectionTitle: "Reçus",
    sectionDescription: "Chaque encaissement produit un reçu numéroté. Un reçu ne se modifie pas : une erreur se corrige par un reçu d'annulation.",
    emptyTitle: "Aucun reçu",
    emptyDescription: "Les reçus apparaîtront ici après le premier encaissement.",
    notFound: "Reçu introuvable.",
    tokens: {
      student: "[élève]",
      period: "[période]",
      amount: "[montant]",
      center: "[centre]",
      link: "[lien]",
      number: "[numéro]",
    },
    whatsappTemplate:
      "Bonjour, voici le reçu [numéro] de [élève] pour [période] : [montant] réglés.\nReçu : [lien]\nMerci de votre confiance.\n[centre]",
    share: {
      title: "Partager le reçu sur WhatsApp",
      noPhone: "Aucun numéro de responsable n'est enregistré pour cet élève. Saisissez le numéro à utiliser.",
      phone: "Numéro WhatsApp du responsable",
      phoneInvalid: "Numéro invalide. Exemple : 06 12 34 56 78.",
      send: "Ouvrir WhatsApp",
      preparing: "Préparation du reçu…",
      opened: "WhatsApp ouvert : vérifiez le message puis envoyez-le.",
      popupBlocked: "Le navigateur a bloqué l'ouverture de WhatsApp. Autorisez les fenêtres pour ce site.",
    },
    cancel: {
      trigger: "Annuler le reçu",
      title: (number: string) => `Annuler le reçu n° ${number} ?`,
      description:
        "Un reçu d'annulation, numéroté à la suite, est émis et lié à ce reçu. Les factures concernées redeviennent à régler.",
      reason: "Motif de l'annulation",
      reasonRequired: "Indiquez le motif de l'annulation.",
      confirm: "Émettre le reçu d'annulation",
      done: "Reçu d'annulation émis",
    },
  },
  payment: {
    trigger: "Encaisser",
    payThis: "Encaisser",
    title: "Encaissement",
    description: (name: string) => `Choisissez les factures que règle le responsable de ${name}.`,
    invoices: "Factures à régler",
    selectAll: "Tout sélectionner",
    method: "Mode de paiement",
    total: "Total à encaisser",
    totalFull: "Tarif plein",
    totalDiscount: "Remises",
    confirm: (amount: string) => `Encaisser ${amount}`,
    noneSelected: "Sélectionnez au moins une facture.",
    nothingToPay: "Aucune facture à régler.",
    success: "Paiement enregistré",
    receiptReady: (number: string, amount: string) => `Reçu n° ${number} · ${amount}`,
    receiptHint: "Remettez le reçu au responsable : imprimez-le ou envoyez-le sur WhatsApp.",
    alreadyPaid: "Une des factures est déjà réglée. Actualisez la page.",
    overdue: "En retard",
    due: (date: string) => `Échéance ${date}`,
  },
  payroll: {
    title: "Paie des professeurs",
    description: "Montants calculés automatiquement chaque mois : salaire fixe, ou commission sur le tarif plein des élèves inscrits.",
    month: "Mois",
    previousMonth: "Mois précédent",
    nextMonth: "Mois suivant",
    supportUnavailable: "Les données de paie d'un centre ne sont pas consultables en mode support.",
    status: { draft: "Brouillon", validated: "Validée", paid: "Versée" },
    statusHints: {
      draft: "Les montants suivent les inscriptions jusqu'à la validation.",
      validated: "Montants figés. Enregistrez les versements au fur et à mesure.",
      paid: "Tous les versements du mois sont enregistrés.",
    },
    validatedBy: (name: string, date: string) => `Validée par ${name} le ${date}`,
    validatedOn: (date: string) => `Validée le ${date}`,
    columns: {
      teacher: "Professeur",
      mode: "Rémunération",
      computed: "Calculé",
      adjustment: "Ajustement",
      final: "Montant final",
      payment: "Versement",
    },
    modes: { fixed_salary: "Salaire fixe", commission: "Commission", none: "Non configurée" },
    total: "Masse salariale du mois",
    teachersCount: (count: number) => (count <= 1 ? `${count} professeur` : `${count} professeurs`),
    emptyTitle: "Aucun professeur",
    emptyDescription: "Créez des comptes professeurs et affectez-leur des matières pour calculer la paie.",
    showDetail: "Voir le détail du calcul",
    hideDetail: "Masquer le détail",
    detail: {
      subject: "Matière",
      level: "Niveau",
      price: "Tarif mensuel",
      enrolled: "Inscrits",
      rate: "Taux",
      subtotal: "Sous-total",
      formula: (price: string, enrolled: number, rate: string, subtotal: string) =>
        `${price} × ${enrolled} × ${rate} = ${subtotal}`,
      noRate: "Taux non défini",
      noSubjects: "Aucune matière affectée à ce professeur.",
      fullPriceNote: "Calcul sur le tarif plein et tous les élèves inscrits, payés ou non, remises comprises.",
      salary: (amount: string, date: string) => `Salaire mensuel de ${amount}, depuis le ${date}.`,
      noSalary: "Aucun salaire défini pour ce mois.",
      notConfigured: "Choisissez le mode de rémunération de ce professeur.",
    },
    notPaid: "À verser",
    notYet: "Après validation",
    paidOn: (date: string, method: string) => `Versé le ${date} · ${method}`,
    adjustment: {
      trigger: "Ajustement",
      title: (name: string) => `Ajustement — ${name}`,
      description: "Prime, retenue ou avance déjà versée. Le montant calculé ne change pas : l'ajustement s'y ajoute.",
      kind: "Type",
      kinds: { bonus: "Prime (+)", deduction: "Retenue ou avance (−)" },
      amount: "Montant (MAD)",
      reason: "Motif",
      reasonRequired: "Indiquez le motif de l'ajustement.",
      remove: "Retirer l'ajustement",
      saved: "Ajustement enregistré",
    },
    validate: {
      trigger: "Valider la paie",
      title: (month: string) => `Valider la paie de ${month} ?`,
      description: "Les montants sont figés : une inscription ou un taux modifié ensuite ne les change plus. Vous pourrez enregistrer les versements.",
      confirm: "Valider",
      done: "Paie validée",
    },
    unlock: {
      trigger: "Déverrouiller",
      title: "Déverrouiller la paie ?",
      description: "La paie repasse en brouillon et sera recalculée. Le déverrouillage est inscrit au journal du centre.",
      reason: "Motif du déverrouillage",
      reasonRequired: "Indiquez le motif du déverrouillage.",
      confirm: "Déverrouiller",
      done: "Paie déverrouillée",
    },
    pay: {
      trigger: "Marquer versé",
      title: (name: string) => `Versement — ${name}`,
      amount: "Montant versé",
      date: "Date du versement",
      method: "Mode de versement",
      confirm: "Enregistrer le versement",
      done: "Versement enregistré",
    },
    exports: {
      payslip: "Fiche de paie",
      summaryPdf: "Récapitulatif (PDF)",
      summaryCsv: "Récapitulatif (tableur)",
    },
    settings: {
      title: "Rémunération des professeurs",
      description: "Mode, salaire ou taux de commission par matière. Chaque changement s'applique à partir de la date choisie ; l'historique est conservé.",
      edit: "Modifier",
      dialogTitle: (name: string) => `Rémunération — ${name}`,
      mode: "Mode de rémunération",
      monthlyAmount: "Salaire mensuel (MAD)",
      rates: "Taux de commission par matière",
      rateFor: (subject: string, level: string) => `${subject} — ${level}`,
      ratePercent: "Taux (%)",
      effectiveFrom: "À partir du",
      effectiveFromHint: "Les paies déjà validées ne changent pas.",
      noAssignment: "Aucune matière affectée : affectez des matières dans Planning ou Utilisateurs.",
      saved: "Rémunération enregistrée",
      current: {
        salary: (amount: string) => `Salaire ${amount} / mois`,
        rates: (count: number) => (count <= 1 ? `${count} taux défini` : `${count} taux définis`),
        none: "À configurer",
      },
      invalidAmount: "Indiquez un montant positif.",
      invalidRate: "Un taux est compris entre 0 et 100.",
      history: "Historique",
      historyFrom: (date: string) => `depuis le ${date}`,
      historyRange: (from: string, to: string) => `du ${from} au ${to}`,
    },
    pdf: {
      payslipTitle: "Fiche de paie",
      summaryTitle: "Récapitulatif de la paie",
      period: "Période",
      teacher: "Professeur",
      generatedAt: (date: string) => `Édité le ${date}`,
      signature: "Signature du professeur",
    },
  },
  expenses: {
    title: "Charges du centre",
    description: "Loyer, factures, fournitures… Elles entrent dans le revenu net du tableau de bord.",
    supportUnavailable: "Les charges d'un centre ne sont pas consultables en mode support.",
    month: "Mois",
    previousMonth: "Mois précédent",
    nextMonth: "Mois suivant",
    quickAdd: {
      title: "Ajouter une charge",
      category: "Catégorie",
      label: "Libellé",
      labelPlaceholder: "Ex. : facture d'électricité",
      amount: "Montant (MAD)",
      date: "Date",
      method: "Paiement",
      methodNone: "Non précisé",
      recurring: "Chaque mois",
      recurringHint: "Recopiée chaque mois en brouillon, à confirmer.",
      receipt: "Justificatif",
      receiptHint: "Photo ou PDF, 3 Mo au maximum (facultatif).",
      add: "Ajouter",
      added: "Charge ajoutée",
    },
    drafts: {
      title: "À confirmer",
      description: "Charges récurrentes recopiées pour ce mois, avec le montant du mois précédent. Ajustez le montant si besoin, puis confirmez.",
      confirm: "Confirmer",
      confirmed: "Charge confirmée",
      discard: "Ignorer ce mois",
    },
    list: {
      title: "Charges du mois",
      empty: "Aucune charge enregistrée pour ce mois.",
      filter: "Catégorie",
      allCategories: "Toutes les catégories",
      recurring: "Récurrente",
      receipt: "Justificatif",
      noReceipt: "Sans justificatif",
      attach: "Joindre",
      edit: "Modifier",
      delete: "Supprimer",
      stopRecurring: "Arrêter la récurrence",
      stoppedRecurring: "Récurrence arrêtée",
      deleteTitle: (label: string) => `Supprimer « ${label} » ?`,
      deleteDescription: "La charge sort des totaux. La suppression est enregistrée avec son auteur dans le journal du centre.",
      deleted: "Charge supprimée",
      recordedBy: (name: string) => `Saisie par ${name}`,
      total: "Total du mois",
      count: (count: number) => (count <= 1 ? `${count} charge` : `${count} charges`),
    },
    edit: {
      title: "Modifier la charge",
      notes: "Note",
      saved: "Charge enregistrée",
    },
    breakdown: {
      title: "Répartition par catégorie",
      empty: "La répartition s'affiche dès la première charge du mois.",
      share: (percent: string) => `${percent} du total`,
    },
    comparison: {
      title: "Comparaison avec le mois précédent",
      current: "Ce mois-ci",
      previous: "Mois précédent",
      delta: "Écart",
      up: (amount: string, percent: string) => `+ ${amount} (${percent})`,
      down: (amount: string, percent: string) => `− ${amount} (${percent})`,
      same: "Identique",
      newSpend: "Nouvelle dépense",
      noPrevious: "Aucune charge le mois précédent.",
    },
    categories: {
      manage: "Catégories",
      title: "Catégories de charges",
      description: "Ajoutez, renommez ou désactivez des catégories. Une catégorie désactivée n'est plus proposée ; ses charges restent.",
      name: "Nom",
      icon: "Icône",
      recurringDefault: "Récurrente par défaut",
      add: "Ajouter une catégorie",
      save: "Enregistrer",
      saved: "Catégorie enregistrée",
      deactivate: "Désactiver",
      activate: "Réactiver",
      inactive: "Désactivée",
      nameRequired: "Indiquez un nom (60 caractères au maximum).",
    },
    validation: {
      categoryRequired: "Choisissez une catégorie.",
      labelRequired: "Indiquez un libellé (120 caractères au maximum).",
      amountInvalid: "Indiquez un montant supérieur à 0.",
      dateInvalid: "Date invalide.",
      receiptInvalid: "Justificatif refusé : photo (JPEG, PNG, WebP) ou PDF de 3 Mo au maximum.",
    },
  },
  financeDashboard: {
    title: "Résultat du mois",
    scope: "Ensemble du centre, tous niveaux confondus.",
    collected: "Revenus encaissés",
    expected: "Revenus prévus",
    unpaid: (amount: string) => `Écart (impayés) : ${amount}`,
    payroll: "Masse salariale",
    payrollHint: "Salaires fixes et commissions",
    expenses: "Charges du mois",
    net: "Revenu net",
    netFormula: "Encaissé − masse salariale − charges",
    positive: "Bénéfice",
    negative: "Perte",
    margin: "Marge nette",
    marginHint: "Revenu net rapporté aux revenus encaissés",
    marginNone: "Pas encore d'encaissement ce mois-ci",
    details: { payroll: "Voir la paie", expenses: "Voir les charges" },
    chart: {
      title: "Douze derniers mois",
      description: "Encaissé, masse salariale, charges et revenu net, mois par mois (MAD).",
      series: { collected: "Encaissé", payroll: "Masse salariale", expenses: "Charges", net: "Revenu net" },
      showTable: "Afficher le tableau",
      hideTable: "Masquer le tableau",
      caption: "Résultat mensuel sur douze mois",
      month: "Mois",
      note: "Masse salariale des mois passés : paies enregistrées dans l'application.",
    },
    discounts: {
      title: "Remises du mois",
      description: "Réductions accordées sur les factures du mois : un manque à gagner à piloter.",
      total: "Total des remises",
      students: (count: number) => (count <= 1 ? `${count} élève concerné` : `${count} élèves concernés`),
      empty: "Aucune remise sur les factures de ce mois.",
      byReason: "Par motif",
    },
  },
  centerSettings: {
    title: "Réglages du centre",
    description: "Coordonnées et reçus de paiement.",
    contactTitle: "Coordonnées",
    contactDescription: "Affichées en en-tête et en pied des reçus.",
    address: "Adresse",
    phone: "Téléphone",
    receiptsTitle: "Reçus",
    format: "Format d'impression",
    formats: {
      a5: "A5 (feuille)",
      ticket_80mm: "Ticket 80 mm (imprimante thermique)",
    },
    formatHints: {
      a5: "Demi-feuille A4, portrait.",
      ticket_80mm: "Rouleau de caisse de 80 mm de large.",
    },
    template: "Message WhatsApp",
    templateHint: "Variables remplacées à l'envoi :",
    templateReset: "Revenir au message proposé",
    preview: "Aperçu",
    save: "Enregistrer",
    saved: "Réglages enregistrés",
    addressTooLong: "200 caractères au maximum.",
    phoneInvalid: "Numéro invalide. Exemple : 05 22 00 00 00.",
    templateTooLong: "1 000 caractères au maximum.",
    templateNeedsLink: "Le message doit contenir [lien] pour que le responsable reçoive le reçu.",
    sample: { student: "Salma Bennani", period: "Octobre 2026", amount: "450 MAD", number: "2026-0042", link: "https://…" },
  },
  followUp: {
    channels: { phone: "Téléphone", whatsapp: "WhatsApp", in_person: "En personne" },
    types: { payment: "Paiement", absence: "Absence" },
    dialog: {
      trigger: "Enregistrer une relance",
      triggerShort: "Relancer",
      title: "Enregistrer une relance",
      description: (name: string) => `Relance de ${name}.`,
      type: "Motif",
      channel: "Canal",
      note: "Note",
      notePlaceholder: "Ex. : le parent promet de régler vendredi.",
      submit: "Enregistrer",
      success: "Relance enregistrée",
    },
    validation: {
      noteTooLong: "La note ne doit pas dépasser 500 caractères.",
    },
  },
  admin: {
    common: {
      edit: "Modifier",
      delete: "Supprimer",
      save: "Enregistrer",
      saving: "Enregistrement…",
      create: "Créer",
      saved: "Modifications enregistrées",
      deleted: "Suppression effectuée",
      created: "Création effectuée",
      actions: "Actions",
      deleteTitle: "Confirmer la suppression",
      irreversible: "Cette action est définitive.",
    },
    validation: {
      nameRequired: "Ce champ est obligatoire.",
      nameTooLong: "Ce texte est trop long.",
      phoneInvalid: "Saisissez un numéro valide, par exemple 06 12 34 56 78.",
      timeInvalid: "Heure invalide (format HH:MM).",
      endBeforeStart: "L'heure de fin doit suivre l'heure de début.",
      sortOrderInvalid: "Saisissez un nombre entre 0 et 999.",
      priceInvalid: "Saisissez un montant valide.",
      levelRequired: "Choisissez un niveau.",
      subjectRequired: "Choisissez une matière.",
      packRequired: "Choisissez un pack.",
      packSubjectsRequired: "Cochez au moins une matière.",
      teacherRequired: "Choisissez un professeur.",
      emailRequired: "Saisissez l'email.",
      emailInvalid: "Cet email n'est pas valide.",
      passwordTooShort: "Le mot de passe doit contenir au moins 8 caractères.",
      assignmentsRequired: "Cochez au moins une matière.",
      notesTooLong: "Les notes ne doivent pas dépasser 500 caractères.",
    },
    errors: {
      inUse: "Suppression impossible : cet élément est encore utilisé.",
      duplicate: "Ce nom existe déjà.",
      roomConflict: "Cette salle est déjà occupée sur ce créneau.",
      teacherConflict: "Ce professeur a déjà un cours sur ce créneau.",
      levelConflict: "Ce niveau a déjà un cours sur ce créneau : ses élèves ne peuvent pas suivre deux cours en même temps.",
    },
    dashboard: {
      title: "Tableau de bord",
      description: (month: string) => `Situation du mois de ${month}.`,
      filterLabel: "Niveau",
      allLevels: "Tous les niveaux",
      stats: {
        collected: "Encaissé ce mois",
        collectedHint: (paid: number, total: number) => `${paid} facture(s) payée(s) sur ${total}`,
        expected: "Attendu ce mois",
        expectedHint: "Factures dont la période commence ce mois-ci",
        gap: "Reste à encaisser",
        gapHint: (percent: string) => `${percent} de l'attendu`,
        students: "Élèves",
        studentsHint: "Élèves inscrits au centre",
        studentsHintLevel: "Élèves de ce niveau",
        activeStudents: "Élèves actifs",
        collectedMonth: "Revenus encaissés ce mois",
        shortfall: "Manque à gagner",
        shortfallDetail: (percent: string, expected: string) => `${percent} des ${expected} attendus`,
      },
      chart: {
        title: "Taux d'absence par matière",
        description: "30 derniers jours : absences rapportées aux présences saisies.",
        tooltip: (absent: number, total: number) => `${absent} absence(s) sur ${total} présence(s) saisie(s)`,
        showTable: "Afficher le tableau",
        hideTable: "Masquer le tableau",
        caption: "Taux d'absence par matière, 30 derniers jours",
        subject: "Matière",
        level: "Niveau",
        absences: "Absences",
        records: "Saisies",
        rate: "Taux",
        emptyTitle: "Aucune présence saisie",
        emptyDescription: "Le graphique apparaîtra dès que les professeurs auront fait l'appel.",
      },
    },
    subjects: {
      title: "Niveaux et matières",
      description: "Organisation pédagogique et tarifs mensuels.",
      newLevel: "Nouveau niveau",
      editLevel: "Modifier le niveau",
      levelName: "Nom du niveau",
      levelNamePlaceholder: "Ex. : 2ème année BAC Sciences",
      sortOrder: "Ordre d'affichage",
      sortOrderHint: "Les niveaux sont triés du plus petit au plus grand.",
      deleteLevel: (name: string) => `Supprimer le niveau « ${name} » ?`,
      deleteLevelHint: "Possible seulement si le niveau n'a ni matière ni élève.",
      newSubject: "Ajouter une matière",
      editSubject: "Modifier la matière",
      subjectName: "Nom de la matière",
      subjectNamePlaceholder: "Ex. : Mathématiques",
      level: "Niveau",
      price: "Tarif mensuel (MAD)",
      priceHint: "Le tarif s'applique aux nouvelles inscriptions. Les inscriptions existantes gardent leur tarif d'inscription.",
      deleteSubject: (name: string) => `Supprimer la matière « ${name} » ?`,
      deleteSubjectHint: "Possible seulement si aucune inscription ne la référence.",
      enrolled: (count: number) => (count <= 1 ? `${count} inscrit` : `${count} inscrits`),
      studentsInLevel: (count: number) => (count <= 1 ? `${count} élève` : `${count} élèves`),
      noSubjects: "Aucune matière pour ce niveau.",
      packsTitle: "Packs",
      packsHint: "Plusieurs matières à un prix mensuel unique, sur une seule facture.",
      newPack: "Nouveau pack",
      editPack: "Modifier le pack",
      packName: "Nom du pack",
      packNamePlaceholder: "Ex. : Toutes matières",
      packPrice: "Prix mensuel du pack (MAD)",
      packPriceHint: "Le prix s'applique aux nouvelles souscriptions. Les abonnés gardent leur prix de souscription.",
      packSubjects: "Matières incluses",
      packSubjectsHint: "Les abonnés sont inscrits automatiquement à chaque matière cochée, et suivent les changements.",
      selectAll: "Tout cocher",
      packActive: "Proposer ce pack aux nouvelles inscriptions",
      unitTotal: (total: string) => `À l'unité, ces matières coûtent ${total} par mois.`,
      deletePack: (name: string) => `Supprimer le pack « ${name} » ?`,
      deletePackHint: "Possible seulement si le pack n'a jamais eu d'abonné. Sinon, décochez « Proposer ce pack ».",
      noPacks: "Aucun pack pour ce niveau.",
      needSubjects: "Ajoutez d'abord des matières à ce niveau.",
      emptyTitle: "Aucun niveau",
      emptyDescription: "Créez un premier niveau, puis ajoutez-y des matières et leurs tarifs.",
    },
    planning: {
      title: "Planning",
      description: "Créneaux hebdomadaires de tout le centre.",
      newSlot: "Nouveau créneau",
      editSlot: "Modifier le créneau",
      deleteSlot: "Supprimer le créneau",
      deleteConfirm: (subject: string, day: string, time: string) => `Supprimer le créneau ${subject}, ${day} ${time} ?`,
      subject: "Matière",
      teacher: "Professeur",
      day: "Jour",
      start: "Début",
      end: "Fin",
      room: "Salle",
      roomPlaceholder: "Ex. : Salle 1",
      chooseSubject: "Choisir une matière",
      chooseTeacher: "Choisir un professeur",
      noTeacher: "Aucun professeur n'est affecté à cette matière. Affectez-en un depuis « Utilisateurs ».",
      conflictTitle: "Conflit de planning",
      conflictRoom: (room: string, other: string) => `La salle ${room} est déjà occupée : ${other}.`,
      conflictTeacher: (teacher: string, other: string) => `${teacher} a déjà un cours : ${other}.`,
      conflictSlot: (subject: string, level: string, time: string) => `${subject} (${level}), ${time}`,
      filterLevel: "Niveau",
      allLevels: "Tous les niveaux",
      emptyTitle: "Aucun créneau",
      emptyDescription: "Créez les créneaux hebdomadaires du centre.",
      noSession: "Aucun créneau",
      noSubjectsTitle: "Aucune matière",
      noSubjectsDescription: "Créez d'abord des niveaux et des matières.",
    },
    users: {
      title: "Utilisateurs",
      description: "Comptes de l'équipe du centre.",
      newUser: "Nouvel utilisateur",
      editUser: "Modifier l'utilisateur",
      caption: "Comptes du centre",
      name: "Nom",
      role: "Rôle",
      email: "Email",
      phone: "Téléphone",
      status: "Statut",
      lastSignIn: "Dernière connexion",
      never: "Jamais",
      active: "Actif",
      inactive: "Désactivé",
      you: "Vous",
      deactivate: "Désactiver",
      reactivate: "Réactiver",
      deactivateConfirm: (name: string) => `Désactiver le compte de ${name} ?`,
      deactivateHint: "La personne ne pourra plus se connecter. Son historique est conservé.",
      deactivated: "Compte désactivé",
      reactivated: "Compte réactivé",
      assignments: "Matières enseignées",
      assignmentsHint: "Cochez chaque matière et niveau enseignés.",
      roleLocked: "Le rôle professeur ne peut pas être modifié.",
      password: "Mot de passe provisoire",
      passwordHint: "8 caractères minimum. À communiquer à la personne.",
      generate: "Générer",
      createdTitle: "Compte créé",
      createdDescription: "Transmettez ces identifiants. La personne peut se connecter immédiatement.",
      copy: "Copier les identifiants",
      copied: "Identifiants copiés",
      emptyTitle: "Aucun utilisateur",
      emptyDescription: "Créez les comptes de l'équipe.",
    },
    students: {
      title: "Élèves",
      description: "Liste complète, modification et suppression.",
      caption: "Élèves du centre",
      search: "Rechercher un élève",
      searchPlaceholder: "Nom de l'élève",
      filterLevel: "Niveau",
      allLevels: "Tous les niveaux",
      filterStatus: "Paiement",
      allStatuses: "Tous les statuts de paiement",
      name: "Élève",
      level: "Niveau",
      guardian: "Responsable",
      unpaid: "Reste dû",
      status: "Statut",
      results: (count: number) => (count <= 1 ? `${count} élève` : `${count} élèves`),
      emptyTitle: "Aucun élève trouvé",
      emptyDescription: "Modifiez la recherche ou les filtres.",
      edit: "Modifier l'élève",
      delete: "Supprimer l'élève",
      deleteConfirm: (name: string) => `Supprimer ${name} ?`,
      deleteHint: "Ses inscriptions, factures, présences et relances seront aussi supprimées.",
      deleted: "Élève supprimé",
      enrollments: {
        title: "Inscriptions",
        description: "Tarif et statut de chaque matière. Une réduction s'accorde par une remise.",
        price: "Tarif mensuel",
        active: "Active",
        inactive: "Arrêtée",
        stop: "Arrêter",
        resume: "Reprendre",
        add: "Inscrire à une matière",
        chooseSubject: "Choisir une matière",
        noOtherSubject: "L'élève est déjà inscrit à toutes les matières de son niveau.",
        alreadyEnrolled: "L'élève a déjà une inscription à cette matière : utilisez « Reprendre ».",
        addPack: "Souscrire un pack",
        choosePack: "Choisir un pack",
        packAdded: "Pack souscrit. La première facture a été créée.",
        packActiveHint: "L'élève a un pack actif : pour changer de formule, arrêtez d'abord le pack.",
        packNeedsStop: "Pour passer en pack, arrêtez d'abord les matières à l'unité.",
        saved: "Inscription mise à jour",
        added: "Inscription ajoutée. La première facture a été créée.",
      },
    },
    reports: {
      title: "Rapports",
      description: "Effectifs et assiduité. Export CSV compatible Excel.",
      export: "Exporter en CSV",
      byLevel: "Effectifs par niveau",
      bySubject: "Effectifs par matière",
      absenceRanking: "Classement des matières par taux d'absence",
      absenceRankingHint: "Du taux le plus élevé au plus faible.",
      period: "Période",
      periods: { "30": "30 derniers jours", "90": "90 derniers jours", all: "Depuis le début" } as Record<string, string>,
      level: "Niveau",
      subject: "Matière",
      students: "Élèves",
      enrollments: "Inscriptions actives",
      price: "Tarif mensuel",
      monthlyRevenue: "Revenu mensuel à l'unité",
      bySubjectHint: "Les inscriptions comptent aussi les élèves en pack ; le revenu, seulement les matières payées à l'unité.",
      byPack: "Packs",
      byPackHint: "Abonnements actifs et revenu mensuel (prix de souscription).",
      pack: "Pack",
      subscribers: "Abonnés",
      packRevenue: "Revenu mensuel",
      absences: "Absences",
      records: "Saisies",
      rate: "Taux d'absence",
      rank: "Rang",
      total: "Total",
      emptyTitle: "Aucune donnée",
      emptyDescription: "Les rapports se remplissent avec les inscriptions et les appels.",
    },
  },
  days: ["Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"],
  daysShort: ["Dim.", "Lun.", "Mar.", "Mer.", "Jeu.", "Ven.", "Sam."],
  teacher: {
    home: {
      title: "Accueil",
      greeting: (name: string) => `Bonjour ${name}`,
      todaySessions: "Séances du jour",
      sessionsCount: (count: number) => (count <= 1 ? `${count} séance` : `${count} séances`),
      takeAttendance: "Faire l'appel",
      editAttendance: "Modifier l'appel",
      attendanceDone: "Appel fait",
      attendancePartial: (marked: number, total: number) => `${marked} / ${total} marqués`,
      attendanceTodo: "Appel à faire",
      studentsCount: (count: number) => (count <= 1 ? `${count} élève` : `${count} élèves`),
      room: (room: string) => `Salle : ${room}`,
      emptyTitle: "Aucune séance aujourd'hui",
      emptyDescription: "Vos prochaines séances figurent dans votre emploi du temps.",
      seeSchedule: "Voir mon emploi du temps",
      stats: {
        sessionsToday: "Séances aujourd'hui",
        sessionsTodayDetail: (done: number) => (done <= 1 ? `${done} appel fait` : `${done} appels faits`),
        followedStudents: "Élèves suivis",
        followedStudentsDetail: (subjects: number) => (subjects <= 1 ? `Dans ${subjects} matière` : `Dans ${subjects} matières`),
        presenceRate: "Taux de présence",
        presenceRateDetail: "30 derniers jours, toutes vos matières",
      },
      mySessions: "Mes séances du jour",
      sessionDetail: (time: string, room: string) => `${time} · ${room}`,
      students: {
        title: "Mes élèves",
        caption: "Élèves de vos matières",
        name: "Nom",
        level: "Niveau",
        subject: "Matière",
        lastStatus: "Dernière séance",
        notMarked: "Pas encore d'appel",
        emptyTitle: "Aucun élève",
        emptyDescription: "Les élèves inscrits à vos matières apparaîtront ici.",
      },
    },
    schedule: {
      title: "Mon emploi du temps",
      description: "Vos séances de la semaine.",
      today: "Aujourd'hui",
      noSession: "Aucune séance",
      emptyTitle: "Aucune séance planifiée",
      emptyDescription: "L'administration n'a encore planifié aucune séance pour vous.",
      time: (start: string, end: string) => `${start} – ${end}`,
    },
    call: {
      close: "Quitter l'appel",
      closeConfirm: "Quitter l'appel ? Les marques non validées seront perdues.",
      progress: (current: number, total: number) => `Élève ${current} sur ${total}`,
      marked: (marked: number, total: number) => `${marked} / ${total} marqués`,
      previous: "Élève précédent",
      next: "Élève suivant",
      present: "Présent",
      absent: "Absent",
      notMarked: "Non marqué",
      hint: "Glissez pour changer d'élève. Au clavier : flèches, P (présent), A (absent).",
      summary: {
        title: "Récapitulatif",
        description: "Vérifiez l'appel. Touchez un élève pour corriger.",
        presentCount: (count: number) => (count <= 1 ? `${count} présent` : `${count} présents`),
        absentCount: (count: number) => (count <= 1 ? `${count} absent` : `${count} absents`),
        missing: (count: number) => (count <= 1 ? `${count} élève non marqué` : `${count} élèves non marqués`),
        toggle: (name: string, status: string) => `${name} : ${status}. Toucher pour changer.`,
        back: "Reprendre l'appel",
        submit: "Valider l'appel",
        submitting: "Enregistrement…",
      },
      success: "Appel enregistré",
      successDescription: (present: number, absent: number) => `${present} présent(s), ${absent} absent(s).`,
      notTodayTitle: "Séance hors de la journée",
      notTodayDescription: "L'appel ne peut être fait que le jour de la séance.",
      emptyTitle: "Aucun élève inscrit",
      emptyDescription: "Aucun élève n'est inscrit à cette matière pour le moment.",
      notFoundTitle: "Séance introuvable",
      notFoundDescription: "Cette séance n'existe pas ou ne vous est pas attribuée.",
      backHome: "Retour à l'accueil",
      errors: {
        notToday: "L'appel ne peut être enregistré que le jour de la séance.",
        incomplete: "Marquez tous les élèves avant de valider.",
      },
    },
  },
  assistant: {
    dashboard: {
      title: "Tableau de bord",
      stats: {
        unpaid: "Impayés",
        unpaidHint: (amount: string) => `${amount} à encaisser`,
        overdue: "En retard",
        overdueHint: (students: string, amount: string) => `${students} · ${amount}`,
        absencesToday: "Absences aujourd'hui",
        absencesTodayHint: "Signalées par les professeurs",
        absenceAlerts: "Alertes d'absences",
        absenceAlertsHint: "3 absences consécutives ou plus",
        overduePayments: "Paiements en retard",
        overduePaymentsDetail: (students: string, amount: string) => `${students} · ${amount}`,
        monthUnpaid: "Impayés du mois",
        monthUnpaidDetail: (count: number) =>
          count <= 1 ? `${count} facture du mois non réglée` : `${count} factures du mois non réglées`,
        absencesTodayDetail: (alerts: number) =>
          alerts <= 1 ? `${alerts} alerte d'absences ouverte` : `${alerts} alertes d'absences ouvertes`,
      },
      queue: {
        title: "Relances du jour",
        description: "Élèves en retard de paiement, du plus ancien retard au plus récent.",
        lastFollowUp: (date: string) => `Dernière relance le ${date}`,
        neverFollowedUp: "Jamais relancé",
        emptyTitle: "Aucune relance à faire aujourd'hui",
        emptyDescription: "Tous les élèves en retard ont été relancés aujourd'hui, ou aucun paiement n'est en retard.",
      },
      alerts: {
        title: "Alertes d'absences",
        description:
          "Élèves absents 3 séances de suite dans une matière. L'alerte se ferme après une relance « absence » ou au retour de l'élève.",
        absences: (count: number, subject: string) => `${count} absences consécutives en ${subject}`,
        lastSession: (date: string) => `Dernière séance le ${date}`,
        emptyTitle: "Aucune alerte d'absence",
        emptyDescription: "Aucun élève n'a manqué 3 séances de suite.",
      },
      openFile: "Voir la fiche",
    },
    search: {
      title: "Élèves",
      description: "Recherchez un élève par son nom.",
      label: "Rechercher un élève",
      placeholder: "Nom de l'élève",
      clear: "Effacer la recherche",
      results: (count: number) => (count <= 1 ? `${count} élève` : `${count} élèves`),
      searching: "Recherche…",
      emptyTitle: "Aucun élève trouvé",
      emptyDescription: "Vérifiez l'orthographe du nom, ou inscrivez un nouvel élève.",
      noStudentsTitle: "Aucun élève inscrit",
      noStudentsDescription: "Les élèves inscrits apparaîtront ici.",
      newStudent: "Nouvel élève",
    },
    student: {
      back: "Retour aux élèves",
      guardian: "Responsable",
      noGuardian: "Aucun responsable renseigné",
      notes: "Notes",
      enrolledOn: (date: string) => `Inscrit le ${date}`,
      tabsLabel: "Historique de l'élève",
      tabs: { payments: "Paiements", receipts: "Reçus", absences: "Absences", followUps: "Relances" },
      sections: {
        subjects: "Matières payées",
        payments: "Historique des paiements",
        absences: "Historique des absences",
        followUps: "Historique des relances",
      },
      subjects: {
        nextDue: (date: string) => `Prochaine échéance : ${date}`,
        upToDate: "Aucune échéance en attente",
        emptyTitle: "Aucune matière",
        emptyDescription: "Cet élève n'est inscrit à aucune matière.",
      },
      payments: {
        caption: "Factures de l'élève",
        subject: "Matière ou pack",
        period: "Période",
        amount: "Montant",
        dueDate: "Échéance",
        status: "Statut",
        paidOn: "Payé le",
        markPaid: "Marquer comme payé",
        confirmTitle: "Confirmer le paiement",
        confirmDescription: (amount: string, subject: string, period: string) =>
          `Paiement intégral de ${amount} pour ${subject}, ${period.toLowerCase()}.`,
        confirmLead: (subject: string, period: string) => `${subject}, ${period.toLowerCase()}.`,
        confirm: "Confirmer le paiement",
        success: "Paiement enregistré",
        alreadyPaid: "Cette facture est déjà payée.",
        emptyTitle: "Aucune facture",
        emptyDescription: "Les factures apparaîtront ici après l'inscription.",
      },
      absences: {
        total: (count: number) => (count <= 1 ? `${count} absence` : `${count} absences`),
        emptyTitle: "Aucune absence",
        emptyDescription: "Cet élève n'a manqué aucune séance.",
      },
      followUps: {
        by: (name: string) => `par ${name}`,
        emptyTitle: "Aucune relance",
        emptyDescription: "Les relances enregistrées apparaîtront ici.",
      },
      notFoundTitle: "Élève introuvable",
      notFoundDescription: "Cet élève n'existe pas ou n'appartient pas à votre centre.",
    },
    newStudent: {
      title: "Nouvel élève",
      description: "Inscription en quatre étapes.",
      progress: (step: number, total: number) => `Étape ${step} sur ${total}`,
      steps: ["Photo et identité", "Responsable", "Niveau et matières", "Récapitulatif"],
      fields: {
        photo: "Photo de l'élève",
        photoHint: "Facultative. Prise avec l'appareil photo du téléphone.",
        takePhoto: "Prendre une photo",
        retakePhoto: "Reprendre la photo",
        removePhoto: "Retirer la photo",
        compressing: "Préparation de la photo…",
        fullName: "Nom complet",
        fullNamePlaceholder: "Ex. : Salma Bennani",
        guardianName: "Nom du responsable",
        guardianNamePlaceholder: "Ex. : Mme Bennani",
        guardianPhone: "Téléphone du responsable",
        guardianPhonePlaceholder: "06 12 34 56 78",
        notes: "Notes",
        notesPlaceholder: "Allergies, informations utiles…",
        level: "Niveau",
        billingCycle: "Cycle de paiement",
        billingCycleHint: "Jour du mois où chaque nouvelle facture est due.",
        formula: "Formule",
        formulaUnit: "Matières à l'unité",
        formulaPack: "Pack",
        packs: "Pack choisi",
        packsHint: "L'élève est inscrit à toutes les matières du pack, sur une seule facture.",
        subjects: "Matières payées",
        subjectsHint: "Cochez les matières réglées par l'élève.",
        noSubjects: "Aucune matière n'est encore proposée pour ce niveau.",
        total: "Total mensuel",
      },
      summary: {
        identity: "Élève",
        guardian: "Responsable",
        subjects: "Matières",
        firstInvoice: (start: string, end: string, cycle: string) =>
          `Première facture : période du ${start} au ${end}, à régler aujourd'hui (${cycle}). Ensuite, une facture chaque mois ce jour-là ; impayée, elle passe en retard le jour même.`,
        edit: "Modifier",
      },
      previous: "Précédent",
      next: "Suivant",
      submit: "Inscrire l'élève",
      submitting: "Inscription…",
      success: "Élève inscrit",
      successDescription: "La première facture a été créée.",
      validation: {
        fullNameRequired: "Saisissez le nom de l'élève.",
        fullNameTooLong: "Le nom ne doit pas dépasser 100 caractères.",
        phoneInvalid: "Saisissez un numéro valide, par exemple 06 12 34 56 78.",
        notesTooLong: "Les notes ne doivent pas dépasser 500 caractères.",
        levelRequired: "Choisissez un niveau.",
        subjectsRequired: "Cochez au moins une matière.",
        packRequired: "Choisissez un pack.",
        photoInvalid: "Ce fichier n'est pas une image valide.",
        photoTooLarge: "La photo est trop lourde, même après compression.",
      },
      errors: {
        photoUpload: "La photo n'a pas pu être envoyée. Réessayez ou inscrivez l'élève sans photo.",
      },
      noLevelsTitle: "Aucun niveau configuré",
      noLevelsDescription: "L'administrateur doit d'abord créer les niveaux et les matières.",
    },
    newTeacher: {
      title: "Nouveau professeur",
      description: "Créez le compte et affectez les matières enseignées.",
      sections: {
        account: "Compte",
        assignments: "Matières enseignées",
      },
      fields: {
        fullName: "Nom complet",
        fullNamePlaceholder: "Ex. : Rachid Benali",
        phone: "Téléphone",
        phonePlaceholder: "06 12 34 56 78",
        email: "Email",
        emailPlaceholder: "prenom.nom@centre.ma",
        password: "Mot de passe provisoire",
        passwordHint: "8 caractères minimum. À communiquer au professeur.",
        generate: "Générer",
        showPassword: "Afficher le mot de passe",
        hidePassword: "Masquer le mot de passe",
        assignmentsHint: "Cochez chaque matière et niveau enseignés.",
      },
      submit: "Créer le compte",
      submitting: "Création…",
      validation: {
        fullNameRequired: "Saisissez le nom du professeur.",
        phoneInvalid: "Saisissez un numéro valide, par exemple 06 12 34 56 78.",
        emailRequired: "Saisissez l'email du professeur.",
        emailInvalid: "Cet email n'est pas valide.",
        passwordTooShort: "Le mot de passe doit contenir au moins 8 caractères.",
        assignmentsRequired: "Cochez au moins une matière.",
      },
      errors: {
        emailExists: "Un compte existe déjà avec cet email.",
        weakPassword: "Ce mot de passe est trop faible. Utilisez « Générer ».",
      },
      success: {
        title: "Compte créé",
        description: "Transmettez ces identifiants au professeur. Il pourra se connecter immédiatement.",
        email: "Email",
        password: "Mot de passe provisoire",
        copy: "Copier les identifiants",
        copied: "Identifiants copiés",
        credentials: (email: string, password: string) =>
          `CentroManager\nEmail : ${email}\nMot de passe provisoire : ${password}`,
        another: "Créer un autre professeur",
      },
      noSubjectsTitle: "Aucune matière configurée",
      noSubjectsDescription: "L'administrateur doit d'abord créer les niveaux et les matières.",
    },
  },
  table: {
    rowActions: "Actions",
  },
  errors: {
    genericTitle: "Impossible d'afficher cette page",
    genericDescription: "Vérifiez votre connexion internet, puis réessayez. Si le problème continue, contactez l'administrateur du centre.",
    notFoundTitle: "Page introuvable",
    notFoundDescription: "Cette page n'existe pas ou a été déplacée.",
    backHome: "Revenir à l'accueil",
  },
  styleguide: {
    tokens: {
      title: "Charte graphique",
      description: "Couleurs, typographie et formes de CentroManager.",
    },
    components: {
      title: "Composants",
      description: "Boutons, pastilles, photos, tableaux et indicateurs.",
    },
    states: {
      title: "États",
      description: "États vides, de chargement et d'erreur. Notifications.",
    },
    sections: {
      colors: "Couleurs",
      textShades: "Nuances de texte accessibles",
      typography: "Typographie",
      spacing: "Espacement",
      buttons: "Boutons",
      callButtons: "Boutons du mode appel",
      badges: "Pastilles de statut",
      avatars: "Photos élèves",
      table: "Tableau",
      stats: "Indicateurs",
      emptyState: "État vide",
      loading: "État de chargement",
      error: "État d'erreur",
      toasts: "Notifications",
    },
    swatches: {
      primary: "Bleu nuit principal",
      brand: "Bleu vif",
      highlight: "Ambre accent",
      success: "Vert succès",
      danger: "Rouge alerte",
      warning: "Orange attention",
      background: "Fond d'application",
      border: "Bordures",
      secondaryText: "Texte secondaire",
      text: "Texte principal",
    },
    textShadesHint: "Nuances plus sombres de la même teinte, utilisées pour le texte afin d'atteindre un contraste de 4,5:1.",
    typography: {
      title: "Titre de page — 28 px, 700",
      section: "Titre de section — 20 px, 600",
      body: "Corps — 15 px, 400. Les élèves à jour de leurs paiements portent une pastille verte.",
      caption: "Légende — 13 px, gris secondaire",
      amount: "Montant",
      date: "Date",
    },
    buttons: {
      primary: "Enregistrer",
      secondary: "Secondaire",
      outline: "Contour",
      ghost: "Discret",
      destructive: "Supprimer",
      highlight: "Faire l'appel",
      link: "Voir la fiche",
    },
    avatars: {
      list: "Liste — 40 px",
      profile: "Fiche — 96 px",
      call: "Appel — 200 px",
    },
    table: {
      student: "Élève",
      level: "Niveau",
      amount: "Montant dû",
      dueDate: "Échéance",
      status: "Statut",
    },
    stats: {
      collected: "Encaissé ce mois",
      expected: "Attendu ce mois",
      unpaid: "Impayés",
      absencesToday: "Absences aujourd'hui",
      vsLastMonth: "vs mois dernier",
    },
    emptyState: {
      title: "Aucun élève pour le moment",
      description: "Les élèves inscrits apparaîtront ici. Ajoutez votre premier élève.",
      action: "Ajouter un élève",
    },
    errorState: {
      title: "Chargement des élèves impossible",
      description: "La connexion au serveur a échoué. Vérifiez votre connexion internet, puis réessayez.",
    },
    toasts: {
      successTrigger: "Notification de succès",
      success: "Paiement enregistré",
      successDescription: "La facture est marquée comme payée.",
      errorTrigger: "Notification d'erreur",
      error: "Enregistrement impossible",
      errorDescription: "Vérifiez votre connexion, puis réessayez.",
    },
  },
} as const;

/**
 * Groupes contenant des termes métier (élève, niveau, matière, professeur,
 * séance) : ils suivent le vocabulaire du centre et se lisent uniquement via
 * getLabels() (serveur) ou useLabels() (client).
 */
type CenterNamespaces = "attendanceSheet" | "absencesPage" | "dashboard" | "roles" | "nav" | "spaces" | "billing" | "admin" | "teacher" | "assistant";

export type AppLabels = typeof TEXTS;

/** Libellés neutres, identiques pour tous les centres. */
export const LABELS: Omit<AppLabels, CenterNamespaces> = TEXTS;

const cache = new Map<string, AppLabels>();

/**
 * Libellés complets dans le vocabulaire d'un centre ; en marque blanche,
 * le nom de la plateforme est remplacé par celui de la marque du centre.
 */
export function labelsFor(terms: VocabularyTerms = DEFAULT_VOCABULARY, brandName?: string | null): AppLabels {
  const key = JSON.stringify([terms, brandName ?? null]);
  let labels = cache.get(key);
  if (!labels) {
    const vocabulary = translator(terms);
    const platformName = TEXTS.app.name;
    const translate = brandName && brandName !== platformName ? (text: string) => vocabulary(text).replaceAll(platformName, brandName) : vocabulary;
    labels = translateTree(TEXTS, translate);
    cache.set(key, labels);
  }
  return labels;
}
