import type { AppLabels } from "@/lib/constants/labels";

const plural = (n: number, one: string, two: string, few: string, many: string) =>
  n === 1 ? one : n === 2 ? two : n >= 3 && n <= 10 ? few : many;

/** « يوم واحد »، « يومان »، « 5 أيام »، « 12 يومًا ». */
const daysCount = (n: number) =>
  n === 1 ? "يوم واحد" : n === 2 ? "يومان" : `${n} ${plural(n, "يوم", "يومان", "أيام", "يومًا")}`;

/** « مركز واحد »، « مركزان »، « 5 مراكز »، « 12 مركزًا ». */
const centersCount = (n: number) =>
  n === 1 ? "مركز واحد" : n === 2 ? "مركزان" : `${n} ${plural(n, "مركز", "مركزان", "مراكز", "مركزًا")}`;

/** Libellés arabes : platform. */
export const AR_PART3: Pick<AppLabels, "platform"> = {
  platform: {
    moduleCatalogue: {
      finance: {
        name: "المالية",
        description: "أجور {the instructors} (أجر ثابت، عمولات)، وصولات قابلة للطباعة وعبر واتساب، المصاريف والدخل الصافي، التخفيضات، الصندوق اليومي.",
      },
      reenrollment: {
        name: "إعادة التسجيل",
        description: "حملات إعادة تسجيل تلقائية كل شهر، نوايا {the learners}، تذكيرات الأداء.",
      },
      absence_tracking: {
        name: "تتبع الغياب",
        description: "بطاقة مواظبة مفصلة، تنبيه بعد ثلاث غيابات، غيابات يجب الإبلاغ عنها ورسائل واتساب إلى ولي الأمر.",
      },
      white_label: {
        name: "العلامة البيضاء",
        description: "واجهة بألوان المركز: الاسم، الشعار، أيقونة الموقع، الألوان، نطاق خاص.",
      },
      lms: {
        name: "المنصة البيداغوجية",
        description: "فضاء {the instructors} للنشر (تمارين، امتحانات، ملخصات دروس) وفضاء {the learners} للاطلاع.",
      },
    },
    centerTypeNames: {
      soutien_scolaire: "مركز دعم مدرسي",
      centre_formation: "مركز تكوين",
      institut_langue: "معهد لغات",
      auto_ecole: "مدرسة لتعليم السياقة",
      soutien_universitaire: "مركز دعم جامعي",
      personnalise: "مخصص",
    },
    brand: "dirassty",
    centerStatus: {
      trial: "تجريبي",
      active: "نشط",
      past_due: "متأخر",
      suspended: "موقوف",
      cancelled: "ملغى",
    },
    plan: {
      starter: "المبتدئ",
      premium: "Premium",
      standard: "القياسي",
      white_label: "العلامة البيضاء",
    },
    interval: {
      month: "شهريًا",
      year: "سنويًا",
    },
    intervalShort: {
      month: "/ شهر",
      year: "/ سنة",
    },
    paymentMethod: {
      bank_transfer: "تحويل بنكي",
      cash: "نقدًا",
      card: "بطاقة",
    },
    noDueDate: "بدون تاريخ استحقاق",
    notSet: "غير محدد",
    daysRemaining: (days: number) =>
      days === 0 ? "الاستحقاق اليوم" : days > 0 ? `المتبقي: ${daysCount(days)}` : `التأخير: ${daysCount(-days)}`,
    dashboard: {
      title: "لوحة قيادة المنصة",
      description: "نظرة عامة على المراكز والاشتراكات والمبالغ المحصّلة.",
      centersByStatus: "المراكز حسب الحالة",
      mrr: "الإيراد الشهري المتكرر",
      mrrDetail: "المراكز النشطة والمتأخرة، مع احتساب الاشتراكات السنوية على أساس شهري",
      collected: "المحصّل هذا الشهر",
      students: "المتعلمون على المنصة",
      users: "حسابات المستخدمين",
      overdueTitle: "مراكز متأخرة في الأداء",
      overdueDescription: "تجاوزت تاريخ الاستحقاق، من الأقدم تأخرًا إلى الأحدث.",
      overdueEmpty: "لا يوجد أي مركز متأخر",
      overdueEmptyDescription: "جميع الاستحقاقات مؤداة في وقتها.",
      daysLate: (days: number) => `التأخير: ${daysCount(days)}`,
      dueSince: (date: string) => `استحقاق ${date}`,
      amountDue: "المبلغ المستحق",
      director: "المدير",
      call: "اتصال",
      email: "مراسلة",
      callLabel: (name: string) => `الاتصال بمدير ${name}`,
      emailLabel: (name: string) => `مراسلة مدير ${name}`,
      openCenter: "عرض الملف",
      upcomingTitle: "الاستحقاقات خلال الأيام السبعة القادمة",
      upcomingEmpty: "لا توجد استحقاقات خلال الأيام السبعة القادمة.",
      dueOn: (date: string) => `الاستحقاق يوم ${date}`,
      remindersTitle: "التذكيرات المُعدّة",
      remindersDescription:
        "رسائل بريد إلكتروني تُعدّ كل ليلة (قبل 7 أيام، قبل يوم، يوم الاستحقاق، الإيقاف). سيُفعَّل الإرسال التلقائي مع خدمة البريد الإلكتروني.",
      remindersEmpty: "لا توجد تذكيرات مُعدّة مؤخرًا.",
      reminderKinds: {
        due_in_7: "الاستحقاق بعد 7 أيام",
        due_in_1: "الاستحقاق غدًا",
        due_today: "الاستحقاق اليوم",
        suspended: "الولوج موقوف",
        owner_digest: "ملخص",
      },
      reminderPending: "للإرسال",
      reminderSent: "أُرسل",
      noRecipient: "بدون بريد إلكتروني",
    },
    centers: {
      title: "المراكز",
      description: "جميع مراكز المنصة.",
      searchLabel: "البحث عن مركز",
      searchPlaceholder: "اسم المركز أو عنوانه",
      search: "بحث",
      filterStatus: "التصفية حسب الحالة",
      filterType: "التصفية حسب نوع المؤسسة",
      filterPlan: "التصفية حسب الباقة",
      allStatuses: "جميع الحالات",
      allTypes: "جميع الأنواع",
      allPlans: "جميع الباقات",
      caption: "قائمة المراكز",
      address: "العنوان",
      name: "المركز",
      type: "النوع",
      plan: "الباقة",
      status: "الحالة",
      activatedAt: "التفعيل",
      dueDate: "تاريخ الاستحقاق",
      remaining: "المهلة",
      students: "المتعلمون",
      price: "السعر",
      count: (n: number) => centersCount(n),
      empty: "لا توجد مراكز",
      emptyDescription: "لا يوجد أي مركز يطابق هذه المعايير.",
    },
    center: {
      back: "جميع المراكز",
      notFound: "المركز غير موجود",
      identity: "المعلومات",
      slug: "عنوان المركز",
      formerSlugs: (list: string) => `العناوين السابقة (مُحوَّلة إلى العنوان الحالي): ${list}`,
      type: "نوع المؤسسة",
      createdAt: "تاريخ الإنشاء",
      activatedAt: "تاريخ التفعيل",
      cancelledAt: "تاريخ الإلغاء",
      contact: "جهة اتصال المدير",
      notes: "ملاحظات داخلية",
      noNotes: "لا توجد ملاحظات.",
      subscription: "الاشتراك",
      plan: "الباقة",
      price: "السعر",
      dueDate: "تاريخ الاستحقاق",
      periodStart: "الفترة الحالية منذ",
      graceDays: "مهلة السماح",
      graceDaysValue: (days: number) => daysCount(days),
      autoRenew: "التجديد التلقائي",
      yes: "نعم",
      no: "لا",
      students: "المتعلمون",
      users: "الحسابات",
      payments: "سجل الأداءات",
      paymentsEmpty: "لا يوجد أي أداء مسجَّل.",
      paidAt: "تاريخ الأداء",
      amount: "المبلغ",
      periodCovered: "الفترة المشمولة",
      method: "الطريقة",
      reference: "المرجع",
      recordedBy: "سجّله",
      history: "السجل",
      historyEmpty: "لا توجد أحداث.",
      automatic: "تلقائي",
      branding: "العلامة البيضاء",
      brandingStandard: "وحدة العلامة البيضاء غير مفعّلة: الواجهة بألوان dirassty.",
      brandingEmpty: "لا توجد إعدادات علامة مسجَّلة.",
      brandName: "اسم العلامة",
      colors: "الألوان",
      customDomain: "نطاق مخصص",
      domainVerified: "تم التحقق",
      domainPending: "في انتظار التحقق",
      supportContact: "الدعم",
      usersTitle: "حسابات المركز",
      usersEmpty: "لا توجد حسابات.",
      userName: "الاسم",
      userEmail: "البريد الإلكتروني",
      userRole: "الدور",
      userState: "الحالة",
      userActive: "نشط",
      userInactive: "معطَّل",
      lastSignIn: "آخر تسجيل دخول",
      never: "أبدًا",
      vocabulary: "المصطلحات",
      periodRange: (from: string, to: string) => `من ${from} إلى ${to}`,
    },
    events: {
      "center.created": "تم إنشاء المركز",
      "center.status_changed": "تم تعديل الحالة",
      "center.period_changed": "تم تعديل تاريخ الاستحقاق",
      "center.pricing_changed": "تم تعديل السعر",
      "center.vocabulary_changed": "تم تعديل نوع المؤسسة",
      "center.identity_changed": "تم تعديل الاسم أو العنوان",
      "subscription.plan_changed": "تم تعديل الصيغة",
      "center.plan_changed": "تم تعديل الباقة",
      "center.module_enabled": "تم تفعيل الوحدة",
      "center.module_disabled": "تم إيقاف الوحدة",
      "plan.updated": "تم تعديل باقة الكتالوج",
      "subscription.auto_renew_changed": "تم تعديل التجديد",
      "subscription.payment_recorded": "تم تسجيل أداء",
      "branding.updated": "تم تعديل العلامة البيضاء",
      "center.details_changed": "تم تعديل المعلومات",
      "center.admin_invited": "تمت دعوة المدير",
      "platform.settings_changed": "تم تعديل الإعدادات",
      "center.admin_password_reset": "تمت إعادة تعيين كلمة مرور المدير",
      "center.password_link_sent": "تم إرسال رابط كلمة المرور",
      "support.started": "تم فتح ولوج الدعم",
      "support.ended": "تم إغلاق ولوج الدعم",
    },
    eventFallback: "إجراء",
    modules: {
      title: "الوحدات",
      description: "الوظائف المفعّلة لهذا المركز. تفعّلها باقته؛ ويمكن أيضًا تفعيل كل وحدة أو إيقافها على حدة.",
      disableHint: "إيقاف وحدة يُخفي شاشاتها ويمنع الولوج إليها من جهة الخادم؛ ولا تُحذف أي بيانات.",
      inPlan: "مشمولة في الباقة",
      notInPlan: "خارج الباقة",
      source: { plan: "حسب الباقة", manual: "على حدة", trial: "تجريبي" },
      enabled: "مفعّلة",
      disabled: "موقوفة",
      switchLabel: (name: string) => `وحدة ${name}`,
      trial: "تجريبي",
      trialHint: "تفعيل هذه الوحدة خارج الباقة على سبيل التجربة",
      enabledSince: (date: string) => `مفعّلة منذ ${date}`,
      saved: "تم تحديث الوحدة.",
      readOnly: "قراءة فقط في وضع الدعم.",
    },
    catalogue: {
      title: "الكتالوج",
      description: "الباقات التجارية والوحدات القابلة للتفعيل. يبقى سعر المركز هو سعر اشتراكه.",
      plans: "الباقات",
      modules: "الوحدات",
      monthlyPrice: "سعر الكتالوج (MAD شهريًا)",
      centersCount: (n: number) => centersCount(n),
      includes: "الوحدات المشمولة",
      inPlans: "ضمن الباقات",
      noPlan: "خارج كل باقة: تفعيل على حدة",
      edit: "تعديل",
      editTitle: (name: string) => `تعديل باقة ${name}`,
      name: "الاسم",
      descriptionLabel: "الوصف",
      saved: "تم تحديث الباقة.",
      categories: { gestion: "التسيير", finance: "المالية", suivi: "المتابعة", marque: "العلامة", pedagogie: "البيداغوجيا" },
      core: {
        title: "الأساس، مفعّل دائمًا",
        items: [
          "ثلاثة أدوار: الإدارة، الاستقبال، {instructor}",
          "{the learners}، التسجيلات، باقات {the courses}، الفواتير والتحصيلات",
          "التخطيط والقاعات مع رصد التعارضات",
          "تسجيل الحضور من طرف {the instructor} ومن طرف الاستقبال",
          "الموظفون، الإحصائيات والمصطلحات حسب نوع المؤسسة",
        ],
      },
      rule: {
        title: "قاعدة الطلبات المستقبلية",
        items: [
          "مفيدة لأغلب المراكز: تنضم الوظيفة إلى الأساس.",
          "مفيدة لمجموعة من المراكز: تصبح وحدة ضمن باقة موجودة أو باقة جديدة.",
          "خاصة بعميل واحد: تُرفض، أو تُفوتر حسب الطلب وتُسلَّم كوحدة خلف مفتاح تفعيل، وليس أبدًا كنسخة من الشيفرة.",
        ],
      },
    },
    reason: (text: string) => `السبب: ${text}`,
    validation: {
      nameRequired: "أدخل اسمًا.",
      tooLong: "هذا النص طويل جدًا.",
      phoneInvalid: "رقم غير صالح (مثال: 06 12 34 56 78).",
      emailRequired: "أدخل بريدًا إلكترونيًا.",
      emailInvalid: "هذا البريد الإلكتروني غير صالح.",
      slugInvalid: "من 2 إلى 63 حرفًا: حروف لاتينية صغيرة وأرقام وشرطات.",
      slugReserved: "هذا العنوان محجوز للمنصة.",
      typeRequired: "اختر نوع المؤسسة.",
      termRequired: "أدخل هذا المصطلح.",
      amountInvalid: "مبلغ غير صالح (مثال: 490 أو 490,50).",
      graceInvalid: "بين 0 و60 يومًا.",
      dateInvalid: "تاريخ غير صالح.",
      dueAfterActivation: "يجب أن يكون تاريخ الاستحقاق بعد تاريخ التفعيل.",
      reasonRequired: "أدخل السبب.",
      planRequired: "اختر باقة.",
    },
    errors: {
      emailExists: "هذا البريد الإلكتروني لديه حساب على المنصة مسبقًا.",
      inviteFailed: "تعذّر إرسال الدعوة. أعد المحاولة.",
      slugTaken: "هذا العنوان مستعمل من طرف مركز آخر.",
    },
    newCenter: {
      title: "مركز جديد",
      open: "مركز جديد",
      steps: ["الهوية", "نوع المؤسسة", "الباقة والسعر", "حساب المدير"],
      progress: (current: number, total: number) => `الخطوة ${current} من ${total}`,
      previous: "السابق",
      next: "التالي",
      submit: "إنشاء المركز ودعوة المدير",
      submitting: "جارٍ الإنشاء…",
      success: "تم إنشاء المركز",
      successDescription: (email: string) => `تم إرسال الدعوة إلى ${email}.`,
      name: "اسم المركز",
      namePlaceholder: "مركز الأمل — الرباط",
      slug: "عنوان المركز",
      slugHint: "النطاق الفرعي للمركز (مثال: al-amal). حروف لاتينية صغيرة وأرقام وشرطات.",
      ownerName: "اسم المدير",
      ownerPhone: "هاتف المدير",
      ownerEmail: "البريد الإلكتروني للمدير",
      notes: "ملاحظات داخلية",
      notesHint: "تظهر في لوحة التحكم فقط.",
      optional: "اختياري",
      typeLegend: "نوع المؤسسة",
      typeHint: "يحدد مصطلحات واجهة المركز بأكملها.",
      customTitle: "مصطلحات مخصصة",
      customHint: "أدخل كل مصطلح بصيغة المفرد والجمع، مع جنسه لضبط المطابقة.",
      termKeys: {
        learner: "المتعلم",
        group: "المجموعة",
        course: "المادة",
        instructor: "المؤطر",
        session: "الحصة",
      },
      singular: "المفرد",
      plural: "الجمع",
      gender: "الجنس",
      masculine: "مذكر",
      feminine: "مؤنث",
      preview: (learners: string, instructors: string, courses: string) => `${learners} · ${instructors} · ${courses}`,
      plan: "الباقة",
      planPrice: (price: string) => `سعر الكتالوج: ${price} شهريًا`,
      price: "المبلغ (MAD)",
      interval: "مدة الفوترة",
      intervalOptions: { month: "شهري", year: "سنوي" },
      graceDays: "مهلة السماح (بالأيام)",
      graceHint: "بعد تاريخ الاستحقاق، يبقى المركز قابلًا للاستعمال خلال هذا العدد من الأيام قبل الإيقاف.",
      status: "الانطلاق",
      statusOptions: { trial: "فترة تجريبية", active: "نشط منذ التفعيل" },
      activationDate: "تاريخ التفعيل",
      firstDueDate: "أول تاريخ استحقاق",
      firstDueHint: "مقترح تلقائيًا: التفعيل + شهر (أو سنة). قابل للتعديل.",
      adminName: "اسم مدير المركز",
      adminEmail: "البريد الإلكتروني للمدير",
      adminEmailHint: "يتلقى دعوة ويختار كلمة المرور عند أول ولوج.",
      adminPhone: "هاتف المدير",
      summary: "ملخص",
    },
    accessLink: {
      title: "رابط الولوج المراد إرساله",
      description: (email: string) =>
        `تعذّر على خدمة البريد الإلكتروني إرسال الرسالة (تم بلوغ حد الإرسال). انسخ هذا الرابط وأرسله إلى ${email}، عبر WhatsApp مثلًا: يتيح له اختيار كلمة المرور.`,
      personal: "رابط شخصي يُستعمل مرة واحدة: لا تشاركه إلا مع هذا الشخص.",
      copy: "نسخ الرابط",
      copied: "تم نسخ الرابط",
      continue: "متابعة",
    },
    actions: {
      title: "الإجراءات",
      recordPayment: "تسجيل أداء",
      dueDate: "تعديل تاريخ الاستحقاق",
      pricing: "الصيغة والسعر",
      details: "تعديل المعلومات",
      suspend: "إيقاف",
      reactivate: "إعادة التفعيل",
      cancel: "إلغاء الاشتراك",
      resendInvitation: "إعادة إرسال الدعوة",
      invitationSent: "تمت إعادة إرسال الدعوة",
      passwordLink: "إرسال رابط كلمة المرور",
      passwordLinkSent: "تم إرسال رابط كلمة المرور",
      saved: "تم حفظ التعديلات",
      save: "حفظ",
      saving: "جارٍ الحفظ…",
      paymentTitle: "تسجيل أداء",
      paymentDescription: (period: string) => `يغطي الأداء ${period} ابتداءً من تاريخ الاستحقاق الحالي ويعيد تشغيل المركز.`,
      periodMonth: "شهرًا واحدًا",
      periodYear: "سنة واحدة",
      paymentAmount: "المبلغ (MAD)",
      paymentDate: "تاريخ الأداء",
      paymentMethod: "طريقة الأداء",
      paymentReference: "المرجع",
      paymentReferenceHint: "رقم التحويل، رقم الوصل… (اختياري)",
      paymentSaved: "تم تسجيل الأداء",
      dueDateTitle: "تعديل تاريخ الاستحقاق",
      dueDateDescription: "تحديد تاريخ الاستحقاق أو تمديده. المركز المتأخر الذي يصبح تاريخ استحقاقه في المستقبل يعود نشطًا.",
      newDueDate: "تاريخ الاستحقاق الجديد",
      reasonOptional: "السبب (اختياري)",
      reason: "السبب",
      reasonPlaceholder: "مثال: مهلة ممنوحة إلى حين التحويل",
      pricingTitle: "الصيغة والسعر",
      detailsTitle: "معلومات المركز",
      statusTitle: {
        active: "إعادة تفعيل المركز",
        suspended: "إيقاف المركز",
        cancelled: "إلغاء اشتراك المركز",
      },
      support: "ولوج الدعم (قراءة فقط)",
      supportTitle: "ولوج الدعم للقراءة فقط",
      supportDescription:
        "ستطّلع على فضاء الإدارة الخاص بالمركز لمدة ساعة واحدة، دون إمكانية تعديل أي شيء. يُسجَّل هذا الولوج ويبقى شريط تنبيه ظاهرًا.",
      supportSubmit: "فتح ولوج الدعم",
      supportReasonPlaceholder: "مثال: أبلغ المدير عن مشكل في التخطيط",
      statusDescription: {
        active:
          "تستعيد حسابات المركز الولوج فورًا. إذا كان تاريخ الاستحقاق قد تجاوز، فقم بتمديده: وإلا ستوقف المراقبة اليومية المركز من جديد.",
        suspended: "سيُمنع تسجيل الدخول لجميع حسابات المركز. تُحفظ البيانات.",
        cancelled: "إجراء نهائي: لن يكون بالإمكان إعادة تفعيل المركز. تبقى البيانات قابلة للتصدير لمدة 90 يومًا.",
      },
      statusSaved: {
        active: "تمت إعادة تفعيل المركز",
        suspended: "تم إيقاف المركز",
        cancelled: "تم إلغاء اشتراك المركز",
      },
    },
    settings: {
      title: "إعدادات المنصة",
      description: "جهة الاتصال المعروضة على المراكز الموقوفة لتسوية اشتراكها.",
      contactTitle: "جهة اتصال التسوية",
      name: "الاسم المعروض",
      namePlaceholder: "خدمة عملاء dirassty",
      phone: "الهاتف",
      email: "البريد الإلكتروني",
      saved: "تم حفظ الإعدادات",
      updatedAt: (date: string) => `آخر تعديل: ${date}`,
    },
    billing: {
      title: "الفوترة",
      description: "أداءات اشتراك جميع المراكز.",
      monthsTitle: "المحصّل حسب الشهر",
      monthsDescription: "توقعات الشهر الحالي: استحقاقات الشهر للمراكز العاملة، حسب سعر صيغتها.",
      month: "الشهر",
      collected: "المحصّل",
      expected: "المتوقع",
      gap: "الفارق",
      currentMonth: "هذا الشهر",
      paymentsTitle: "جميع الأداءات",
      center: "المركز",
      empty: "لا توجد أداءات",
      emptyDescription: "ستظهر هنا أداءات الاشتراك المسجَّلة.",
    },
  },
};
