import type { AppLabels } from "@/lib/constants/labels";

const plural = (n: number, one: string, two: string, few: string, many: string) =>
  n === 1 ? one : n === 2 ? two : n >= 3 && n <= 10 ? few : many;

/** Libellés arabes : absencesPage, dashboard, roles, nav, passwords, centerAddress, centerHost, auth, branding. */
export const AR_PART2: Pick<AppLabels, "absencesPage" | "dashboard" | "roles" | "nav" | "passwords" | "centerAddress" | "centerHost" | "auth" | "branding"> = {
  absencesPage: {
    title: "الغيابات",
    description: (date: string) => `غيابات {the learners} يوم ${date}.`,
    date: "التاريخ",
    today: "اليوم",
    count: (count: number) => plural(count, "غياب واحد", "غيابان", `${count} غيابات`, `${count} غيابًا`),
    subject: "{the course}",
    teacher: "{the instructor}",
    openFile: "عرض الملف",
    emptyTitle: "لا توجد أي غيابات",
    emptyDescription: "لم يُسجَّل غياب أي {learner} في ذلك اليوم.",
    streak: (count: number) =>
      plural(count, "غياب واحد", "غيابان متتاليان", `${count} غيابات متتالية`, `${count} غيابًا متتاليًا`),
  },
  dashboard: {
    statsTitle: "الإحصائيات",
    detail: "عرض التفاصيل",
    moreActions: (label: string) => `إجراءات — ${label}`,
    students: {
      title: "لائحة {the learners}",
      caption: "{learners} المركز",
      name: "الاسم",
      level: "{the group}",
      subjects: "{the course}",
      status: "الحالة",
      phone: "هاتف ولي الأمر",
      actions: "الإجراءات",
      sortBy: (column: string) => `ترتيب حسب ${column}`,
      search: "البحث في اللائحة",
      searchPlaceholder: "اسم {the learner}",
      openFile: "عرض الملف",
      call: "اتصال",
      whatsapp: "WhatsApp",
      rowActions: (name: string) => `إجراءات — ${name}`,
      emptyTitle: "لا يوجد أي {learner}",
      emptyDescription: "ستظهر هنا لائحة {the learners} بعد تسجيلهم.",
      noMatch: "لا توجد أي نتيجة تطابق هذا البحث.",
    },
    reminder: {
      title: "تذكير",
      cardTitle: "متابعات اليوم",
      cardDescription: (count: number) =>
        count === 0
          ? "لا يوجد أي {learner} للمتابعة اليوم."
          : `عدد {the learners} في وضعية تأخر للتواصل معهم اليوم: ${count}.`,
      link: "عرض اللائحة",
      dismiss: "إخفاء التذكير",
    },
    presence: {
      title: "الحضور حسب {the course}",
      ring: "الحضور",
      detail: (level: string, students: number) => `${level} · {the learners}: ${students}`,
      link: "عرض التفاصيل",
      emptyTitle: "لم يُسجَّل أي حضور",
      emptyDescription: "ستظهر النسب بعد أول تسجيل للحضور.",
    },
  },
  roles: {
    admin: "المدير",
    super_admin: "مالك المنصة",
    assistant: "مساعد",
    teacher: "{instructor}",
  },
  nav: {
    mainLabel: "التنقل الرئيسي",
    searchStudent: "البحث عن {learner}",
    styleguideTokens: "الميثاق البصري",
    styleguideComponents: "المكونات",
    styleguideStates: "الحالات",
    dashboard: "لوحة القيادة",
    students: "{the learners}",
    newStudent: "إضافة {learner}",
    newTeacher: "إضافة {instructor}",
    home: "الرئيسية",
    schedule: "استعمال الزمن",
    subjects: "{the groups} و{the courses}",
    planning: "التخطيط",
    users: "المستخدمون",
    reports: "التقارير",
    absences: "الغيابات",
    platformCenters: "المراكز",
    platformCatalogue: "الكتالوج",
    platformBilling: "الفوترة",
    platformSettings: "الإعدادات",
    branding: "الهوية البصرية",
    settings: "الإعدادات",
    payroll: "الأجور",
    expenses: "المصاريف",
    rooms: "القاعات",
    reenrollment: "إعادة التسجيل",
    cash: "الصندوق",
    sessions: "{sessions} اليوم",
    resources: "الموارد",
    short: {
      sessions: "{the sessions}",
      dashboard: "الرئيسية",
      subjects: "{the courses}",
      newStudent: "تسجيل",
      newTeacher: "{instructor}",
    },
  },
  passwords: {
    reset: "إعادة تعيين كلمة المرور",
    resetFor: (name: string) => `إعادة تعيين كلمة المرور — ${name}`,
    resetAdmin: "إعادة تعيين كلمة مرور المدير",
    resetTitle: (name: string) => `كلمة مرور جديدة لـ ${name}`,
    resetDescription:
      "كلمة المرور الحالية غير مرئية أبدًا. ستحدد كلمة مرور جديدة مؤقتة: يُسجَّل خروج الشخص من جميع أجهزته، وعليه تغييرها عند تسجيل دخوله المقبل.",
    modeLegend: "كلمة مرور مؤقتة",
    modeGenerate: "توليد تلقائي (10 أحرف سهلة القراءة)",
    modeManual: "إدخالها بنفسي",
    manualLabel: "كلمة مرور مؤقتة",
    manualHint: "8 أحرف على الأقل.",
    confirm: "إعادة التعيين",
    confirming: "جارٍ إعادة التعيين…",
    cancel: "إلغاء",
    doneTitle: "كلمة مرور مؤقتة",
    doneDescription: "لن تُعرض مرة أخرى أبدًا: انسخها أو أرسلها الآن.",
    password: "كلمة المرور المؤقتة",
    loginCode: "رمز الدخول",
    address: "عنوان تسجيل الدخول",
    copy: "نسخ",
    copied: "تم النسخ.",
    message: "رسالة WhatsApp (قابلة للتعديل)",
    whatsapp: "إرسال عبر WhatsApp",
    noPhone: "لا يوجد رقم هاتف مسجَّل: سلِّم كلمة المرور شفهيًا.",
    done: "لقد سلّمت كلمة المرور",
    staffMessage: (name: string, url: string, password: string) =>
      `مرحبًا ${name}، تمت إعادة تعيين كلمة المرور الخاصة بك. سجّل الدخول عبر ${url} باستعمال كلمة المرور المؤقتة ${password}، ثم اختر كلمة مرور جديدة.`,
    studentMessage: (name: string, url: string, code: string, password: string) =>
      `مرحبًا، إليكم معلومات الدخول الجديدة لـ ${name}: ${url} — الرمز ${code}، كلمة المرور المؤقتة ${password}. سيُطلب اختيار كلمة مرور جديدة عند تسجيل الدخول.`,
    lastReset: (date: string, by: string) => `أُعيد تعيين كلمة المرور يوم ${date} من طرف ${by}`,
    lastResetByYou: (date: string) => `أُعيد تعيين كلمة المرور يوم ${date} من طرفك`,
    unknownActor: "أحد المسؤولين",
    errors: {
      forbidden: "الوصول مرفوض: لا يمكنك إعادة تعيين كلمة مرور هذا الحساب.",
      rate_limited: "عدد كبير جدًا من عمليات إعادة التعيين خلال ساعة. أعد المحاولة لاحقًا.",
      inactive: "هذا الحساب معطَّل: أعد تفعيله أولًا.",
      not_found: "الحساب غير موجود.",
      failed: "تعذّر تغيير كلمة المرور. أعد المحاولة.",
    },
    admins: {
      title: "مدير المركز",
      titlePlural: "مديرو المركز",
      none: "لا يوجد أي مدير.",
      lastSignIn: "آخر تسجيل دخول",
      never: "لم يسجّل الدخول قط",
    },
    mine: {
      menu: "كلمة المرور الخاصة بي",
      title: "كلمة المرور الخاصة بي",
      description: "أدخل كلمة المرور الحالية، ثم الجديدة.",
      current: "كلمة المرور الحالية",
      next: "كلمة المرور الجديدة",
      confirm: "تأكيد كلمة المرور الجديدة",
      submit: "حفظ",
      submitting: "جارٍ الحفظ…",
      saved: "تم تغيير كلمة المرور. تم تسجيل الخروج من أجهزتك الأخرى.",
      wrongCurrent: "كلمة المرور الحالية غير صحيحة.",
      back: "رجوع",
    },
    forced: {
      title: "اختر كلمة مرورك الجديدة",
      description:
        "حدّد أحد المسؤولين كلمة مرورك. اختر كلمة مرور شخصية للمتابعة: لن يعرفها أحد غيرك.",
      submit: "تأكيد ومتابعة",
    },
    validation: {
      required: "أدخل كلمة مرور.",
      tooShort: "8 أحرف على الأقل.",
      tooLong: "72 حرفًا على الأكثر.",
      mismatch: "كلمتا المرور غير متطابقتين.",
      sameAsOld: "اختر كلمة مرور مختلفة عن الحالية.",
      weak: "كلمة المرور ضعيفة جدًا: أضف حروفًا أو أرقامًا أو رموزًا.",
      currentRequired: "أدخل كلمة المرور الحالية.",
    },
    strength: {
      label: "القوة",
      levels: ["", "ضعيفة", "متوسطة", "جيدة", "ممتازة"],
    },
    sessionClosed: "تم إغلاق جلستك (تغيّرت كلمة المرور). المرجو تسجيل الدخول من جديد.",
    unavailable: "الخدمة غير متاحة مؤقتًا. أعد المحاولة.",
  },
  centerAddress: {
    label: "عنوان المركز",
    preview: "معاينة",
    copy: "نسخ",
    copied: "تم نسخ العنوان.",
    copyFailed: "تعذّر النسخ: حدّد العنوان يدويًا.",
    open: "فتح",
    checking: "جارٍ التحقق من العنوان…",
    status: {
      available: "العنوان متاح.",
      current: "العنوان الحالي للمركز.",
      taken: "العنوان مستعمل من طرف مركز آخر.",
      reserved: "العنوان محجوز للمنصة.",
      invalid: "من 2 إلى 63 حرفًا: حروف لاتينية صغيرة وأرقام وشرطات (لا في البداية ولا في النهاية).",
    },
    change: "تغيير العنوان",
    changeTitle: "تغيير عنوان المركز",
    changeDescription:
      "سيستمر العنوان القديم في التحويل إلى العنوان الجديد. سيتعيّن على حسابات المركز تسجيل الدخول من جديد: أخبِر المركز بذلك.",
    newSlug: "العنوان الجديد",
    confirmLabel: (from: string, to: string) => `أؤكد الانتقال من ${from} إلى ${to}.`,
    submit: "تغيير العنوان",
    submitting: "جارٍ التغيير…",
    changed: "تم تغيير عنوان المركز.",
    cancel: "إلغاء",
  },
  centerHost: {
    unavailable: "الخدمة غير متاحة مؤقتًا. أعد المحاولة بعد لحظات.",
    notFoundTitle: "المركز غير موجود",
    notFoundDescription: "لا يوجد أي مركز يطابق هذا العنوان. تحقّق من العنوان الذي زوّدك به مركزك.",
    notFoundLink: (root: string) => `الانتقال إلى ${root}`,
    wrongCenter: "هذا الحساب لا ينتمي إلى هذا المركز. سجّل الدخول من عنوان مركزك:",
    platformAccount: "هذا الحساب خاص بلوحة تحكم المنصة. سجّل الدخول من عنوانها:",
    transferred:
      "أصبح لمركزك عنوان خاص به. سجّل الدخول هنا مرة أخرى (مرة واحدة فقط)، ثم احفظ هذا العنوان في المفضلة:",
  },
  auth: {
    login: {
      title: "تسجيل الدخول",
      description: "ادخل إلى فضاء مركزك.",
      email: "البريد الإلكتروني",
      emailPlaceholder: "name@centre.ma",
      password: "كلمة المرور",
      showPassword: "إظهار كلمة المرور",
      hidePassword: "إخفاء كلمة المرور",
      submit: "تسجيل الدخول",
      submitting: "جارٍ تسجيل الدخول…",
      forgotten: "نسيت كلمة المرور؟ تواصل مع مدير مركزك.",
    },
    validation: {
      emailRequired: "أدخل بريدك الإلكتروني.",
      emailInvalid: "هذا البريد الإلكتروني غير صالح.",
      passwordRequired: "أدخل كلمة المرور.",
    },
    errors: {
      invalidInput: "تحقّق من حقول الاستمارة.",
      invalidCredentials: "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
      rateLimited: "محاولات كثيرة جدًا. انتظر بضع دقائق، ثم أعد المحاولة.",
      unavailable: "تعذّر تسجيل الدخول حاليًا. تحقّق من اتصالك بالإنترنت، ثم أعد المحاولة.",
      inactive: "هذا الحساب معطَّل. تواصل مع مدير مركزك.",
    },
    inactive: {
      title: "حساب غير نشط",
      description:
        "حسابك معطَّل أو غير مرتبط بأي مركز. تواصل مع مدير مركزك لإعادة تفعيله.",
      retry: "التحقق من جديد",
    },
    userMenu: {
      label: "قائمة الحساب",
      myPhoto: "صورتي",
      signOut: "تسجيل الخروج",
    },
    photo: {
      title: "صورتي",
      description: "مرئية لفريق مركزك.",
      adminTitle: (name: string) => `صورة ${name}`,
      adminDescription: "مرئية لفريق المركز.",
      label: "الصورة",
      hint: "التقطها بالكاميرا، أو اخترها من ملفاتك.",
      save: "حفظ الصورة",
      remove: "إزالة الصورة",
      saved: "تم حفظ الصورة",
      removed: "تمت إزالة الصورة",
      change: (name: string) => `تغيير الصورة — ${name}`,
      uploadFailed: "تعذّر رفع الصورة. أعد المحاولة.",
    },
  },
  branding: {
    title: "الهوية البصرية",
    description: "اسم وشعار وألوان واجهتك وشاشة تسجيل الدخول والرسائل الإلكترونية.",
    standardOnly: "الباقة القياسية: تعتمد الواجهة ألوان المنصة. تُفعَّل العلامة البيضاء عند الطلب.",
    identity: "الهوية",
    brandName: "اسم العلامة",
    brandNameHint: "يظهر في علامة تبويب المتصفح وشاشة تسجيل الدخول والرسائل الإلكترونية.",
    images: "الصور",
    logo: "الشعار",
    logoHint: "PNG أو SVG أو WebP، ويُفضَّل بخلفية شفافة، 2 ميغابايت كحد أقصى.",
    favicon: "أيقونة علامة التبويب (favicon)",
    faviconHint: "مربعة، PNG أو ICO، ويُنصح بمقاس 64 × 64 px.",
    loginBackground: "خلفية شاشة تسجيل الدخول",
    loginBackgroundHint: "صورة أفقية، ويُنصح بمقاس 1920 × 1080 px.",
    choose: "اختيار صورة",
    replace: "استبدال",
    remove: "إزالة",
    uploading: "جارٍ الرفع…",
    uploadFailed: "تعذّر رفع الصورة (صيغة PNG أو JPEG أو WebP أو SVG أو ICO، 2 ميغابايت كحد أقصى).",
    colors: "الألوان",
    primary: "اللون الرئيسي",
    primaryHint: "الشريط الجانبي، الأزرار، الروابط، التركيز.",
    secondary: "اللون الثانوي",
    secondaryHint: "التدرجات وخلفية التطبيق.",
    accent: "لون التمييز",
    accentHint: "العناصر البارزة والمؤشرات.",
    colorInvalid: "لون بصيغة #RRGGBB.",
    preview: "معاينة",
    previewButton: "الزر الرئيسي",
    emails: "الرسائل الإلكترونية",
    senderName: "اسم المرسل",
    supportEmail: "عنوان الرد والدعم",
    supportPhone: "هاتف الدعم",
    domain: "نطاق مخصص",
    domainHint: (target: string) =>
      `ينشئ العميل سجل CNAME لنطاقه (مثلًا app.moncentre.ma) يشير إلى ${target}، ثم تتحقق منه.`,
    domainInvalid: "نطاق غير صالح (مثلًا app.moncentre.ma).",
    domainVerified: "تم التحقق من النطاق",
    domainPending: "في انتظار التحقق",
    verify: "التحقق من النطاق",
    verifying: "جارٍ التحقق…",
    verifiedOk: "تم التحقق من النطاق: إنه يشير فعلًا إلى المنصة.",
    verifiedKo: (target: string) => `النطاق لا يشير بعد إلى ${target} (قد يستغرق انتشار DNS بضع ساعات).`,
    noTarget: "هدف DNS غير مُعَدّ: حدّد PLATFORM_CNAME_TARGET أو ROOT_DOMAIN.",
    save: "حفظ الهوية البصرية",
    saving: "جارٍ الحفظ…",
    saved: "تم حفظ الهوية البصرية",
    edit: "تعديل الهوية البصرية",
    optional: "اختياري",
  },
};
