import type { AppLabels } from "@/lib/constants/labels";

/** Accord du nom avec le nombre en arabe : 1, 2, 3 à 10, 11 et plus. */
const plural = (n: number, one: string, two: string, few: string, many: string): string =>
  n === 1 ? one : n === 2 ? two : n >= 3 && n <= 10 ? few : many;

/** Libellés arabes : app, common, theme, currency, status, notifications, studentAccess, studentLogin, resources, studentSpace, attendanceMarkers, sessions, attendanceConflicts, attendanceSheet. */
export const AR_PART1: Pick<
  AppLabels,
  | "app"
  | "common"
  | "theme"
  | "currency"
  | "status"
  | "notifications"
  | "studentAccess"
  | "studentLogin"
  | "resources"
  | "studentSpace"
  | "attendanceMarkers"
  | "sessions"
  | "attendanceConflicts"
  | "attendanceSheet"
> = {
  app: {
    name: "dirassty",
    tagline: "سيّر مركزك ببساطة.",
    poweredBy: "بدعم من dirassty",
    metaDescription: "الاشتراكات والأداءات والحضور في مركزك للغات أو للدعم المدرسي.",
  },
  common: {
    loading: "جارٍ التحميل…",
    retry: "إعادة المحاولة",
    cancel: "إلغاء",
    confirm: "تأكيد",
    save: "حفظ",
    search: "بحث",
    back: "رجوع",
    close: "إغلاق",
    more: "المزيد",
    openMenu: "فتح القائمة",
    skipToContent: "الانتقال إلى المحتوى الرئيسي",
    signOut: "تسجيل الخروج",
    language: "اللغة",
    colon: ":",
    seeAll: "عرض الكل",
    show: "عرض",
    none: "—",
  },
  theme: {
    toggleToDark: "التبديل إلى الوضع الداكن",
    toggleToLight: "التبديل إلى الوضع الفاتح",
  },
  currency: {
    code: "MAD",
  },
  status: {
    upToDate: "منتظم",
    overdue: "متأخر",
    pending: "قيد الانتظار",
    paid: "مؤدى",
    present: "حاضر",
    absent: "غائب",
    absence: "غياب",
    followUp: "متابعة مطلوبة",
    followedUp: "تمت المتابعة",
  },
  notifications: {
    title: "الإشعارات",
    open: (count: number) => (count === 0 ? "الإشعارات" : `الإشعارات — الجديدة: ${count}`),
    description: "التذكيرات والملاحظات خلال آخر 14 يومًا، والتنبيهات التي تنتظر المعالجة.",
    empty: "لا توجد إشعارات حاليًا.",
    kinds: {
      followUp: "تذكير",
      note: "ملاحظة في الملف",
      absenceAlert: "تنبيه غياب",
      cashVariance: "فارق الصندوق",
      attendanceConflict: "تعارض في الحضور",
    },
    by: (name: string) => `من طرف ${name}`,
    priority: "أولوية",
  },
  studentAccess: {
    title: "ولوج {the learner}",
    description: "يلج {the learner} إلى فضائه (المنصة التعليمية) برمز يمنحه إياه المركز. لا تُطلب منه أي بيانات شخصية.",
    none: "لا يوجد ولوج بعد.",
    active: "الولوج مفعّل",
    inactive: "الولوج معطّل",
    code: "رمز الدخول",
    openedOn: (date: string) => `فُتح في ${date}`,
    disabledOn: (date: string) => `عُطّل في ${date}`,
    open: "فتح الولوج",
    disable: "تعطيل الولوج",
    enable: "إعادة تفعيل الولوج",
    disableTitle: "تعطيل ولوج {the learner}؟",
    disableDescription: "لن يتمكن {the learner} من تسجيل الدخول بعد الآن. لن يُحذف أي شيء: يمكن إعادة تفعيل الولوج.",
    opened: "تم فتح الولوج.",
    disabled: "تم تعطيل الولوج.",
    enabled: "تمت إعادة تفعيل الولوج.",
    failed: "تعذّر إنشاء الولوج. أعد المحاولة.",
    newStudentOption: "فتح ولوج {the learner}",
    newStudentHint: "سيلج {the learner} إلى فضائه برمز وكلمة مرور تُعرضان مرة واحدة فقط بعد التسجيل.",
    credentials: {
      title: "بيانات دخول {the learner}",
      description: "دوّنها أو أرسلها إلى ولي الأمر: لن تُعرض كلمة المرور مرة أخرى.",
      url: "عنوان الدخول",
      code: "الرمز",
      password: "كلمة المرور",
      copy: "نسخ",
      copied: "تم النسخ.",
      whatsapp: "إرسال إلى ولي الأمر",
      done: "تم التدوين",
      message: (name: string, url: string, code: string, password: string) =>
        `Bonjour, voici l'accès de ${name} à son espace : ${url} — code ${code}, mot de passe temporaire ${password}. Un mot de passe personnel sera demandé à la première connexion.`,
    },
  },
  studentLogin: {
    title: "فضاء {the learner}",
    description: "سجّل الدخول بالرمز وكلمة المرور اللذين منحك إياهما مركزك.",
    code: "الرمز",
    codePlaceholder: "مثال: 7K4Q 2MXP",
    password: "كلمة المرور",
    submit: "تسجيل الدخول",
    submitting: "جارٍ تسجيل الدخول…",
    invalid: "الرمز أو كلمة المرور غير صحيحة.",
    codeRequired: "أدخل رمزك (8 أحرف).",
    passwordRequired: "أدخل كلمة المرور.",
    disabled: "ولوجك معطّل. تواصل مع مركزك.",
    rateLimited: "محاولات كثيرة جدًا. انتظر دقيقة، ثم أعد المحاولة.",
    unavailable: "تعذّر تسجيل الدخول حاليًا. تحقّق من اتصالك بالإنترنت، ثم أعد المحاولة.",
    staffLink: "هل أنت من فريق العمل؟ دخول الفريق",
    studentLink: "هل أنت {learner}؟ دخول {the learners}",
  },
  resources: {
    title: "مواردي",
    description:
      "تمارين وامتحانات وملخصات دروس خاصة ب{the courses} التي تدرّسها. يظهر المورد المنشور في فضاء {the learners} المسجَّلين في {the course} و{the group}.",
    new: "نشر مورد",
    newTitle: "مورد جديد",
    editTitle: "تعديل المورد",
    back: "مواردي",
    types: { exercise: "تمرين", exam: "امتحان", summary: "ملخص درس", other: "أخرى" },
    filterSubject: "تصفية حسب {the course}",
    allSubjects: "جميع {the courses}",
    emptyTitle: "لا توجد موارد",
    emptyDescription: "انشر أول تمرين أو موضوع امتحان أو ملخص درس.",
    noAssignmentsTitle: "لا توجد {courses}",
    noAssignmentsDescription: "لم تُسند إليك الإدارة أي {course} بعد.",
    published: "منشور",
    draft: "مسودة",
    publishedOn: (date: string) => `نُشر في ${date}`,
    updatedOn: (date: string) => `عُدّل في ${date}`,
    dueOn: (date: string) => `آخر أجل للتسليم: ${date}`,
    open: "فتح الملف",
    edit: "تعديل",
    publish: "نشر",
    unpublish: "إلغاء النشر",
    delete: "حذف",
    deleteTitle: "حذف المورد؟",
    deleteDescription: "سيُحذف المورد وملفه نهائيًا؛ ولن يراه {the learners} بعد الآن.",
    deleted: "تم حذف المورد.",
    publishedToast: "تم نشر المورد.",
    unpublishedToast: "تم إلغاء نشر المورد: لم يعد {the learners} يرونه.",
    saved: "تم حفظ المورد.",
    fields: {
      type: "النوع",
      subject: "{the course} و{the group}",
      subjectPlaceholder: "اختر {course}",
      title: "العنوان",
      titlePlaceholder: "مثال: السلسلة 3 — الدوال المشتقة",
      description: "الوصف",
      descriptionHint: "التعليمات، الفصل المعني… (اختياري)",
      file: "الملف",
      fileHint: "PDF أو صورة (JPEG، PNG، WebP)، 8 ميغابايت كحد أقصى.",
      currentFile: (name: string) => `الملف الحالي: ${name}`,
      replaceFile: "استبدال الملف (اختياري)",
      dueDate: "آخر أجل للتسليم (اختياري)",
      dueDateHint: "لتمرين أو امتحان يجب تسليمه.",
      publishNow: "النشر الآن",
      publishNowHint: "وإلا يبقى المورد مسودة: لا يراه أحد غيرك.",
    },
    submit: "حفظ",
    submitting: "جارٍ الحفظ…",
    validation: {
      titleRequired: "أدخل عنوانًا.",
      titleTooLong: "150 حرفًا كحد أقصى.",
      descriptionTooLong: "2000 حرف كحد أقصى.",
      subjectRequired: "اختر {course}.",
      fileRequired: "أضف ملفًا (PDF أو صورة).",
      fileTooLarge: "الملف كبير جدًا: 8 ميغابايت كحد أقصى.",
      fileInvalid: "صيغة غير مقبولة: PDF أو JPEG أو PNG أو WebP فقط.",
      dueDateInvalid: "تاريخ غير صالح.",
    },
    errors: {
      upload: "تعذّر رفع الملف. أعد المحاولة.",
    },
  },
  studentSpace: {
    title: "فضائي",
    welcome: (name: string) => `مرحبًا ${name}`,
    description: (center: string, level: string) => `${center} · ${level}`,
    comingSoonTitle: "لا توجد موارد حاليًا",
    comingSoon: "ستظهر هنا تمارينك وامتحاناتك وملخصات دروسك فور نشرها من طرف {the instructors}.",
    newCount: (count: number) => `جديد: ${count}`,
    dueCount: (count: number) => `مواعيد تسليم قادمة: ${count}`,
    dueSoonTitle: "للتسليم قريبًا",
    resourcesTitle: "مواردي",
    filterSubject: "تصفية حسب {the course}",
    allSubjects: "جميع {the courses}",
    typeGroups: { exercise: "تمارين", exam: "امتحانات", summary: "ملخصات الدروس", other: "وثائق أخرى" },
    new: "جديد",
    open: "فتح",
    download: "تحميل",
    by: (name: string) => `من طرف ${name}`,
    publishedOn: (date: string) => `نُشر في ${date}`,
    dueIn: (days: number) =>
      days < 0
        ? "انتهى أجل التسليم"
        : days === 0
          ? "للتسليم اليوم"
          : days === 1
            ? "للتسليم غدًا"
            : days === 2
              ? "للتسليم بعد يومين"
              : `للتسليم بعد ${days} ${plural(days, "يوم", "يومين", "أيام", "يومًا")}`,
    dueOn: (date: string) => `في ${date}`,
    emptySubjectTitle: "لا يوجد شيء ضمن {the course}",
    emptySubjectDescription: "لم يُنشر أي مورد ضمن {the course} حتى الآن.",
    signOut: "تسجيل الخروج",
  },
  /** À quel titre une présence a été saisie. */
  attendanceMarkers: { teacher: "{the instructor}", assistant: "الاستقبال", admin: "الإدارة" },
  sessions: {
    title: "{sessions} اليوم",
    description: "جميع {the sessions} في الوقت الفعلي. افتح {session} لتسجيل الحضور بدلًا من {the instructor} إذا تعذّر عليه ذلك.",
    dayLabel: (date: string) => `{sessions} يوم ${date}`,
    today: "اليوم",
    previousDay: "اليوم السابق",
    nextDay: "اليوم التالي",
    rangeHint: "يمكن تسجيل الحضور أو تصحيحه خلال 7 أيام بعد {the session}.",
    emptyTitle: "لا توجد {sessions} في هذا اليوم",
    emptyDescription: "لا يتضمن التخطيط أي {session} في هذا اليوم من الأسبوع.",
    state: { upcoming: "قريبًا", ongoing: "قيد الانعقاد", done: "تم الانتهاء" },
    progress: (marked: number, total: number) => `المسجَّلون: ${marked} / ${total}`,
    notMarked: "لم يُسجَّل الحضور",
    absents: (count: number) => `الغائبون: ${count}`,
    byTeacher: "سجّله {the instructor}",
    byStaff: "سجّله الاستقبال",
    byBoth: "{the instructor} والاستقبال",
    conflicts: (count: number) => `إدخالات متعارضة: ${count}`,
    take: "تسجيل الحضور",
    edit: "تصحيح الحضور",
    lastMarked: (time: string) => `آخر إدخال على الساعة ${time}`,
    roster: {
      back: "{sessions} اليوم",
      description: "حدّد حالة كل {learner}: حاضر أو غائب. ترى الإدارة من سجّل الحضور ومتى.",
      allPresent: "الجميع حاضرون",
      present: "حاضر",
      absent: "غائب",
      notMarked: "غير مسجَّل",
      markedBy: (role: string, name: string, time: string) => `${role} · ${name} · ${time}`,
      save: "حفظ الحضور",
      saving: "جارٍ الحفظ…",
      saved: (count: number) => `تم حفظ سجلات الحضور: ${count}.`,
      nothingToSave: "حدّد حالة {learner} واحد على الأقل.",
      unmarked: (count: number) => `{learners} بدون حالة: ${count}`,
      emptyTitle: "لم يُسجَّل أي {learner}",
      emptyDescription: "لا أحد مسجَّل في {the session} بهذا التاريخ.",
      notFoundTitle: "تعذّر العثور على {the session}",
      notFoundDescription: "لا أثر ل{the session} في ذلك اليوم، أو أن التاريخ خارج الأيام السبعة الأخيرة.",
      teacherOf: (name: string) => `{the instructor}: ${name}`,
    },
  },
  attendanceConflicts: {
    title: "تعارضات الحضور",
    description: "أدخل {the instructor} والاستقبال حالات مختلفة. يُعرض الإدخال الأحدث؛ اختر الإدخال الذي سيُعتمد.",
    banner: (count: number) =>
      count <= 1
        ? "يوجد تسجيل حضور متعارض بين {the instructor} والاستقبال."
        : `عدد تسجيلات الحضور المتعارضة بين {the instructor} والاستقبال: ${count}.`,
    review: "مراجعة التعارضات",
    session: (subject: string, date: string) => `${subject} · ${date}`,
    entry: (role: string, name: string, status: string, time: string) => `${role} (${name}): ${status}، ${time}`,
    displayed: (status: string) => `المعروض: ${status}`,
    keep: (status: string) => `اعتماد «${status}»`,
    resolved: "تم اعتماد الحالة.",
    notification: (subject: string, date: string) => `${subject}، {the session} بتاريخ ${date}`,
  },
  attendanceSheet: {
    title: "المواظبة",
    description: "حضور وغيابات {the learner} حسب {the course}.",
    filtersLabel: "عوامل تصفية المواظبة",
    period: "الفترة",
    periods: { month: "هذا الشهر", quarter: "هذا الفصل", all: "السجل الكامل" },
    subject: "{the course}",
    allSubjects: "جميع {the courses}",
    totalAbsences: "الغيابات",
    sessions: "{the sessions} المسجَّلة",
    rate: "نسبة الحضور",
    noRate: "—",
    bySubject: "حسب {the course}",
    absencesCount: (count: number) => `الغيابات: ${count}`,
    markedBy: (role: string, name: string, time: string) => `سجّله ${name} (${role})، ${time}`,
    history: "الإدخالات المتتالية",
    historyItem: (role: string, name: string, status: string, time: string) => `${role} (${name}): ${status}، ${time}`,
    sessionsCount: (count: number) => `عدد {the sessions}: ${count}`,
    streaksTitle: "الغيابات المتتالية",
    streak: (length: number, subject: string) =>
      `${length} ${plural(length, "غياب متتالٍ", "غيابان متتاليان", "غيابات متتالية", "غيابًا متتاليًا")} في ${subject}`,
    streakRange: (from: string, to: string) => `من ${from} إلى ${to}`,
    streakOngoing: "سلسلة جارية",
    streaksEmpty: "لا توجد سلسلة غيابات متتالية خلال هذه الفترة.",
    alertTriggered: "تم إطلاق التنبيه",
    alertHint: "يُنشأ تنبيه عند الغياب الثالث على التوالي في نفس {the course}.",
    listTitle: "{the sessions} الفائتة",
    listCaption: "{the sessions} الفائتة، من الأحدث إلى الأقدم",
    date: "التاريخ",
    time: "التوقيت",
    teacher: "{the instructor}",
    note: "السبب أو ملاحظة",
    noNote: "بدون سبب",
    noTime: "توقيت غير مبرمج",
    position: (position: number, length: number) => `${position} من أصل ${length} على التوالي`,
    emptyTitle: "لا توجد غيابات",
    emptyDescription: "لا توجد {sessions} فائتة خلال هذه الفترة.",
    noSessionsTitle: "لا توجد {sessions} مسجَّلة",
    noSessionsDescription: "سيظهر الحضور بعد تسجيله لأول مرة.",
    followUpsTitle: "تذكيرات الغياب",
    followUpsEmpty: "لم يُرسل أي تذكير غياب إلى ولي الأمر.",
    followUpBy: (name: string) => `من طرف ${name}`,
    editNote: "السبب",
    editNoteLabel: (date: string) => `سبب الغياب بتاريخ ${date}`,
    notePlaceholder: "مثال: مريض، تم استلام شهادة طبية",
    noteSaved: "تم حفظ السبب",
    noteTooLong: "300 حرف كحد أقصى.",
    exportPdf: "تصدير بصيغة PDF",
    pdfTitle: "بطاقة المواظبة",
    pdfStudent: "{the learner}",
    pdfLevel: "{the group}",
    pdfGuardian: "ولي الأمر",
    pdfPeriod: "الفترة",
    pdfGeneratedOn: (date: string) => `حُرّر في ${date}`,
    pdfPage: (page: number, total: number) => `الصفحة ${page} / ${total}`,
    viewAttendance: "عرض المواظبة",
    teacherScope: "لا ترى إلا غيابات {the courses} التي تدرّسها.",
  },
};
