import type { AppLabels } from "@/lib/constants/labels";

/** 15 → « 15:00–16:00 ». */
function hourRange(hour: number): string {
  return `${hour}:00–${hour + 1}:00`;
}

const plural = (n: number, one: string, two: string, few: string, many: string) =>
  n === 1 ? one : n === 2 ? two : n >= 3 && n <= 10 ? few : many;

/** Libellés arabes : cash, absenceAlerts, roomOccupancy, financeDashboard, centerSettings, followUp. */
export const AR_PART7: Pick<AppLabels, "cash" | "absenceAlerts" | "roomOccupancy" | "financeDashboard" | "centerSettings" | "followUp"> = {
  cash: {
    description: "مداخيل اليوم حسب طريقة الأداء، والنقد المتوقع في الدرج، ثم العدّ والإغلاق.",
    shared: "الصندوق المشترك للمركز",
    personal: (name: string | null) => (name ? `صندوق ${name}` : "صندوق شخصي"),
    closedTitle: "الصندوق مغلق",
    closedDescription: "يُفتح الصندوق عند أول عملية تحصيل في اليوم. يمكنكم أيضًا فتحه الآن بالرصيد الافتتاحي.",
    openingFloat: "الرصيد الافتتاحي",
    openingFloatHint: "الصرف الموجود في الدرج في بداية اليوم؛ 0 إذا كان المركز لا يستعمله.",
    open: "فتح الصندوق",
    opened: "تم فتح الصندوق",
    floatTitle: "الرصيد الافتتاحي في انتظار التأكيد",
    floatDescription: "لم تُسجَّل أي عملية تحصيل بعد: تحققوا من الصرف الموجود في الدرج. بعد أول عملية تحصيل، يصبح الرصيد ثابتًا.",
    floatSave: "حفظ الرصيد",
    floatSaved: "تم حفظ الرصيد الافتتاحي",
    floatLocked: (amount: string) =>
      `سبق تسجيل عملية تحصيل: يبقى الرصيد الافتتاحي ${amount}. لتعديله، سجّلوا حركة «تعديل الرصيد».`,
    amountInvalid: "أدخلوا مبلغًا موجبًا، بدقة السنتيم (مثال: 250 أو 250,50).",
    sessionOf: (date: string) => `صندوق يوم ${date}`,
    openedAt: (time: string, name: string | null, amount: string) =>
      `فُتح على الساعة ${time}${name ? ` من طرف ${name}` : ""} · الرصيد ${amount}`,
    closedAt: (date: string, name: string | null) => `أُغلق يوم ${date}${name ? ` من طرف ${name}` : ""}`,
    status: { open: "مفتوح", closed: "مغلق", validated: "مصادق عليه" },
    staleTitle: "صندوق آخر لا يزال مفتوحًا",
    staleDescription: "قوموا بعدّه وإغلاقه: المداخيل الجديدة تُسجَّل في صندوق اليوم.",
    methods: { cash: "نقدًا", bank_transfer: "تحويل بنكي", card: "بطاقة", cheque: "شيك" },
    total: "مجموع المبلغ المحصّل",
    transactions: (count: number) => `عدد العمليات: ${count}`,
    listTitle: "المداخيل",
    listEmpty: "لا توجد أي عملية تحصيل في هذه الجلسة.",
    cancellation: "إلغاء",
    receipt: (number: string) => `الوصل ${number}`,
    movementsTitle: "حركات النقد",
    movementsEmpty: "لا توجد أي حركة.",
    movementKinds: {
      refund: "استرجاع",
      expense: "مصروف مؤدى نقدًا",
      teacher_pay: "أجور مؤداة نقدًا",
      bank_deposit: "إيداع بنكي",
      float_change: "تعديل الرصيد",
      correction: "تصحيح",
    },
    hiddenReason: "التفاصيل متاحة للمدير فقط",
    correctsSession: (date: string) => `يصحح صندوق يوم ${date}`,
    correctionsTitle: "التصحيحات بعد الإغلاق",
    correctionLine: (date: string, name: string | null) => `يوم ${date}${name ? ` من طرف ${name}` : ""}`,
    afterCorrections: "بعد التصحيحات",
    validationNotes: "ملاحظة المصادقة",
    addMovement: "حركة نقدية",
    movementTitle: "حركة نقدية",
    movementDescription: "خروج أو دخول نقد خارج عمليات التحصيل: تُحتسب ضمن النقد المتوقع.",
    movementKind: "النوع",
    movementAmount: "المبلغ",
    movementDirection: { in: "إضافة إلى الدرج", out: "سحب من الدرج" },
    movementReason: "السبب",
    movementReasonRequired: "أدخلوا سبب الحركة.",
    movementReasonPlaceholder: "مثال: إيداع في البنك، استرجاع لفائدة Salma Bennani",
    movementSave: "حفظ الحركة",
    movementSaved: "تم حفظ الحركة",
    expected: {
      title: "النقد المتوقع",
      formula: (float: string, cash: string, movements: string) =>
        `الرصيد ${float} + النقد المحصّل ${cash} ${movements.startsWith("-") ? "−" : "+"} الحركات ${movements.replace(/^-/, "")}`,
      note: "تُطابَق التحويلات والبطاقات والشيكات بشكل منفصل: لا تدخل في حساب الفارق.",
    },
    counted: "المبلغ المعدود",
    countedHint: "النقد الموجود فعليًا في الدرج.",
    variance: {
      none: "الصندوق مضبوط",
      shortage: (amount: string) => `نقص: ${amount}`,
      surplus: (amount: string) => `فائض: ${amount}`,
    },
    varianceReason: "سبب الفارق",
    varianceReasonPlaceholder: "مثال: خطأ في إرجاع الصرف",
    varianceReasonRequired: "أدخلوا سبب الفارق قبل الإغلاق.",
    notes: "ملاحظات (اختياري)",
    close: "إغلاق الصندوق",
    closeConfirmTitle: "إغلاق الصندوق؟",
    closeConfirmDescription: "بعد الإغلاق، لا يمكن تغيير الجلسة: أي تصحيح سيتم عبر عملية بتاريخ اليوم.",
    closeConfirm: "إغلاق",
    closedToast: "تم إغلاق الصندوق",
    countedCash: "المعدود",
    supportReadOnly: "وضع الدعم: لا يمكن الاطلاع على الصندوق.",
    settings: {
      title: "الصندوق",
      description: "إغلاق الصندوق اليومي: جلسة مشتركة، أو جلسة لكل شخص في الاستقبال.",
      perAssistant: "صندوق لكل شخص في الاستقبال",
      perAssistantHint:
        "ضروري ابتداءً من وجود شخصين في الاستقبال: يُنسب كل فارق إلى شخص محدد. الصناديق المفتوحة حاليًا يجب إغلاقها؛ والصناديق التالية تتبع هذا الإعداد.",
      threshold: "عتبة التنبيه (الفارق)",
      thresholdHint: (amount: string) => `أي فارق يتجاوز ${amount} (نقصًا أو فائضًا) يُنبّه المدير.`,
      thresholdInvalid: "أدخلوا مبلغًا موجبًا، بدقة السنتيم.",
    },
    notification: (amount: string, date: string) => `فارق في الصندوق قدره ${amount} يوم ${date}`,
    admin: {
      historyTitle: "سجل الجلسات",
      historyDescription: "جلسات الشهر: المحصّل، المتوقع، المعدود، الفارق والسبب. الجلسة المصادق عليها تُقفل نهائيًا.",
      monthsLabel: "الشهر",
      month: (month: string) => month,
      empty: "لا توجد أي جلسة صندوق هذا الشهر.",
      indicators: {
        shortage: "النقص خلال الشهر",
        surplus: "الفائض خلال الشهر",
        net: (amount: string) => `صافي الفوارق: ${amount}`,
        exact: "جلسات بدون فارق",
        exactHint: (exact: number, total: number) => `${exact} من أصل ${total} من الجلسات المغلقة`,
        collected: "المحصّل في الصناديق",
        validated: (count: number) => `المصادق عليها: ${count}`,
      },
      peopleTitle: "الفوارق حسب الشخص",
      peopleDescription: "الفارق المنفرد خطأ بشري؛ أما الفوارق المتكررة في الاتجاه نفسه فهي مؤشر يجب معالجته.",
      personLine: (sessions: number, short: number, surplus: number) =>
        `الجلسات: ${sessions} · حالات النقص: ${short} · حالات الفائض: ${surplus}`,
      repeated: "فوارق متكررة في الاتجاه نفسه",
      unknownPerson: "حساب محذوف",
      columns: {
        date: "التاريخ",
        holder: "الصندوق",
        collected: "المحصّل",
        expected: "المتوقع",
        counted: "المعدود",
        variance: "الفارق",
        status: "الحالة",
      },
      corrections: (amount: string) => `التصحيحات: ${amount}`,
      open: "التفاصيل",
      report: "تقرير PDF",
      backToCash: "الرجوع إلى الصندوق",
      detailTitle: (date: string) => `جلسة يوم ${date}`,
      validate: {
        button: "مصادقة",
        title: "المصادقة على الجلسة؟",
        description: "بعد المصادقة، تُقفل الجلسة نهائيًا: لا يمكن ربط أي تصحيح بها بعد ذلك.",
        notes: "ملاحظة المصادقة (اختياري)",
        action: "المصادقة على الجلسة",
        done: "تمت المصادقة على الجلسة",
      },
      correct: {
        button: "تصحيح",
        title: "تصحيح الصندوق",
        description:
          "عملية بتاريخ اليوم، في صندوقكم لهذا اليوم، مرتبطة بهذه الجلسة. مبلغ موجب: يعود المال إلى الدرج؛ مبلغ سالب: يخرج منه.",
        direction: { in: "مال تم العثور عليه (دخول)", out: "مال ناقص (خروج)" },
        amount: "المبلغ",
        reason: "السبب",
        reasonPlaceholder: "مثال: ورقة نقدية وُجدت تحت الدرج",
        already: (amount: string) => `تم تصحيحه مسبقًا لهذه الجلسة: ${amount}.`,
        action: "حفظ التصحيح",
        done: "تم حفظ التصحيح",
      },
      staleAlert: (date: string, holder: string) => `لم يتم إغلاق صندوق يوم ${date} (${holder}).`,
      staleAction: "فتح الصندوق",
      pdf: {
        title: (date: string) => `تقرير الصندوق ليوم ${date}`,
        session: (holder: string, status: string) => `${holder} · ${status}`,
        opened: (time: string, name: string | null) => `فُتح على الساعة ${time}${name ? ` من طرف ${name}` : ""}`,
        closed: (time: string, name: string | null) => `أُغلق على الساعة ${time}${name ? ` من طرف ${name}` : ""}`,
        notClosed: "غير مغلق",
        float: "الرصيد الافتتاحي",
        expectedCash: "النقد المتوقع",
        counted: "المعدود",
        variance: "الفارق",
        reason: "السبب",
        receipts: "المداخيل",
        time: "الساعة",
        student: "{the learner}",
        receipt: "الوصل",
        method: "طريقة الأداء",
        amount: "المبلغ",
        movements: "حركات النقد",
        corrections: "التصحيحات بعد الإغلاق",
        validationNotes: "ملاحظة المصادقة",
        noReceipts: "لا توجد أي عملية تحصيل.",
        dayTotal: "مجموع المحصّل خلال اليوم",
        signature: "التوقيع",
        generatedAt: (date: string) => `صدر بتاريخ ${date}`,
        empty: "لا توجد أي جلسة صندوق في ذلك اليوم.",
      },
    },
  },
  absenceAlerts: {
    title: "غيابات يجب الإبلاغ عنها",
    description: "أخبروا ولي الأمر في اليوم نفسه: الرسالة محررة مسبقًا، يكفي إرسالها.",
    emptyTitle: "لا توجد غيابات للإبلاغ عنها",
    emptyDescription: "ستظهر هنا الغيابات التي يسجلها {the instructors}.",
    disabled: "تنبيهات الغياب معطلة في إعدادات المركز.",
    notifyAll: (count: number) => `إخبار الجميع (${count})`,
    notify: "إخبار ولي الأمر",
    notifyAgain: "تذكير",
    recordCall: "تم الاتصال",
    recordInPerson: "تم اللقاء حضوريًا",
    otherChannel: "وسيلة أخرى",
    notifiedVia: (channel: string, date: string, by: string | null) =>
      by ? `تم الإخبار ${channel} يوم ${date} من طرف ${by}` : `تم الإخبار ${channel} يوم ${date}`,
    notNotified: "لم يتم إخبار ولي الأمر بعد",
    channels: { whatsapp: "عبر WhatsApp", phone_call: "عبر الهاتف", in_person: "حضوريًا" },
    channelNames: { whatsapp: "WhatsApp", phone_call: "الهاتف", in_person: "حضوريًا" },
    series: "سلسلة غيابات",
    seriesHint: "عدة غيابات متتالية: الرسالة تشير إلى السلسلة.",
    session: (date: string, time: string | null) => (time ? `${date} · ${time}` : date),
    guardian: (name: string | null, phone: string | null) => [name, phone].filter(Boolean).join(" · ") || "لم يتم إدخال ولي الأمر",
    noPhone: "لا يوجد رقم: أدخلوه لإرسال الرسالة.",
    recorded: "تم تسجيل الإخبار",
    alreadyNotified: "سبق إخبار ولي الأمر بهذا الغياب. استعملوا «تذكير».",
    sequence: {
      title: "إخبار أولياء الأمور",
      progress: (index: number, total: number) => `الغياب ${index} من ${total}`,
      preview: "الرسالة",
      open: "فتح WhatsApp",
      skip: "تخطي",
      done: "تمت معالجة جميع الغيابات.",
      close: "إنهاء",
    },
    tokens: {
      student: "[élève]",
      date: "[date]",
      day: "[jour]",
      subject: "[matière]",
      time: "[heure]",
      teacher: "[professeur]",
      center: "[centre]",
    },
    template:
      "Bonjour, nous vous informons que [élève] était absent(e) au cours de [matière] du [date] à [heure]. Merci de nous contacter si nécessaire.\n[centre]",
    seriesTemplate:
      "Bonjour, nous vous informons que [élève] a manqué plusieurs séances consécutives de [matière], la dernière le [date] à [heure]. Merci de nous contacter rapidement.\n[centre]",
    noTime: "وقت الحصة",
    settings: {
      title: "تنبيهات الغياب",
      description: "رسالة تُرسَل إلى ولي الأمر عبر WhatsApp عند غياب أحد {the learners}.",
      enabled: "اقتراح إخبار أولياء الأمور",
      enabledHint: "يعرض قسم «غيابات يجب الإبلاغ عنها» في لوحة القيادة الخاصة بالاستقبال.",
      template: "رسالة الغياب",
      templateHint: "متغيرات تُستبدل عند الإرسال:",
      reset: "الرجوع إلى الرسالة المقترحة",
      preview: "معاينة",
      sample: { student: "Salma Bennani", date: "mardi 14 octobre", day: "mardi", subject: "Mathématiques", time: "17:00", teacher: "M. Alami" },
    },
  },
  roomOccupancy: {
    title: "إشغال القاعات",
    description: "نسبة ساعات العمل التي تُستعمل فيها كل قاعة. ساعات العمل: من أول حصة إلى آخر حصة في كل يوم.",
    overall: "نسبة الإشغال",
    overallHint: "جميع القاعات مجتمعة، على مدى الأسبوع.",
    peak: "ساعة الذروة",
    peakValue: (day: string, hour: number) => `${day} ${hourRange(hour)}`,
    peakDetail: (rooms: number, total: number) => `القاعات المشغولة: ${rooms} من ${total}`,
    noPeak: "لا توجد حصص",
    fullHours: "الساعات الممتلئة",
    fullHoursValue: (count: number) =>
      count === 0 ? "لا شيء" : count === 1 ? "ساعة واحدة" : count === 2 ? "ساعتان" : `${count} ${plural(count, "ساعة", "ساعتان", "ساعات", "ساعة")}`,
    fullHoursHint: (count: number) =>
      count === 0
        ? "تبقى دائمًا قاعة واحدة على الأقل شاغرة."
        : "جميع القاعات مشغولة: قاعة إضافية ستسمح بفتح مجموعات جديدة في هذه الساعات.",
    roomsTitle: "حسب القاعة",
    heatmapTitle: "حسب اليوم والساعة",
    heatmapCaption: "نسبة القاعات المشغولة، بالنسبة المئوية.",
    used: (hours: string, open: string) => `${hours} س من الحصص من أصل ${open} س من ساعات العمل`,
    fill: (percent: string) => `نسبة الملء ${percent}`,
    fillHint: "عدد المسجلين مقارنة بعدد المقاعد خلال حصص القاعة.",
    capacityUnknown: "السعة غير محددة",
    status: { saturated: "مشبعة", balanced: "متوازنة", underused: "ضعيفة الاستعمال" },
    advice: {
      saturated: "مشغولة تقريبًا طوال الوقت: وزّعوا الحصص أو افتحوا قاعة أخرى.",
      overloaded: (count: number) => `عدد الحصص التي تتجاوز سعة القاعة: ${count}.`,
      underused: (hours: string) => `شاغرة ${hours} س في الأسبوع خلال ساعات العمل: ما يكفي لفتح مجموعة.`,
      balanced: "استعمال جيد.",
    },
    legend: "مفتاح الألوان",
    legendSteps: ["شاغرة", "أقل من 25%", "من 25 إلى 50%", "من 50 إلى 75%", "من 75 إلى 99%", "ممتلئة"],
    closed: "خارج ساعات الحصص",
    closedCell: (day: string, hour: number) => `${day} ${hourRange(hour)}: خارج ساعات الحصص`,
    cell: (day: string, hour: number, percent: string, rooms: number, total: number) =>
      `${day} ${hourRange(hour)}: ${percent} · القاعات: ${rooms} من ${total}`,
    hour: "الساعة",
    hourLabel: (hour: number) => `${hour}:00`,
    emptyTitle: "لا توجد حصص مبرمجة",
    emptyDescription: "سيظهر إشغال القاعات بمجرد أن يتضمن التخطيط حصصًا.",
  },
  financeDashboard: {
    title: "نتيجة الشهر",
    scope: "المركز بأكمله، جميع {the groups} مجتمعة.",
    collected: "المداخيل المحصّلة",
    expected: "المداخيل المتوقعة",
    unpaid: (amount: string) => `الفارق (المبالغ غير المؤداة): ${amount}`,
    payroll: "كتلة الأجور",
    payrollHint: "الأجور الثابتة والعمولات",
    expenses: "مصاريف الشهر",
    net: "الدخل الصافي",
    netFormula: "المحصّل − كتلة الأجور − المصاريف",
    positive: "ربح",
    negative: "خسارة",
    margin: "الهامش الصافي",
    marginHint: "الدخل الصافي مقارنة بالمداخيل المحصّلة",
    marginNone: "لا توجد أي عملية تحصيل هذا الشهر بعد",
    details: { payroll: "عرض الأجور", expenses: "عرض المصاريف" },
    chart: {
      title: "الأشهر الاثنا عشر الأخيرة",
      description: "المحصّل، كتلة الأجور، المصاريف والدخل الصافي، شهرًا بشهر (MAD).",
      series: { collected: "المحصّل", payroll: "كتلة الأجور", expenses: "المصاريف", net: "الدخل الصافي" },
      showTable: "عرض الجدول",
      hideTable: "إخفاء الجدول",
      caption: "النتيجة الشهرية على مدى اثني عشر شهرًا",
      month: "الشهر",
      note: "كتلة أجور الأشهر الماضية: الأجور المسجلة في التطبيق.",
    },
    discounts: {
      title: "تخفيضات الشهر",
      description: "التخفيضات الممنوحة على فواتير الشهر: مداخيل ضائعة يجب تتبعها.",
      total: "مجموع التخفيضات",
      students: (count: number) => `عدد المستفيدين من {the learners}: ${count}`,
      empty: "لا توجد أي تخفيضات على فواتير هذا الشهر.",
      byReason: "حسب السبب",
    },
    collection: {
      title: "تحصيل الشهر",
      description: (month: string) =>
        `الفواتير التي تبدأ فترتها في ${month} (بما فيها الحملة): المتوقع، المحصّل إلى اليوم، المتبقي للتحصيل.`,
      expected: "التوقعات",
      expectedHint: (count: number) => `عدد الفواتير: ${count}`,
      collected: "المحصّل إلى اليوم",
      collectedHint: (paid: number, total: number) => `المؤداة: ${paid} من ${total}`,
      remaining: "المتبقي للتحصيل",
      rate: "نسبة التحصيل",
      rateNone: "لا توجد أي فاتورة هذا الشهر",
      comparison: (rate: string, previousRate: string) =>
        `في اليوم نفسه من الشهر الماضي، تم تحصيل ${previousRate} من المتوقع؛ وهذا الشهر، ${rate}.`,
      comparisonNone: "لا توجد فواتير في الشهر الماضي للمقارنة.",
      chart: {
        title: "منحنى التحصيل",
        description: "المحصّل التراكمي يومًا بيوم، مقارنة باليوم نفسه من الشهر السابق (MAD).",
        series: { current: "هذا الشهر", previous: "الشهر السابق" },
        expectedLine: "التوقعات",
        day: "اليوم",
        dayLabel: (day: number) => `اليوم ${day}`,
        showTable: "عرض الجدول",
        hideTable: "إخفاء الجدول",
        caption: "المحصّل التراكمي يومًا بيوم، هذا الشهر والشهر السابق",
      },
    },
  },
  centerSettings: {
    title: "إعدادات المركز",
    description: "معلومات الاتصال، وصولات الأداء، إعادة التسجيل التلقائية وتنبيهات الغياب.",
    contactTitle: "معلومات الاتصال",
    contactDescription: "تظهر في رأس الوصولات وأسفلها.",
    address: "العنوان",
    phone: "الهاتف",
    receiptsTitle: "الوصولات",
    format: "صيغة الطباعة",
    formats: {
      a5: "A5 (ورقة)",
      ticket_80mm: "تذكرة 80 مم (طابعة حرارية)",
    },
    formatHints: {
      a5: "نصف ورقة A4، عمودي.",
      ticket_80mm: "لفافة صندوق بعرض 80 مم.",
    },
    template: "رسالة WhatsApp",
    templateHint: "متغيرات تُستبدل عند الإرسال:",
    templateReset: "الرجوع إلى الرسالة المقترحة",
    preview: "معاينة",
    save: "حفظ",
    saved: "تم حفظ الإعدادات",
    addressTooLong: "200 حرف كحد أقصى.",
    phoneInvalid: "رقم غير صالح. مثال: 05 22 00 00 00.",
    templateTooLong: "1000 حرف كحد أقصى.",
    templateNeedsLink: "يجب أن تتضمن الرسالة [lien] ليتوصل ولي الأمر بالوصل.",
    sample: { student: "Salma Bennani", period: "Octobre 2026", amount: "450 MAD", number: "2026-0042", link: "https://…" },
  },
  followUp: {
    channels: { phone: "الهاتف", whatsapp: "WhatsApp", in_person: "حضوريًا" },
    types: { payment: "الأداء", absence: "الغياب" },
    dialog: {
      trigger: "تسجيل متابعة",
      triggerShort: "متابعة",
      title: "تسجيل متابعة",
      description: (name: string) => `متابعة ${name}.`,
      type: "السبب",
      channel: "القناة",
      note: "ملاحظة",
      notePlaceholder: "مثال: يَعِد ولي الأمر بالأداء يوم الجمعة.",
      submit: "حفظ",
      success: "تم تسجيل المتابعة",
    },
    validation: {
      noteTooLong: "يجب ألا تتجاوز الملاحظة 500 حرف.",
    },
  },
};
