import type { AppLabels } from "@/lib/constants/labels";

/** Libellés arabes : payroll, expenses, rooms. */
export const AR_PART5: Pick<AppLabels, "payroll" | "expenses" | "rooms"> = {
  payroll: {
    title: "أجور {the instructors}",
    description: "مبالغ تُحسب تلقائيًا كل شهر: أجر ثابت، أو عمولة على التعريفة الكاملة ل{the learners} المسجلين.",
    month: "الشهر",
    previousMonth: "الشهر السابق",
    nextMonth: "الشهر التالي",
    supportUnavailable: "لا يمكن الاطلاع على بيانات أجور المركز في وضع الدعم.",
    status: { draft: "مسودة", validated: "مُصادق عليها", paid: "مؤداة" },
    statusHints: {
      draft: "تتغير المبالغ مع التسجيلات إلى حين المصادقة.",
      validated: "المبالغ مثبتة. سجّل الدفعات تباعًا.",
      paid: "تم تسجيل جميع دفعات الشهر.",
    },
    validatedBy: (name: string, date: string) => `صادق عليها ${name} بتاريخ ${date}`,
    validatedOn: (date: string) => `تمت المصادقة بتاريخ ${date}`,
    columns: {
      teacher: "{the instructor}",
      mode: "نوع الأجر",
      computed: "المبلغ المحسوب",
      adjustment: "التسوية",
      final: "المبلغ النهائي",
      payment: "الدفع",
    },
    modes: { fixed_salary: "أجر ثابت", commission: "عمولة", none: "غير محدد" },
    total: "كتلة الأجور الشهرية",
    teachersCount: (count: number) => `{the instructors}: ${count}`,
    emptyTitle: "لا يوجد {instructors}",
    emptyDescription: "أنشئ حسابات {the instructors} وأسند إليهم {courses} لحساب الأجور.",
    showDetail: "عرض تفاصيل الحساب",
    hideDetail: "إخفاء التفاصيل",
    detail: {
      subject: "{the course}",
      level: "{the group}",
      price: "التعريفة الشهرية",
      enrolled: "المسجلون",
      rate: "النسبة",
      subtotal: "المجموع الجزئي",
      formula: (price: string, enrolled: number, rate: string, subtotal: string) =>
        `${price} × ${enrolled} × ${rate} = ${subtotal}`,
      noRate: "النسبة غير محددة",
      noSubjects: "لم تُسند أي {courses} إلى هذا {the instructor}.",
      fullPriceNote: "يتم الحساب على أساس التعريفة الكاملة وجميع {the learners} المسجلين، سواء أدّوا أم لا، مع احتساب التخفيضات.",
      salary: (amount: string, date: string) => `أجر شهري قدره ${amount}، ابتداءً من ${date}.`,
      noSalary: "لم يُحدد أي أجر لهذا الشهر.",
      notConfigured: "اختر طريقة احتساب أجر هذا {the instructor}.",
    },
    notPaid: "للأداء",
    notYet: "بعد المصادقة",
    paidOn: (date: string, method: string) => `تم الدفع بتاريخ ${date} · ${method}`,
    adjustment: {
      trigger: "تسوية",
      title: (name: string) => `تسوية — ${name}`,
      description: "منحة أو اقتطاع أو تسبيق سبق دفعه. لا يتغير المبلغ المحسوب: تُضاف إليه التسوية.",
      kind: "النوع",
      kinds: { bonus: "منحة (+)", deduction: "اقتطاع أو تسبيق (−)" },
      amount: "المبلغ (MAD)",
      reason: "السبب",
      reasonRequired: "أدخل سبب التسوية.",
      remove: "حذف التسوية",
      saved: "تم حفظ التسوية",
    },
    validate: {
      trigger: "المصادقة على الأجور",
      title: (month: string) => `المصادقة على أجور ${month}؟`,
      description: "ستُثبَّت المبالغ: أي تسجيل أو نسبة تُعدَّل لاحقًا لن تغيّرها. وستتمكن بعدها من تسجيل الدفعات.",
      confirm: "مصادقة",
      done: "تمت المصادقة على الأجور",
    },
    unlock: {
      trigger: "إلغاء القفل",
      title: "إلغاء قفل الأجور؟",
      description: "تعود الأجور إلى وضع المسودة وسيُعاد حسابها. يُسجَّل إلغاء القفل في سجل المركز.",
      reason: "سبب إلغاء القفل",
      reasonRequired: "أدخل سبب إلغاء القفل.",
      confirm: "إلغاء القفل",
      done: "تم إلغاء قفل الأجور",
    },
    pay: {
      trigger: "تحديد كمدفوع",
      title: (name: string) => `دفع — ${name}`,
      amount: "المبلغ المدفوع",
      date: "تاريخ الدفع",
      method: "طريقة الدفع",
      confirm: "تسجيل الدفع",
      done: "تم تسجيل الدفع",
    },
    exports: {
      payslip: "ورقة الأجر",
      summaryPdf: "ملخص (PDF)",
      summaryCsv: "ملخص (جدول بيانات)",
    },
    settings: {
      title: "أجور {the instructors}",
      description: "نوع الأجر، أو الأجر الثابت، أو نسبة العمولة حسب {the course}. يسري كل تغيير ابتداءً من التاريخ المختار؛ ويُحتفظ بالسجل.",
      edit: "تعديل",
      dialogTitle: (name: string) => `الأجر — ${name}`,
      mode: "نوع الأجر",
      monthlyAmount: "الأجر الشهري (MAD)",
      rates: "نسبة العمولة حسب {the course}",
      rateFor: (subject: string, level: string) => `${subject} — ${level}`,
      ratePercent: "النسبة (%)",
      effectiveFrom: "ابتداءً من",
      effectiveFromHint: "لا تتغير الأجور التي تمت المصادقة عليها.",
      noAssignment: "لم تُسند أي {courses}: أسند {the courses} من التخطيط أو المستخدمين.",
      saved: "تم حفظ إعدادات الأجر",
      current: {
        salary: (amount: string) => `الأجر ${amount} / شهريًا`,
        rates: (count: number) => `النسب المحددة: ${count}`,
        none: "للإعداد",
      },
      invalidAmount: "أدخل مبلغًا موجبًا.",
      invalidRate: "يجب أن تكون النسبة بين 0 و100.",
      history: "السجل",
      historyFrom: (date: string) => `ابتداءً من ${date}`,
      historyRange: (from: string, to: string) => `من ${from} إلى ${to}`,
    },
    pdf: {
      payslipTitle: "ورقة الأجر",
      summaryTitle: "ملخص الأجور",
      period: "الفترة",
      teacher: "{the instructor}",
      generatedAt: (date: string) => `حُرّر بتاريخ ${date}`,
      signature: "توقيع {the instructor}",
    },
  },
  expenses: {
    title: "مصاريف المركز",
    description: "الكراء، الفواتير، اللوازم… تدخل في صافي الدخل بلوحة القيادة.",
    supportUnavailable: "لا يمكن الاطلاع على مصاريف المركز في وضع الدعم.",
    month: "الشهر",
    previousMonth: "الشهر السابق",
    nextMonth: "الشهر التالي",
    quickAdd: {
      title: "إضافة مصروف",
      category: "الفئة",
      label: "البيان",
      labelPlaceholder: "مثال: فاتورة الكهرباء",
      amount: "المبلغ (MAD)",
      date: "التاريخ",
      method: "الأداء",
      methodNone: "غير محدد",
      recurring: "كل شهر",
      recurringHint: "يُنسخ كل شهر كمسودة، ويجب تأكيده.",
      receipt: "المستند المثبت",
      receiptHint: "صورة أو PDF، بحد أقصى 3 ميغابايت (اختياري).",
      add: "إضافة",
      added: "تمت إضافة المصروف",
    },
    drafts: {
      title: "في انتظار التأكيد",
      description: "مصاريف متكررة نُسخت لهذا الشهر بمبلغ الشهر السابق. عدّل المبلغ عند الحاجة، ثم أكّد.",
      confirm: "تأكيد",
      confirmed: "تم تأكيد المصروف",
      discard: "تجاهل هذا الشهر",
    },
    list: {
      title: "مصاريف الشهر",
      empty: "لم يُسجَّل أي مصروف لهذا الشهر.",
      filter: "الفئة",
      allCategories: "جميع الفئات",
      recurring: "متكرر",
      receipt: "المستند المثبت",
      noReceipt: "بدون مستند مثبت",
      attach: "إرفاق",
      edit: "تعديل",
      delete: "حذف",
      stopRecurring: "إيقاف التكرار",
      stoppedRecurring: "تم إيقاف التكرار",
      deleteTitle: (label: string) => `حذف «${label}»؟`,
      deleteDescription: "يُستبعد المصروف من المجاميع. يُسجَّل الحذف مع اسم منفّذه في سجل المركز.",
      deleted: "تم حذف المصروف",
      recordedBy: (name: string) => `أدخله ${name}`,
      total: "مجموع الشهر",
      count: (count: number) => `عدد المصاريف: ${count}`,
    },
    edit: {
      title: "تعديل المصروف",
      notes: "ملاحظة",
      saved: "تم حفظ المصروف",
    },
    breakdown: {
      title: "التوزيع حسب الفئة",
      empty: "يظهر التوزيع ابتداءً من أول مصروف في الشهر.",
      share: (percent: string) => `${percent} من المجموع`,
    },
    comparison: {
      title: "المقارنة مع الشهر السابق",
      current: "هذا الشهر",
      previous: "الشهر السابق",
      delta: "الفارق",
      up: (amount: string, percent: string) => `+ ${amount} (${percent})`,
      down: (amount: string, percent: string) => `− ${amount} (${percent})`,
      same: "مماثل",
      newSpend: "مصروف جديد",
      noPrevious: "لا توجد مصاريف في الشهر السابق.",
    },
    categories: {
      manage: "الفئات",
      title: "فئات المصاريف",
      description: "أضف فئات أو أعد تسميتها أو عطّلها. الفئة المعطلة لا تُقترح بعد ذلك؛ وتبقى مصاريفها.",
      name: "الاسم",
      icon: "الأيقونة",
      recurringDefault: "متكرر افتراضيًا",
      add: "إضافة فئة",
      save: "حفظ",
      saved: "تم حفظ الفئة",
      deactivate: "تعطيل",
      activate: "إعادة التفعيل",
      inactive: "معطلة",
      nameRequired: "أدخل اسمًا (60 حرفًا كحد أقصى).",
    },
    validation: {
      categoryRequired: "اختر فئة.",
      labelRequired: "أدخل بيانًا (120 حرفًا كحد أقصى).",
      amountInvalid: "أدخل مبلغًا أكبر من 0.",
      dateInvalid: "تاريخ غير صالح.",
      receiptInvalid: "المستند المثبت مرفوض: صورة (JPEG، PNG، WebP) أو PDF بحد أقصى 3 ميغابايت.",
    },
  },
  rooms: {
    title: "القاعات",
    description: "سعة كل قاعة وتجهيزاتها ونسبة استغلالها خلال الأسبوع.",
    add: "قاعة جديدة",
    edit: "تعديل",
    addTitle: "قاعة جديدة",
    editTitle: (name: string) => `تعديل — ${name}`,
    name: "الاسم",
    capacity: "السعة (عدد المقاعد)",
    capacityHint: "عدد {the learners} الذين تستوعبهم القاعة.",
    floor: "الطابق أو الموقع",
    floorPlaceholder: "مثال: الطابق الأول",
    equipment: "التجهيزات",
    notes: "ملاحظات",
    equipments: {
      whiteboard: "سبورة",
      projector: "جهاز عرض",
      screen: "شاشة",
      computers: "حواسيب",
      speakers: "نظام صوتي",
      air_conditioning: "تكييف",
    },
    capacityUnknown: "السعة غير محددة",
    places: (count: number) => `المقاعد: ${count}`,
    inactive: "معطلة",
    activate: "إعادة التفعيل",
    deactivate: "تعطيل",
    deactivateHint: "القاعة المعطلة لا تُقترح بعد ذلك في التخطيط؛ وتبقى حصصها الحالية.",
    delete: "حذف",
    deleteTitle: (name: string) => `حذف القاعة «${name}»؟`,
    deleteDescription: "ممكن فقط إذا لم تكن فيها أي حصة مبرمجة.",
    inUse: "لهذه القاعة حصص في التخطيط: انقلها أو عطّل القاعة.",
    duplicate: "توجد قاعة بهذا الاسم.",
    saved: "تم حفظ القاعة",
    deleted: "تم حذف القاعة",
    activated: "تمت إعادة تفعيل القاعة",
    deactivated: "تم تعطيل القاعة",
    nameRequired: "أدخل اسمًا (40 حرفًا كحد أقصى).",
    capacityInvalid: "أدخل عددًا بين 1 و500.",
    week: {
      title: "حصص الأسبوع",
      empty: "لا توجد حصص في هذه القاعة.",
      hours: (hours: string) => `${hours} س من الحصص أسبوعيًا`,
      slots: (count: number) => `الحصص: ${count}`,
      enrolled: (count: number) => `المسجلون: ${count}`,
      overCapacity: (enrolled: number, capacity: number) => `المسجلون: ${enrolled} / المقاعد: ${capacity}`,
      overCapacityShort: "القاعة صغيرة جدًا",
    },
    emptyTitle: "لا توجد قاعات",
    emptyDescription: "أضف قاعاتك: ستُقترح في التخطيط مع سعتها.",
    summary: (rooms: number, overloaded: number) =>
      overloaded > 0 ? `القاعات: ${rooms} · حصص تتجاوز السعة: ${overloaded}` : `القاعات: ${rooms}`,
  },
};
