import type { AppLabels } from "@/lib/constants/labels";

/** « B2 » → « القاعة B2 » ; « قاعة 1 » ou « Salle 1 » restent tels quels. */
function roomRef(name: string): string {
  const trimmed = name.trim();
  return /^(ال)?قاعة/.test(trimmed) || /^(salle|room)\b/i.test(trimmed) ? name : `القاعة ${name}`;
}

/** Libellés arabes : admin, days, daysShort. */
export const AR_PART8: Pick<AppLabels, "admin" | "days" | "daysShort"> = {
  admin: {
    common: {
      edit: "تعديل",
      delete: "حذف",
      save: "حفظ",
      saving: "جارٍ الحفظ…",
      create: "إنشاء",
      saved: "تم حفظ التعديلات",
      deleted: "تم الحذف",
      created: "تم الإنشاء",
      actions: "الإجراءات",
      deleteTitle: "تأكيد الحذف",
      irreversible: "هذا الإجراء نهائي.",
    },
    validation: {
      nameRequired: "هذا الحقل إلزامي.",
      nameTooLong: "هذا النص طويل جدًا.",
      phoneInvalid: "أدخل رقمًا صحيحًا، مثلًا 06 12 34 56 78.",
      timeInvalid: "وقت غير صالح (الصيغة HH:MM).",
      endBeforeStart: "يجب أن تكون ساعة النهاية بعد ساعة البداية.",
      sortOrderInvalid: "أدخل عددًا بين 0 و999.",
      priceInvalid: "أدخل مبلغًا صحيحًا.",
      levelRequired: "اختر {group}.",
      subjectRequired: "اختر {course}.",
      packRequired: "اختر باقة.",
      packSubjectsRequired: "حدّد {course} على الأقل.",
      teacherRequired: "اختر {instructor}.",
      roomRequired: "اختر قاعة.",
      emailRequired: "أدخل البريد الإلكتروني.",
      emailInvalid: "هذا البريد الإلكتروني غير صالح.",
      passwordTooShort: "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل.",
      assignmentsRequired: "حدّد {course} على الأقل.",
      notesTooLong: "يجب ألا تتجاوز الملاحظات 500 حرف.",
    },
    errors: {
      inUse: "تعذّر الحذف: هذا العنصر لا يزال مستعملًا.",
      duplicate: "هذا الاسم موجود مسبقًا.",
      roomConflict: "هذه القاعة محجوزة مسبقًا في هذه الفترة.",
      teacherConflict: "لدى {the instructor} حصة أخرى في هذه الفترة.",
      levelConflict: "لدى {the group} حصة أخرى في هذه الفترة: لا يمكن ل{the learners} حضور حصتين في الوقت نفسه.",
    },
    dashboard: {
      title: "لوحة القيادة",
      description: (month: string) => `وضعية شهر ${month}.`,
      filterLabel: "{the group}",
      allLevels: "جميع {the groups}",
      stats: {
        collected: "المحصّل هذا الشهر",
        collectedHint: (paid: number, total: number) => `الفواتير المؤداة: ${paid} من ${total}`,
        expected: "المتوقع هذا الشهر",
        expectedHint: "الفواتير التي تبدأ فترتها هذا الشهر",
        gap: "المتبقي للتحصيل",
        gapHint: (percent: string) => `${percent} من المبلغ المتوقع`,
        students: "{the learners}",
        studentsHint: "جميع {the learners} المسجلين في المركز",
        studentsHintLevel: "{the learners} حسب {the group} المختار",
        activeStudents: "{the learners} النشطون",
        collectedMonth: "المداخيل المحصّلة هذا الشهر",
        shortfall: "النقص في المداخيل",
        shortfallDetail: (percent: string, expected: string) => `${percent} من ${expected} المتوقعة`,
      },
      chart: {
        title: "نسبة الغياب حسب {the course}",
        description: "آخر 30 يومًا: الغيابات مقارنة بسجلات الحضور المُدخلة.",
        tooltip: (absent: number, total: number) => `الغيابات: ${absent}، سجلات الحضور المُدخلة: ${total}`,
        showTable: "عرض الجدول",
        hideTable: "إخفاء الجدول",
        caption: "نسبة الغياب حسب {the course}، آخر 30 يومًا",
        subject: "{the course}",
        level: "{the group}",
        absences: "الغيابات",
        records: "الإدخالات",
        rate: "النسبة",
        emptyTitle: "لم يُسجَّل أي حضور",
        emptyDescription: "سيظهر المبيان بمجرد أن يسجل {the instructors} الحضور.",
      },
    },
    subjects: {
      title: "{the groups} و{the courses}",
      description: "التنظيم التربوي والتعريفات الشهرية.",
      newLevel: "إضافة {group}",
      editLevel: "تعديل {the group}",
      levelName: "اسم {the group}",
      levelNamePlaceholder: "مثال: السنة الثانية بكالوريا علوم",
      sortOrder: "ترتيب العرض",
      sortOrderHint: "تُرتَّب {the groups} من الأصغر إلى الأكبر.",
      deleteLevel: (name: string) => `حذف {the group} «${name}»؟`,
      deleteLevelHint: "ممكن فقط إذا لم يكن ل{the group} أي {course} ولا أي {learner}.",
      newSubject: "إضافة {course}",
      editSubject: "تعديل {the course}",
      subjectName: "اسم {the course}",
      subjectNamePlaceholder: "مثال: الرياضيات",
      level: "{the group}",
      price: "التعريفة الشهرية (MAD)",
      priceHint: "تُطبَّق التعريفة على التسجيلات الجديدة. تحتفظ التسجيلات الحالية بتعريفة تسجيلها.",
      deleteSubject: (name: string) => `حذف {the course} «${name}»؟`,
      deleteSubjectHint: "ممكن فقط في غياب أي تسجيل مرتبط.",
      enrolled: (count: number) => `المسجلون: ${count}`,
      studentsInLevel: (count: number) => `{the learners}: ${count}`,
      noSubjects: "لا يوجد أي {course} بعد.",
      packsTitle: "الباقات",
      packsHint: "عدة {courses} بثمن شهري واحد، في فاتورة واحدة.",
      newPack: "باقة جديدة",
      editPack: "تعديل الباقة",
      packName: "اسم الباقة",
      packNamePlaceholder: "مثال: جميع {the courses}",
      packPrice: "الثمن الشهري للباقة (MAD)",
      packPriceHint: "يُطبَّق الثمن على الاشتراكات الجديدة. يحتفظ المشتركون الحاليون بثمن اشتراكهم.",
      packSubjects: "{the courses} المشمولة",
      packSubjectsHint: "يُسجَّل المشتركون تلقائيًا في كل ما تم تحديده من {the courses}، ويتابعون التغييرات.",
      selectAll: "تحديد الكل",
      packActive: "اقتراح هذه الباقة للتسجيلات الجديدة",
      unitTotal: (total: string) => `بشكل منفرد، تكلّف هذه {the courses} ${total} شهريًا.`,
      deletePack: (name: string) => `حذف الباقة «${name}»؟`,
      deletePackHint: "ممكن فقط إذا لم يكن للباقة أي مشترك من قبل. وإلا، ألغِ تحديد «اقتراح هذه الباقة».",
      noPacks: "لا توجد أي باقة بعد.",
      needSubjects: "أضف أولًا {courses} إلى {the group}.",
      emptyTitle: "لا يوجد أي {group}",
      emptyDescription: "أنشئ أول {group}، ثم أضف {courses} وتعريفاتها.",
    },
    planning: {
      title: "التخطيط",
      description: "الفترات الأسبوعية للمركز بأكمله.",
      newSlot: "فترة جديدة",
      editSlot: "تعديل الفترة",
      deleteSlot: "حذف الفترة",
      deleteConfirm: (subject: string, day: string, time: string) => `حذف فترة ${subject}، ${day} ${time}؟`,
      subject: "{the course}",
      teacher: "{the instructor}",
      day: "اليوم",
      start: "البداية",
      end: "النهاية",
      room: "القاعة",
      chooseRoom: "اختر قاعة",
      roomInactive: (name: string) => `${name} (معطّلة)`,
      roomHint: "تُنشأ القاعات وتُعدَّل من صفحة «القاعات».",
      noRooms: "لا توجد قاعة نشطة. أنشئ واحدة من صفحة «القاعات».",
      chooseSubject: "اختر {course}",
      chooseTeacher: "اختر {instructor}",
      noTeacher: "لم يُسنَد أي {instructor} إلى {the course}. أسنِد واحدًا من «المستخدمون».",
      conflict: {
        title: "تعذّر وضع هذه الحصة",
        types: { room: "القاعة محجوزة", teacher: "{the instructor} في حصة أخرى", level: "{the group} في حصة أخرى" },
        hours: (start: string, end: string) => `من ${start} إلى ${end}`,
        enrolled: (count: number) => `المسجلون: ${count}`,
        room: (room: string, day: string, hours: string, teacher: string, subject: string, level: string, enrolled: string) =>
          `${roomRef(room)} محجوزة مسبقًا يوم ${day} ${hours} من طرف ${teacher} — ${subject}، ${level}، ${enrolled}.`,
        teacher: (teacher: string, day: string, hours: string, subject: string, level: string, room: string, enrolled: string) =>
          `لدى ${teacher} حصة يوم ${day} ${hours} — ${subject}، ${level}، ${roomRef(room)}، ${enrolled}.`,
        level: (level: string, day: string, hours: string, subject: string, teacher: string, room: string, enrolled: string) =>
          `لدى {the group} ${level} حصة يوم ${day} ${hours} — ${subject} مع ${teacher}، ${roomRef(room)}، ${enrolled}. لا يمكن ل{the learners} حضور حصتين في الوقت نفسه.`,
        forecast: (count: number) => `عدد المسجلين المتوقع لهذه الحصة: ${count}.`,
        solutions: "حلول مقترحة",
        freeRooms: "القاعات الشاغرة في هذه الفترة",
        noFreeRoom: "لا توجد قاعة أخرى شاغرة في هذه الفترة.",
        tooSmall: (count: number) => `لا تتسع لـ${count} من {the learners}`,
        capacityUnknown: "السعة غير محددة",
        freeTimes: "أقرب الفترات الشاغرة",
        sameDay: "اليوم نفسه",
        otherDays: "خلال الأسبوع",
        noFreeTime: "لم يُعثر على أي فترة شاغرة ل{the instructor} و{the group}.",
        apply: "تطبيق",
        applyRoom: (room: string) => `نقل الحصة إلى ${room}`,
        applyTime: (day: string, time: string, room: string) => `نقل الحصة إلى يوم ${day} ${time}، ${room}`,
        resolved: "تم حفظ الفترة: حُلّ التعارض",
        modified: "تغيّر التخطيط في هذه الأثناء: إليك الوضعية المحدَّثة.",
      },
      grid: {
        axis: "عرض التخطيط",
        axes: { room: "حسب القاعة", teacher: "حسب {the instructor}", level: "حسب {the group}" },
        axesShort: { room: "القاعات", teacher: "{the instructors}", level: "{the groups}" },
        all: { room: "جميع القاعات", teacher: "جميع {the instructors}", level: "جميع {the groups}" },
        show: "عرض",
        day: "اليوم المعروض",
        dragHint: "اسحب حصة لتغيير يومها أو توقيتها.",
        dragHintRoom: "اسحب حصة داخل الجدول لتغيير توقيتها، أو إلى إحدى القاعات أعلاه لنقلها إليها.",
        dragHintTeacher: "اسحب حصة داخل الجدول لتغيير توقيتها، أو إلى أحد {the instructors} أعلاه لإسنادها إليه.",
        touchHint: "على الهاتف: اضغط مطولًا على حصة لنقلها.",
        dropOn: (name: string) => `إلى ${name}`,
        where: (day: string, time: string, room: string) => `${day} ${time}، ${room}`,
        moved: (subject: string, where: string) => `تم نقل ${subject}: ${where}`,
        moveTitle: (subject: string, level: string) => `نقل ${subject} · ${level}`,
        moveAttempt: (where: string) => `النقل المطلوب: ${where}.`,
        cancelMove: "إلغاء النقل",
        notEligible: (teacher: string, subject: string) =>
          `لم يتم إسناد {the course} «${subject}» إلى ${teacher}. قم بهذا الإسناد أولًا من «المستخدمون».`,
        roomInactive: "هذه القاعة معطّلة: أعد تفعيلها من صفحة «القاعات».",
        overloaded: (enrolled: number, capacity: number) => `المسجلون: ${enrolled}، المقاعد: ${capacity}`,
        overloadedShort: "القاعة صغيرة جدًا",
        overloadedCount: (count: number) => `حصص مكتظة: ${count}`,
        freeCount: (count: number) => `فترات شاغرة مفيدة: ${count}`,
        opportunitiesTitle: "قاعات شاغرة رغم وجود الطلب",
        opportunity: (subject: string, level: string, day: string, time: string, enrolled: number, room: string, capacity: number) =>
          `${subject} · ${level}، ${day} ${time}: عدد المسجلين ${enrolled}، وسعة ${room} ${capacity}.`,
        opportunityRoom: (room: string, capacity: number) => `${room} (السعة: ${capacity}) شاغرة في ذلك الوقت.`,
        moveTo: (room: string) => `نقل إلى ${room}`,
        freeLabel: (subject: string, enrolled: number) => `شاغرة لـ${subject} · المسجلون: ${enrolled}`,
        moveHere: "النقل إلى هنا",
        moveHereLabel: (subject: string, room: string) => `نقل ${subject} إلى ${room}، قاعة شاغرة وكافية السعة`,
        emptyEntity: "لا توجد أي حصة هذا الأسبوع.",
      },
      emptyTitle: "لا توجد أي فترة",
      emptyDescription: "أنشئ الفترات الأسبوعية للمركز.",
      noSubjectsTitle: "لا يوجد أي {course}",
      noSubjectsDescription: "أنشئ أولًا {groups} و{courses}.",
    },
    users: {
      title: "المستخدمون",
      description: "حسابات فريق المركز.",
      newUser: "مستخدم جديد",
      editUser: "تعديل المستخدم",
      caption: "حسابات المركز",
      name: "الاسم",
      role: "الدور",
      email: "البريد الإلكتروني",
      phone: "الهاتف",
      status: "الحالة",
      lastSignIn: "آخر تسجيل دخول",
      never: "أبدًا",
      active: "نشط",
      inactive: "معطّل",
      you: "أنت",
      deactivate: "تعطيل",
      reactivate: "إعادة التفعيل",
      deactivateConfirm: (name: string) => `تعطيل حساب ${name}؟`,
      deactivateHint: "لن يتمكن هذا الشخص من تسجيل الدخول بعد الآن. يُحتفظ بسجله.",
      deactivated: "تم تعطيل الحساب",
      reactivated: "تمت إعادة تفعيل الحساب",
      assignments: "{the courses} المُدرَّسة",
      assignmentsHint: "حدّد كل ما يُدرَّس من {the courses} و{the groups}.",
      roleLocked: "لا يمكن تغيير دور {the instructor}.",
      password: "كلمة مرور مؤقتة",
      passwordHint: "8 أحرف على الأقل. تُبلَّغ إلى الشخص المعني.",
      generate: "توليد",
      createdTitle: "تم إنشاء الحساب",
      createdDescription: "أرسل بيانات الدخول هذه. يمكن للشخص تسجيل الدخول فورًا، وسيختار كلمة مروره الخاصة عند أول تسجيل دخول.",
      copy: "نسخ بيانات الدخول",
      copied: "تم نسخ بيانات الدخول",
      emptyTitle: "لا يوجد أي مستخدم",
      emptyDescription: "أنشئ حسابات الفريق.",
    },
    students: {
      title: "{the learners}",
      description: "القائمة الكاملة، التعديل والحذف.",
      caption: "{learners} المركز",
      search: "البحث عن {learner}",
      searchPlaceholder: "اسم {the learner}",
      filterLevel: "{the group}",
      allLevels: "جميع {the groups}",
      filterStatus: "الأداء",
      allStatuses: "جميع حالات الأداء",
      name: "{the learner}",
      level: "{the group}",
      guardian: "ولي الأمر",
      unpaid: "المبلغ المتبقي",
      status: "الحالة",
      results: (count: number) => `{the learners}: ${count}`,
      emptyTitle: "لم يُعثر على أي {learner}",
      emptyDescription: "عدّل البحث أو عوامل التصفية.",
      edit: "تعديل {the learner}",
      delete: "حذف {the learner}",
      deleteConfirm: (name: string) => `حذف ${name}؟`,
      deleteHint: "ستُحذف أيضًا جميع التسجيلات والفواتير وسجلات الحضور والتذكيرات المرتبطة.",
      deleted: "تم حذف {the learner}",
      enrollments: {
        title: "التسجيلات",
        description: "تعريفة وحالة كل {course}. لتخفيض الثمن، امنح تخفيضًا.",
        price: "التعريفة الشهرية",
        active: "نشط",
        inactive: "متوقف",
        stop: "إيقاف",
        resume: "استئناف",
        add: "التسجيل في {course}",
        chooseSubject: "اختر {course}",
        noOtherSubject: "تم تسجيل {the learner} مسبقًا في جميع {the courses} المتاحة ل{the group}.",
        alreadyEnrolled: "ل{the learner} تسجيل سابق في {the course}: استعمل «استئناف».",
        addPack: "الاشتراك في باقة",
        choosePack: "اختر باقة",
        packAdded: "تم الاشتراك في الباقة. أُنشئت الفاتورة الأولى.",
        packActiveHint: "ل{the learner} باقة نشطة: لتغيير الصيغة، أوقف الباقة أولًا.",
        packNeedsStop: "للانتقال إلى باقة، أوقف أولًا {the courses} المؤداة بشكل منفرد.",
        saved: "تم تحديث التسجيل",
        added: "تمت إضافة التسجيل. أُنشئت الفاتورة الأولى.",
      },
    },
    reports: {
      title: "التقارير",
      description: "الأعداد والمواظبة. تصدير CSV متوافق مع Excel.",
      export: "تصدير بصيغة CSV",
      byLevel: "الأعداد حسب {the group}",
      bySubject: "الأعداد حسب {the course}",
      absenceRanking: "ترتيب {the courses} حسب نسبة الغياب",
      absenceRankingHint: "من النسبة الأعلى إلى الأدنى.",
      period: "الفترة",
      periods: { "30": "آخر 30 يومًا", "90": "آخر 90 يومًا", all: "منذ البداية" } as Record<string, string>,
      level: "{the group}",
      subject: "{the course}",
      students: "{the learners}",
      enrollments: "التسجيلات النشطة",
      price: "التعريفة الشهرية",
      monthlyRevenue: "المداخيل الشهرية (بشكل منفرد)",
      bySubjectHint: "تشمل التسجيلات أيضًا اشتراكات الباقات؛ أما المداخيل فلا تحتسب إلا {the courses} المؤداة بشكل منفرد.",
      byPack: "الباقات",
      byPackHint: "الاشتراكات النشطة والمداخيل الشهرية (ثمن الاشتراك).",
      pack: "الباقة",
      subscribers: "المشتركون",
      packRevenue: "المداخيل الشهرية",
      absences: "الغيابات",
      records: "الإدخالات",
      rate: "نسبة الغياب",
      rank: "الرتبة",
      total: "المجموع",
      emptyTitle: "لا توجد بيانات",
      emptyDescription: "تمتلئ التقارير مع التسجيلات وتسجيل الحضور.",
    },
  },
  days: ["الأحد", "الإثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"],
  daysShort: ["أحد", "اثنين", "ثلاثاء", "أربعاء", "خميس", "جمعة", "سبت"],
};
