import type { AppLabels } from "@/lib/constants/labels";

const plural = (n: number, one: string, two: string, few: string, many: string) =>
  n === 1 ? one : n === 2 ? two : n >= 3 && n <= 10 ? few : many;

/** Durée en jours au génitif : « يوم واحد »، « يومين »، « 3 أيام »، « 11 يومًا ». */
const daysPhrase = (n: number) => plural(n, "يوم واحد", "يومين", `${n} أيام`, `${n} يومًا`);

/** Libellés arabes : welcome, suspended, pastDueBanner, supportBanner, spaces, placeholder, actions, contact, billing, packs, discounts, paymentMethods, receipts, payment. */
export const AR_PART4: Pick<AppLabels, "welcome" | "suspended" | "pastDueBanner" | "supportBanner" | "spaces" | "placeholder" | "actions" | "contact" | "billing" | "packs" | "discounts" | "paymentMethods" | "receipts" | "payment"> = {
  welcome: {
    title: "مرحبًا",
    description: "اختر كلمة المرور للولوج إلى فضائك.",
    checking: "جارٍ التحقق من الرابط…",
    invalidTitle: "رابط غير صالح أو منتهي الصلاحية",
    invalidDescription: "اطلب دعوة جديدة من مسؤول المنصة.",
    password: "كلمة المرور",
    passwordHint: "8 أحرف على الأقل.",
    confirm: "تأكيد كلمة المرور",
    submit: "حفظ والولوج إلى فضائي",
    submitting: "جارٍ الحفظ…",
    tooShort: "8 أحرف على الأقل.",
    mismatch: "كلمتا المرور غير متطابقتين.",
    weak: "كلمة المرور ضعيفة جدًا: اختر كلمة أطول أو أكثر تنوعًا.",
    failed: "تعذّر الحفظ. أعد المحاولة.",
    signedInAs: (email: string) => `الحساب: ${email}`,
  },
  suspended: {
    title: "تم إيقاف الولوج",
    description: (center: string) =>
      `تم إيقاف الولوج${center ? ` إلى ${center}` : ""}: لم يتم أداء الاشتراك. بياناتك محفوظة وسيُعاد فتح الولوج فور تسوية الوضعية.`,
    cancelledTitle: "تم إلغاء الاشتراك",
    cancelledDescription: (center: string) =>
      `تم إلغاء الاشتراك${center ? ` الخاص بـ ${center}` : ""}. تظل البيانات متاحة للتصدير لمدة 90 يومًا عند الطلب.`,
    contact: (name: string | null) => (name ? `للتسوية، تواصل مع ${name}:` : "للتسوية، تواصل معنا:"),
    retry: "قمت بالتسوية، أعد المحاولة",
    restoredTitle: "تمت إعادة فتح الولوج",
    restoredDescription: "مركزك نشط من جديد.",
    continue: "متابعة",
  },
  pastDueBanner: {
    message: (days: number, date: string) =>
      days > 0
        ? `الاشتراك متأخر الأداء: سيتم إيقاف الولوج بعد ${daysPhrase(days)} (في ${date}).`
        : `الاشتراك متأخر الأداء: سيتم إيقاف الولوج اليوم.`,
    due: (date: string) => `تاريخ الاستحقاق: ${date}.`,
  },
  supportBanner: {
    message: (center: string, time: string) => `وضع الدعم — قراءة فقط — ${center} (حتى ${time}).`,
    leave: "الخروج من وضع الدعم",
  },
  spaces: {
    assistant: "فضاء الاستقبال",
    teacher: "فضاء {the instructor}",
    admin: "فضاء الإدارة",
    platform: "لوحة تحكم المنصة",
  },
  placeholder: {
    title: "شاشة قيد الإعداد",
    description: "ستكون هذه الشاشة متاحة في مرحلة لاحقة من المشروع.",
  },
  actions: {
    errors: {
      forbidden: "هذا الإجراء غير مسموح به لحسابك.",
      moduleDisabled: "هذه الميزة غير مضمّنة في عرض المركز.",
      invalid: "تحقق من حقول الاستمارة.",
      notFound: "العنصر غير موجود. حدّث الصفحة.",
      unexpected: "حدث خطأ. أعد المحاولة بعد لحظات.",
    },
  },
  contact: {
    call: "اتصال",
    whatsapp: "WhatsApp",
    callLabel: (name: string) => `الاتصال بـ ${name}`,
    whatsappLabel: (name: string) => `مراسلة ${name} عبر WhatsApp`,
  },
  billing: {
    cycle: { 1: "دورة يوم 1", 15: "دورة يوم 15" } as Record<number, string>,
    perMonth: "/ الشهر",
    period: (start: string, end: string) => `من ${start} إلى ${end}`,
    daysOverdue: (days: number) => `تأخير ${daysPhrase(Math.max(days, 1))}`,
    invoicesCount: (count: number) =>
      plural(Math.max(count, 1), "فاتورة واحدة", "فاتورتان", `${count} فواتير`, `${count} فاتورة`),
    studentsCount: (count: number) => `{the learners}: ${count}`,
  },
  packs: {
    pack: "باقة",
    label: (name: string) => `باقة ${name}`,
    includes: (subjects: string) => `تتضمن: ${subjects}`,
    subscribers: (count: number) => `المشتركون: ${count}`,
    inactive: "لم تعد معروضة",
    coveredByPack: (name: string) => `ضمن باقة ${name}`,
  },
  discounts: {
    title: "التخفيضات",
    badge: (value: string, reason: string) => `تخفيض ${value} — ${reason}`,
    more: (count: number) => `+${count}`,
    reasons: {
      sibling: "الإخوة",
      social: "وضعية اجتماعية",
      merit: "استحقاق",
      referral: "إحالة",
      other: "أخرى",
    },
    reasonOptions: {
      sibling: "الإخوة",
      social: "وضعية اجتماعية",
      merit: "استحقاق",
      referral: "إحالة",
      other: "أخرى",
    },
    types: { percentage: "نسبة مئوية", fixed_amount: "مبلغ ثابت" },
    scopes: { all_subjects: "جميع {the courses}", specific_subject: "{course} بالتحديد" },
    scopeAll: "جميع {the courses}",
    appliesTo: (target: string) => `على ${target}`,
    validFrom: (date: string) => `منذ ${date}`,
    validRange: (from: string, to: string) => `من ${from} إلى ${to}`,
    grantedBy: (name: string, date: string) => `مُنح من طرف ${name} في ${date}`,
    grantedOn: (date: string) => `مُنح في ${date}`,
    states: { active: "جارٍ", inactive: "معطّل", expired: "منتهٍ", upcoming: "قادم" },
    conflict: "يتداخل مع تخفيض آخر: يُطبَّق التخفيض الأنسب ل{the learner}.",
    emptyTitle: "لا توجد تخفيضات",
    emptyDescription: "تظهر هنا التخفيضات التي تمنحها الإدارة.",
    emptyAdminDescription: "امنح تخفيضًا: يُعاد حساب الصافي المستحق على الفواتير غير المؤداة.",
    readOnlyHint: "الإدارة وحدها تمنح التخفيضات أو تعدّلها.",
    add: "منح تخفيض",
    edit: "تعديل التخفيض",
    activate: "إعادة التفعيل",
    deactivate: "تعطيل",
    delete: "حذف",
    form: {
      title: "منح تخفيض",
      editTitle: "تعديل التخفيض",
      description: "يُعاد حساب الصافي المستحق على الفواتير غير المؤداة. لا تتغير الفواتير المؤداة.",
      type: "نوع التخفيض",
      percentValue: "النسبة المئوية (%)",
      amountValue: "المبلغ المخصوم (MAD)",
      amountHint: "يُخصم كل شهر من كل فاتورة معنية.",
      scope: "النطاق",
      target: "{the course} أو الباقة",
      chooseTarget: "اختر…",
      reason: "السبب",
      reasonNote: "توضيح",
      reasonNoteHint: "إلزامي للسبب «أخرى».",
      validFrom: "البداية",
      validTo: "النهاية (اختياري)",
      validToHint: "فارغ: تخفيض بدون تاريخ نهاية.",
      save: "حفظ التخفيض",
      saved: "تم حفظ التخفيض",
      activated: "تمت إعادة تفعيل التخفيض",
      deactivated: "تم تعطيل التخفيض",
      deleted: "تم حذف التخفيض",
      deleteTitle: "حذف هذا التخفيض؟",
      deleteDescription:
        "يُعاد حساب الفواتير غير المؤداة بدونه. تحتفظ الفواتير المؤداة بالتخفيض المطبَّق. للاحتفاظ بأثر، يُفضَّل «تعطيل».",
    },
    validation: {
      valueRequired: "أدخل قيمة أكبر من 0.",
      percentMax: "لا يمكن أن تتجاوز النسبة 100.",
      amountMax: "المبلغ مرتفع جدًا.",
      targetRequired: "اختر {the course} أو الباقة.",
      noteRequired: "وضّح السبب.",
      noteTooLong: "200 حرف كحد أقصى.",
      dateInvalid: "تاريخ غير صالح.",
      endBeforeStart: "يجب أن تكون النهاية بعد البداية.",
    },
    invoice: {
      full: "السعر الكامل",
      discount: "التخفيض",
      net: "الصافي المستحق",
      conflict: "عدة تخفيضات ممكنة: يُطبَّق الأنسب.",
    },
  },
  paymentMethods: { cash: "نقدًا", bank_transfer: "تحويل بنكي", card: "بطاقة", cheque: "شيك" },
  receipts: {
    title: "وصل الأداء",
    cancellationTitle: "وصل الإلغاء",
    number: (number: string) => `وصل رقم ${number}`,
    cancellationNumber: (number: string) => `إلغاء رقم ${number}`,
    issuedAt: (date: string) => `صدر في ${date}`,
    student: "{the learner}",
    level: "{the group}",
    period: "الفترة",
    subject: "{the course}",
    rate: "السعر",
    paid: "المؤدى",
    lines: "التفاصيل",
    linePeriod: (from: string, to: string) => `من ${from} إلى ${to}`,
    totalFull: "المجموع بالسعر الكامل",
    totalDiscount: "التخفيضات",
    total: "المجموع المؤدى",
    totalCancelled: "المجموع الملغى",
    method: "طريقة الأداء",
    balanceDue: "الباقي المستحق",
    nothingDue: "لا يوجد باقٍ مستحق",
    cashier: "تم التحصيل من طرف",
    cancelledBy: "أُلغي من طرف",
    cancels: (number: string) => `يلغي الوصل رقم ${number}`,
    cancelReason: "السبب",
    cancelledNotice: (number: string, date: string) => `وصل ملغى في ${date} (وصل الإلغاء رقم ${number}).`,
    thanks: "شكرًا على ثقتكم.",
    editedWith: "صادر عبر dirassty",
    phone: (phone: string) => `الهاتف: ${phone}`,
    print: "طباعة",
    printAgain: "إعادة الطباعة",
    close: "إغلاق",
    back: "رجوع",
    whatsapp: "مشاركة عبر WhatsApp",
    whatsappAgain: "إعادة الإرسال عبر WhatsApp",
    view: "عرض الوصل",
    printed: (date: string) => `طُبع في ${date}`,
    sent: (date: string) => `أُرسل عبر WhatsApp في ${date}`,
    cancelled: "ملغى",
    cancellation: "إلغاء",
    sectionTitle: "الوصولات",
    sectionDescription: "كل عملية تحصيل تُنتج وصلًا مرقّمًا. لا يمكن تعديل الوصل: يُصحَّح الخطأ بوصل إلغاء.",
    emptyTitle: "لا توجد وصولات",
    emptyDescription: "ستظهر الوصولات هنا بعد أول عملية تحصيل.",
    notFound: "الوصل غير موجود.",
    tokens: {
      student: "[élève]",
      period: "[période]",
      amount: "[montant]",
      center: "[centre]",
      link: "[lien]",
      number: "[numéro]",
    },
    whatsappTemplate:
      "Bonjour, voici le reçu [numéro] de [élève] pour [période] : [montant] réglés.\nReçu : [lien]\nMerci de votre confiance.\n[centre]",
    share: {
      title: "مشاركة الوصل عبر WhatsApp",
      noPhone: "لا يوجد رقم ولي أمر مسجّل في ملف {the learner}. أدخل الرقم المراد استعماله.",
      phone: "رقم WhatsApp لولي الأمر",
      phoneInvalid: "رقم غير صالح. مثال: 06 12 34 56 78.",
      send: "فتح WhatsApp",
      preparing: "جارٍ إعداد الوصل…",
      opened: "تم فتح WhatsApp: تحقق من الرسالة ثم أرسلها.",
      popupBlocked: "منع المتصفح فتح WhatsApp. اسمح بالنوافذ المنبثقة لهذا الموقع.",
    },
    cancel: {
      trigger: "إلغاء الوصل",
      title: (number: string) => `إلغاء الوصل رقم ${number}؟`,
      description:
        "يصدر وصل إلغاء برقم تسلسلي موالٍ ويُربط بهذا الوصل. تعود الفواتير المعنية غير مؤداة.",
      reason: "سبب الإلغاء",
      reasonRequired: "أدخل سبب الإلغاء.",
      confirm: "إصدار وصل الإلغاء",
      done: "تم إصدار وصل الإلغاء",
    },
  },
  payment: {
    trigger: "تحصيل",
    payThis: "تحصيل",
    title: "التحصيل",
    description: (name: string) => `اختر الفواتير التي يؤديها ولي أمر ${name}.`,
    invoices: "الفواتير المستحقة",
    selectAll: "تحديد الكل",
    method: "طريقة الأداء",
    total: "المجموع المراد تحصيله",
    totalFull: "السعر الكامل",
    totalDiscount: "التخفيضات",
    confirm: (amount: string) => `تحصيل ${amount}`,
    noneSelected: "حدد فاتورة واحدة على الأقل.",
    nothingToPay: "لا توجد فواتير مستحقة.",
    success: "تم تسجيل الأداء",
    receiptReady: (number: string, amount: string) => `وصل رقم ${number} · ${amount}`,
    recorded: (amount: string) => `تم تحصيل ${amount}`,
    receiptHint: "سلّم الوصل لولي الأمر: اطبعه أو أرسله عبر WhatsApp.",
    alreadyPaid: "إحدى الفواتير مؤداة مسبقًا. حدّث الصفحة.",
    overdue: "متأخر",
    due: (date: string) => `الاستحقاق: ${date}`,
  },
};
