import type { AppLabels } from "@/lib/constants/labels";

/** Libellés arabes : teacher, assistant, table, errors, styleguide. */
export const AR_PART9: Pick<AppLabels, "teacher" | "assistant" | "table" | "errors" | "styleguide"> = {
  teacher: {
    home: {
      title: "الرئيسية",
      greeting: (name: string) => `مرحبًا ${name}`,
      todaySessions: "{the sessions} اليوم",
      sessionsCount: (count: number) => `{the sessions}: ${count}`,
      takeAttendance: "تسجيل الحضور",
      editAttendance: "تعديل الحضور",
      attendanceDone: "تم تسجيل الحضور",
      attendancePartial: (marked: number, total: number) => `تم تسجيل ${marked} / ${total}`,
      attendanceTodo: "الحضور لم يُسجَّل بعد",
      studentsCount: (count: number) => `{the learners}: ${count}`,
      room: (room: string) => `القاعة: ${room}`,
      emptyTitle: "لا توجد {sessions} اليوم",
      emptyDescription: "تجد {the sessions} القادمة في استعمال الزمن الخاص بك.",
      seeSchedule: "عرض استعمال الزمن الخاص بي",
      stats: {
        sessionsToday: "{the sessions} اليوم",
        sessionsTodayDetail: (done: number) => `تسجيلات الحضور المنجزة: ${done}`,
        followedStudents: "{the learners} الذين أدرّسهم",
        followedStudentsDetail: (subjects: number) => `عدد {the courses}: ${subjects}`,
        presenceRate: "نسبة الحضور",
        presenceRateDetail: "آخر 30 يومًا، كل {the courses} التي تدرّسها",
      },
      mySessions: "{the sessions} الخاصة بي اليوم",
      sessionDetail: (time: string, room: string) => `${time} · ${room}`,
      students: {
        title: "{the learners} الذين أدرّسهم",
        caption: "{the learners} في {the courses} التي تدرّسها",
        name: "الاسم",
        level: "{the group}",
        subject: "{the course}",
        lastStatus: "آخر {session}",
        notMarked: "لم يُسجَّل الحضور بعد",
        emptyTitle: "لا يوجد {learners}",
        emptyDescription: "سيظهر هنا {the learners} المسجلون في {the courses} التي تدرّسها.",
      },
    },
    schedule: {
      title: "استعمال الزمن الخاص بي",
      description: "{the sessions} الخاصة بك هذا الأسبوع.",
      today: "اليوم",
      noSession: "لا توجد {sessions}",
      emptyTitle: "لا توجد {sessions} مبرمجة",
      emptyDescription: "لم تبرمج الإدارة لك أي {session} بعد.",
      time: (start: string, end: string) => `${start} – ${end}`,
    },
    call: {
      close: "مغادرة تسجيل الحضور",
      closeConfirm: "مغادرة تسجيل الحضور؟ ستُفقد الإشارات غير المؤكَّدة.",
      progress: (current: number, total: number) => `{the learner} ${current} من ${total}`,
      marked: (marked: number, total: number) => `تم تسجيل ${marked} / ${total}`,
      previous: "{the learner} السابق",
      next: "{the learner} التالي",
      present: "حاضر",
      absent: "غائب",
      notMarked: "غير مسجَّل",
      hint: "اسحب للانتقال إلى {learner} آخر. بلوحة المفاتيح: الأسهم، P (حاضر)، A (غائب).",
      summary: {
        title: "ملخص",
        description: "تحقق من الحضور. المس اسم {the learner} لتصحيح حالته.",
        presentCount: (count: number) => `الحاضرون: ${count}`,
        absentCount: (count: number) => `الغائبون: ${count}`,
        missing: (count: number) => `{the learners} غير المسجَّلين: ${count}`,
        toggle: (name: string, status: string) => `${name}: ${status}. المس للتغيير.`,
        back: "استئناف تسجيل الحضور",
        submit: "تأكيد الحضور",
        submitting: "جارٍ الحفظ…",
      },
      success: "تم حفظ الحضور",
      successDescription: (present: number, absent: number) => `الحاضرون: ${present}، الغائبون: ${absent}.`,
      notTodayTitle: "تاريخ {the session} لا يوافق اليوم",
      notTodayDescription: "لا يمكن تسجيل الحضور إلا في يوم {the session}.",
      emptyTitle: "لا يوجد {learners} مسجلون",
      emptyDescription: "لم يُسجَّل أي {learner} بعدُ في {the course}.",
      notFoundTitle: "تعذّر العثور على {the session}",
      notFoundDescription: "لم يتم العثور على {the session} ضمن ما أُسند إليك.",
      backHome: "العودة إلى الرئيسية",
      errors: {
        notToday: "لا يمكن حفظ الحضور إلا في يوم {the session}.",
        incomplete: "سجّل حضور جميع {the learners} قبل التأكيد.",
      },
    },
  },
  assistant: {
    dashboard: {
      title: "لوحة القيادة",
      stats: {
        unpaid: "المبالغ غير المؤداة",
        unpaidHint: (amount: string) => `${amount} للتحصيل`,
        overdue: "المتأخرات",
        overdueHint: (students: string, amount: string) => `${students} · ${amount}`,
        absencesToday: "غيابات اليوم",
        absencesTodayHint: "أبلغ عنها {the instructors}",
        absenceAlerts: "تنبيهات الغياب",
        absenceAlertsHint: "3 غيابات متتالية أو أكثر",
        overduePayments: "الأداءات المتأخرة",
        overduePaymentsDetail: (students: string, amount: string) => `${students} · ${amount}`,
        monthUnpaid: "المبالغ غير المؤداة لهذا الشهر",
        monthUnpaidDetail: (count: number) => `فواتير هذا الشهر غير المؤداة: ${count}`,
        absencesTodayDetail: (alerts: number) => `تنبيهات الغياب المفتوحة: ${alerts}`,
      },
      queue: {
        title: "تذكيرات اليوم",
        description: "{the learners} المتأخرون في الأداء، من الأقدم تأخرًا إلى الأحدث.",
        lastFollowUp: (date: string) => `آخر تذكير في ${date}`,
        neverFollowedUp: "لم يُذكَّر قط",
        emptyTitle: "لا توجد تذكيرات لإرسالها اليوم",
        emptyDescription: "تم تذكير جميع {the learners} المتأخرين اليوم، أو لا يوجد أي أداء متأخر.",
      },
      alerts: {
        title: "تنبيهات الغياب",
        description:
          "{the learners} الغائبون عن 3 {sessions} متتالية في نفس {the course}. يُغلق التنبيه بعد تذكير من نوع «غياب» أو عند عودة {the learner}.",
        absences: (count: number, subject: string) => `غيابات متتالية في ${subject}: ${count}`,
        lastSession: (date: string) => `آخر {session} في ${date}`,
        emptyTitle: "لا توجد تنبيهات غياب",
        emptyDescription: "لم يتغيب أي {learner} عن 3 {sessions} متتالية.",
      },
      openFile: "عرض الملف",
    },
    search: {
      title: "{the learners}",
      description: "ابحث عن {learner} باسمه.",
      label: "البحث عن {learner}",
      placeholder: "اسم {the learner}",
      clear: "مسح البحث",
      results: (count: number) => `{the learners}: ${count}`,
      searching: "جارٍ البحث…",
      emptyTitle: "لم يتم العثور على أي {learner}",
      emptyDescription: "تحقق من كتابة الاسم، أو سجّل {learner} جديدًا.",
      noStudentsTitle: "لا يوجد {learners} مسجلون",
      noStudentsDescription: "سيظهر هنا {the learners} المسجلون.",
      newStudent: "{learner} جديد",
    },
    student: {
      back: "العودة إلى {the learners}",
      guardian: "ولي الأمر",
      noGuardian: "لم يُدخَل أي ولي أمر",
      notes: "ملاحظات",
      enrolledOn: (date: string) => `تاريخ التسجيل: ${date}`,
      tabsLabel: "سجل {the learner}",
      tabs: { payments: "الأداءات", receipts: "الوصولات", absences: "الغيابات", followUps: "المتابعات" },
      sections: {
        subjects: "{the courses} المؤداة",
        payments: "سجل الأداءات",
        absences: "سجل الغيابات",
        followUps: "سجل المتابعات",
      },
      subjects: {
        nextDue: (date: string) => `تاريخ الاستحقاق القادم: ${date}`,
        upToDate: "لا توجد استحقاقات معلقة",
        emptyTitle: "لا توجد {courses}",
        emptyDescription: "{the learner} غير مسجل في أي {course}.",
      },
      payments: {
        caption: "فواتير {the learner}",
        subject: "{the course} أو الباقة",
        period: "الفترة",
        amount: "المبلغ",
        dueDate: "تاريخ الاستحقاق",
        status: "الحالة",
        paidOn: "تاريخ الأداء",
        markPaid: "تحديد كمؤدى",
        confirmTitle: "تأكيد الأداء",
        confirmDescription: (amount: string, subject: string, period: string) =>
          `أداء كامل لمبلغ ${amount} عن ${subject}، ${period}.`,
        confirmLead: (subject: string, period: string) => `${subject}، ${period}.`,
        confirm: "تأكيد الأداء",
        success: "تم تسجيل الأداء",
        alreadyPaid: "هذه الفاتورة مؤداة مسبقًا.",
        emptyTitle: "لا توجد فواتير",
        emptyDescription: "ستظهر الفواتير هنا بعد التسجيل.",
      },
      absences: {
        total: (count: number) => `الغيابات: ${count}`,
        emptyTitle: "لا توجد غيابات",
        emptyDescription: "لم يتغيب {the learner} عن أي {session}.",
      },
      followUps: {
        by: (name: string) => `بواسطة ${name}`,
        emptyTitle: "لا توجد متابعات",
        emptyDescription: "ستظهر هنا المتابعات المسجلة.",
      },
      notFoundTitle: "تعذّر العثور على {the learner}",
      notFoundDescription: "{the learner} غير موجود أو لا ينتمي إلى مركزك.",
    },
    newStudent: {
      title: "{learner} جديد",
      description: "التسجيل في أربع مراحل.",
      progress: (step: number, total: number) => `المرحلة ${step} من ${total}`,
      steps: ["الصورة والهوية", "ولي الأمر", "{the group} و{the courses}", "ملخص"],
      fields: {
        photo: "صورة {the learner}",
        photoHint: "اختيارية. تُلتقط بكاميرا الهاتف.",
        takePhoto: "التقاط صورة",
        retakePhoto: "إعادة التقاط الصورة",
        removePhoto: "حذف الصورة",
        compressing: "جارٍ تجهيز الصورة…",
        fullName: "الاسم الكامل",
        fullNamePlaceholder: "مثال: سلمى بناني",
        guardianName: "اسم ولي الأمر",
        guardianNamePlaceholder: "مثال: السيدة بناني",
        guardianPhone: "هاتف ولي الأمر",
        guardianPhonePlaceholder: "06 12 34 56 78",
        notes: "ملاحظات",
        notesPlaceholder: "الحساسية، معلومات مفيدة…",
        level: "{the group}",
        billingCycle: "دورة الأداء",
        billingCycleHint: "يوم الشهر الذي تستحق فيه كل فاتورة جديدة.",
        formula: "الصيغة",
        formulaUnit: "{the courses} بشكل منفرد",
        formulaPack: "الباقة",
        packs: "الباقة المختارة",
        packsHint: "يُسجَّل {the learner} في جميع {the courses} الخاصة بالباقة، بفاتورة واحدة.",
        subjects: "{the courses} المؤداة",
        subjectsHint: "حدّد {the courses} التي يؤديها {the learner}.",
        noSubjects: "لا توجد {courses} مقترحة بعدُ ل{the group}.",
        total: "المجموع الشهري",
      },
      summary: {
        identity: "{the learner}",
        guardian: "ولي الأمر",
        subjects: "{the courses}",
        firstInvoice: (start: string, end: string, cycle: string) =>
          `الفاتورة الأولى: الفترة من ${start} إلى ${end}، تُؤدّى اليوم (${cycle}). بعد ذلك، فاتورة كل شهر في هذا اليوم؛ وإذا لم تُؤدَّ، تصبح متأخرة في اليوم نفسه.`,
        edit: "تعديل",
      },
      previous: "السابق",
      next: "التالي",
      submit: "تسجيل {the learner}",
      submitting: "جارٍ التسجيل…",
      success: "تم تسجيل {the learner}",
      successDescription: "تم إنشاء الفاتورة الأولى.",
      validation: {
        fullNameRequired: "أدخل اسم {the learner}.",
        fullNameTooLong: "يجب ألا يتجاوز الاسم 100 حرف.",
        phoneInvalid: "أدخل رقمًا صالحًا، مثل 06 12 34 56 78.",
        notesTooLong: "يجب ألا تتجاوز الملاحظات 500 حرف.",
        levelRequired: "اختر {the group}.",
        subjectsRequired: "حدّد عنصرًا واحدًا على الأقل من {the courses}.",
        packRequired: "اختر باقة.",
        photoInvalid: "هذا الملف ليس صورة صالحة.",
        photoTooLarge: "حجم الصورة كبير جدًا، حتى بعد الضغط.",
      },
      errors: {
        photoUpload: "تعذّر رفع الصورة. أعد المحاولة أو سجّل {the learner} بدون صورة.",
      },
      noLevelsTitle: "لم يتم إعداد أي {group}",
      noLevelsDescription: "يجب على المدير أولًا إنشاء {the groups} و{the courses}.",
    },
    newTeacher: {
      title: "{instructor} جديد",
      description: "أنشئ الحساب وأسند {the courses} التي يدرّسها.",
      sections: {
        account: "الحساب",
        assignments: "{the courses} المدرَّسة",
      },
      fields: {
        fullName: "الاسم الكامل",
        fullNamePlaceholder: "مثال: رشيد بنعلي",
        phone: "الهاتف",
        phonePlaceholder: "06 12 34 56 78",
        email: "البريد الإلكتروني",
        emailPlaceholder: "prenom.nom@centre.ma",
        password: "كلمة المرور المؤقتة",
        passwordHint: "8 أحرف على الأقل. تُسلَّم إلى {the instructor}.",
        generate: "توليد",
        showPassword: "إظهار كلمة المرور",
        hidePassword: "إخفاء كلمة المرور",
        assignmentsHint: "حدّد كل {course} وكل {group} يدرّسه.",
      },
      submit: "إنشاء الحساب",
      submitting: "جارٍ الإنشاء…",
      validation: {
        fullNameRequired: "أدخل اسم {the instructor}.",
        phoneInvalid: "أدخل رقمًا صالحًا، مثل 06 12 34 56 78.",
        emailRequired: "أدخل البريد الإلكتروني ل{the instructor}.",
        emailInvalid: "هذا البريد الإلكتروني غير صالح.",
        passwordTooShort: "يجب أن تحتوي كلمة المرور على 8 أحرف على الأقل.",
        assignmentsRequired: "حدّد عنصرًا واحدًا على الأقل من {the courses}.",
      },
      errors: {
        emailExists: "يوجد حساب مسبقًا بهذا البريد الإلكتروني.",
        weakPassword: "كلمة المرور هذه ضعيفة جدًا. استخدم «توليد».",
      },
      success: {
        title: "تم إنشاء الحساب",
        description: "أرسل بيانات الدخول هذه إلى {the instructor}. يمكنه تسجيل الدخول فورًا.",
        email: "البريد الإلكتروني",
        password: "كلمة المرور المؤقتة",
        copy: "نسخ بيانات الدخول",
        copied: "تم نسخ بيانات الدخول",
        credentials: (email: string, password: string) =>
          `dirassty\nالبريد الإلكتروني: ${email}\nكلمة المرور المؤقتة: ${password}`,
        another: "إنشاء حساب {instructor} آخر",
      },
      noSubjectsTitle: "لم يتم إعداد أي {course}",
      noSubjectsDescription: "يجب على المدير أولًا إنشاء {the groups} و{the courses}.",
    },
  },
  table: {
    rowActions: "الإجراءات",
  },
  errors: {
    genericTitle: "تعذّر عرض هذه الصفحة",
    genericDescription: "تحقق من اتصالك بالإنترنت، ثم أعد المحاولة. إذا استمرت المشكلة، اتصل بمدير المركز.",
    notFoundTitle: "الصفحة غير موجودة",
    notFoundDescription: "هذه الصفحة غير موجودة أو تم نقلها.",
    backHome: "العودة إلى الرئيسية",
  },
  styleguide: {
    tokens: {
      title: "الدليل البصري",
      description: "ألوان dirassty وخطوطها وأشكالها.",
    },
    components: {
      title: "المكونات",
      description: "الأزرار والشارات والصور والجداول والمؤشرات.",
    },
    states: {
      title: "الحالات",
      description: "الحالات الفارغة وحالات التحميل والخطأ. الإشعارات.",
    },
    sections: {
      colors: "الألوان",
      textShades: "درجات ألوان النص سهلة القراءة",
      typography: "الخطوط",
      spacing: "التباعد",
      buttons: "الأزرار",
      callButtons: "أزرار وضع تسجيل الحضور",
      badges: "شارات الحالة",
      avatars: "صور {the learners}",
      table: "الجدول",
      stats: "المؤشرات",
      emptyState: "الحالة الفارغة",
      loading: "حالة التحميل",
      error: "حالة الخطأ",
      toasts: "الإشعارات",
    },
    swatches: {
      primary: "الأزرق الليلي الرئيسي",
      brand: "الأزرق الساطع",
      highlight: "الكهرماني المميِّز",
      success: "أخضر النجاح",
      danger: "أحمر التنبيه",
      warning: "برتقالي التحذير",
      background: "خلفية التطبيق",
      border: "الحدود",
      secondaryText: "النص الثانوي",
      text: "النص الرئيسي",
    },
    textShadesHint: "درجات أغمق من اللون نفسه، تُستعمل للنص لبلوغ نسبة تباين 4.5:1.",
    typography: {
      title: "عنوان الصفحة — 28 px، 700",
      section: "عنوان القسم — 20 px، 600",
      body: "النص — 15 px، 400. يحمل {the learners} الملتزمون بأداءاتهم شارة خضراء.",
      caption: "التعليق — 13 px، رمادي ثانوي",
      amount: "المبلغ",
      date: "التاريخ",
    },
    buttons: {
      primary: "حفظ",
      secondary: "ثانوي",
      outline: "بإطار",
      ghost: "خفي",
      destructive: "حذف",
      highlight: "تسجيل الحضور",
      link: "عرض الملف",
    },
    avatars: {
      list: "القائمة — 40 px",
      profile: "الملف — 96 px",
      call: "تسجيل الحضور — 200 px",
    },
    table: {
      student: "{the learner}",
      level: "{the group}",
      amount: "المبلغ المستحق",
      dueDate: "تاريخ الاستحقاق",
      status: "الحالة",
    },
    stats: {
      collected: "المحصّل هذا الشهر",
      expected: "المتوقع هذا الشهر",
      unpaid: "المبالغ غير المؤداة",
      absencesToday: "غيابات اليوم",
      vsLastMonth: "مقارنة بالشهر الماضي",
    },
    emptyState: {
      title: "لا يوجد {learners} بعد",
      description: "سيظهر هنا {the learners} المسجلون. أضف أول {learner}.",
      action: "إضافة {learner}",
    },
    errorState: {
      title: "تعذّر تحميل {the learners}",
      description: "فشل الاتصال بالخادم. تحقق من اتصالك بالإنترنت، ثم أعد المحاولة.",
    },
    toasts: {
      successTrigger: "إشعار نجاح",
      success: "تم تسجيل الأداء",
      successDescription: "تم تحديد الفاتورة كمؤداة.",
      errorTrigger: "إشعار خطأ",
      error: "تعذّر الحفظ",
      errorDescription: "تحقق من اتصالك، ثم أعد المحاولة.",
    },
  },
};
