import type { AppLabels } from "@/lib/constants/labels";

/** "B2" → "room B2"; "Room 1" stays "Room 1" (no "room Room 1"). */
function roomRef(name: string): string {
  return /^room\b/i.test(name.trim()) ? name : `room ${name}`;
}

function capitalize(text: string): string {
  return text.charAt(0).toUpperCase() + text.slice(1);
}

function enrolledLabel(count: number): string {
  return count === 1 ? `${count} {learner} enrolled` : `${count} {learners} enrolled`;
}

/** Libellés anglais : admin, days, daysShort. */
export const EN_PART8: Pick<AppLabels, "admin" | "days" | "daysShort"> = {
  admin: {
    common: {
      edit: "Edit",
      delete: "Delete",
      save: "Save",
      saving: "Saving…",
      create: "Create",
      saved: "Changes saved",
      deleted: "Deleted",
      created: "Created",
      actions: "Actions",
      deleteTitle: "Confirm deletion",
      irreversible: "This action cannot be undone.",
    },
    validation: {
      nameRequired: "This field is required.",
      nameTooLong: "This text is too long.",
      phoneInvalid: "Enter a valid number, for example 06 12 34 56 78.",
      timeInvalid: "Invalid time (HH:MM format).",
      endBeforeStart: "The end time must be after the start time.",
      sortOrderInvalid: "Enter a number between 0 and 999.",
      priceInvalid: "Enter a valid amount.",
      levelRequired: "Choose {a group}.",
      subjectRequired: "Choose {a course}.",
      packRequired: "Choose a pack.",
      packSubjectsRequired: "Tick at least one {course}.",
      teacherRequired: "Choose {a instructor}.",
      roomRequired: "Choose a room.",
      emailRequired: "Enter the email.",
      emailInvalid: "This email is not valid.",
      passwordTooShort: "The password must be at least 8 characters long.",
      assignmentsRequired: "Tick at least one {course}.",
      notesTooLong: "Notes must not exceed 500 characters.",
    },
    errors: {
      inUse: "Cannot delete: this item is still in use.",
      duplicate: "This name already exists.",
      roomConflict: "This room is already booked for this time slot.",
      teacherConflict: "This {instructor} already has a class in this time slot.",
      levelConflict: "This {group} already has a class in this time slot: its {learners} cannot attend two classes at the same time.",
    },
    dashboard: {
      title: "Dashboard",
      description: (month: string) => `Overview for ${month}.`,
      filterLabel: "{Group}",
      allLevels: "All {groups}",
      stats: {
        collected: "Collected this month",
        collectedHint: (paid: number, total: number) =>
          total === 1 ? `${paid} of ${total} invoice paid` : `${paid} of ${total} invoices paid`,
        expected: "Expected this month",
        expectedHint: "Invoices whose period starts this month",
        gap: "Still to collect",
        gapHint: (percent: string) => `${percent} of the expected amount`,
        students: "{Learners}",
        studentsHint: "{Learners} enrolled at the centre",
        studentsHintLevel: "{Learners} in this {group}",
        activeStudents: "Active {learners}",
        collectedMonth: "Revenue collected this month",
        shortfall: "Shortfall",
        shortfallDetail: (percent: string, expected: string) => `${percent} of the ${expected} expected`,
      },
      chart: {
        title: "Absence rate by {course}",
        description: "Last 30 days: absences compared with attendance records entered.",
        tooltip: (absent: number, total: number) =>
          `${absent === 1 ? "1 absence" : `${absent} absences`} out of ${total === 1 ? "1 attendance record" : `${total} attendance records`}`,
        showTable: "Show table",
        hideTable: "Hide table",
        caption: "Absence rate by {course}, last 30 days",
        subject: "{Course}",
        level: "{Group}",
        absences: "Absences",
        records: "Records",
        rate: "Rate",
        emptyTitle: "No attendance recorded",
        emptyDescription: "The chart will appear as soon as {instructors} have taken attendance.",
      },
    },
    subjects: {
      title: "{Groups} and {courses}",
      description: "Teaching structure and monthly fees.",
      newLevel: "New {group}",
      editLevel: "Edit {group}",
      levelName: "{Group} name",
      levelNamePlaceholder: "E.g. 2nd year BAC Sciences",
      sortOrder: "Display order",
      sortOrderHint: "{Groups} are sorted from lowest to highest.",
      deleteLevel: (name: string) => `Delete the {group} "${name}"?`,
      deleteLevelHint: "Only possible if the {group} has no {courses} and no {learners}.",
      newSubject: "Add {a course}",
      editSubject: "Edit {course}",
      subjectName: "{Course} name",
      subjectNamePlaceholder: "E.g. Mathematics",
      level: "{Group}",
      price: "Monthly fee (MAD)",
      priceHint: "The fee applies to new enrolments. Existing enrolments keep the fee they were enrolled at.",
      deleteSubject: (name: string) => `Delete the {course} "${name}"?`,
      deleteSubjectHint: "Only possible if no enrolment refers to it.",
      enrolled: (count: number) => `${count} enrolled`,
      studentsInLevel: (count: number) => (count === 1 ? `${count} {learner}` : `${count} {learners}`),
      noSubjects: "No {courses} for this {group}.",
      packsTitle: "Packs",
      packsHint: "Several {courses} at a single monthly price, on one invoice.",
      newPack: "New pack",
      editPack: "Edit pack",
      packName: "Pack name",
      packNamePlaceholder: "E.g. All {courses}",
      packPrice: "Monthly pack price (MAD)",
      packPriceHint: "The price applies to new subscriptions. Existing subscribers keep the price they subscribed at.",
      packSubjects: "Included {courses}",
      packSubjectsHint: "Subscribers are automatically enrolled in every ticked {course} and follow any changes.",
      selectAll: "Tick all",
      packActive: "Offer this pack for new enrolments",
      unitTotal: (total: string) => `Taken individually, these {courses} cost ${total} per month.`,
      deletePack: (name: string) => `Delete the pack "${name}"?`,
      deletePackHint: "Only possible if the pack has never had a subscriber. Otherwise, untick \"Offer this pack\".",
      noPacks: "No packs for this {group}.",
      needSubjects: "First add {courses} to this {group}.",
      emptyTitle: "No {groups}",
      emptyDescription: "Create a first {group}, then add {courses} and their fees.",
    },
    planning: {
      title: "Schedule",
      description: "Weekly time slots for the whole centre.",
      newSlot: "New time slot",
      editSlot: "Edit time slot",
      deleteSlot: "Delete time slot",
      deleteConfirm: (subject: string, day: string, time: string) => `Delete the ${subject} slot, ${day} ${time}?`,
      subject: "{Course}",
      teacher: "{Instructor}",
      day: "Day",
      start: "Start",
      end: "End",
      room: "Room",
      chooseRoom: "Choose a room",
      roomInactive: (name: string) => `${name} (deactivated)`,
      roomHint: "Rooms are created and edited from the \"Rooms\" page.",
      noRooms: "No active rooms. Create one from the \"Rooms\" page.",
      chooseSubject: "Choose {a course}",
      chooseTeacher: "Choose {a instructor}",
      noTeacher: "No {instructor} is assigned to this {course}. Assign one from \"Users\".",
      conflict: {
        title: "Cannot schedule this class",
        types: { room: "Room booked", teacher: "{Instructor} already teaching", level: "{Group} already in class" },
        hours: (start: string, end: string) => `from ${start} to ${end}`,
        enrolled: (count: number) => enrolledLabel(count),
        room: (room: string, day: string, hours: string, teacher: string, subject: string, level: string, enrolled: string) =>
          `${capitalize(roomRef(room))} is already booked on ${day} ${hours} by ${teacher} — ${subject}, ${level}, ${enrolled}.`,
        teacher: (teacher: string, day: string, hours: string, subject: string, level: string, room: string, enrolled: string) =>
          `${teacher} is already teaching on ${day} ${hours} — ${subject}, ${level}, ${roomRef(room)}, ${enrolled}.`,
        level: (level: string, day: string, hours: string, subject: string, teacher: string, room: string, enrolled: string) =>
          `The {group} ${level} already has a class on ${day} ${hours} — ${subject} with ${teacher}, ${roomRef(room)}, ${enrolled}. Its {learners} cannot attend two classes at the same time.`,
        forecast: (count: number) => `Expected headcount for this class: ${enrolledLabel(count)}.`,
        solutions: "Suggested solutions",
        freeRooms: "Rooms free in this time slot",
        noFreeRoom: "No other room is free in this time slot.",
        tooSmall: (count: number) => `too small for ${count} {learners}`,
        capacityUnknown: "capacity not specified",
        freeTimes: "Nearest free time slots",
        sameDay: "Same day",
        otherDays: "Later in the week",
        noFreeTime: "No free time slot found for this {instructor} and this {group}.",
        apply: "Apply",
        applyRoom: (room: string) => `Move the class to ${room}`,
        applyTime: (day: string, time: string, room: string) => `Move the class to ${day} ${time}, ${room}`,
        resolved: "Time slot saved: conflict resolved",
        modified: "The schedule changed in the meantime: here is the up-to-date situation.",
      },
      grid: {
        axis: "View the schedule",
        axes: { room: "By room", teacher: "By {instructor}", level: "By {group}" },
        axesShort: { room: "Rooms", teacher: "{Instructors}", level: "{Groups}" },
        all: { room: "All rooms", teacher: "All {instructors}", level: "All {groups}" },
        show: "Show",
        day: "Day shown",
        dragHint: "Drag a class to change its day or time.",
        dragHintRoom: "Drag a class within the grid to change its time, or onto a room above to move it there.",
        dragHintTeacher: "Drag a class within the grid to change its time, or onto {a instructor} above to assign it to them.",
        touchHint: "On a phone: long-press a class to move it.",
        dropOn: (name: string) => `to ${name}`,
        where: (day: string, time: string, room: string) => `${day} ${time}, ${room}`,
        moved: (subject: string, where: string) => `${subject} moved: ${where}`,
        moveTitle: (subject: string, level: string) => `Move ${subject} · ${level}`,
        moveAttempt: (where: string) => `Requested move: ${where}.`,
        cancelMove: "Cancel move",
        notEligible: (teacher: string, subject: string) =>
          `The {course} "${subject}" is not assigned to ${teacher}. Assign it to them first from "Users".`,
        roomInactive: "This room is deactivated: reactivate it from the \"Rooms\" page.",
        overloaded: (enrolled: number, capacity: number) => `${enrolled} enrolled for ${capacity} seats`,
        overloadedShort: "Room too small",
        overloadedCount: (count: number) => (count === 1 ? `${count} overcrowded class` : `${count} overcrowded classes`),
        freeCount: (count: number) => (count === 1 ? `${count} useful free slot` : `${count} useful free slots`),
        opportunitiesTitle: "Empty rooms while demand exists",
        opportunity: (subject: string, level: string, day: string, time: string, enrolled: number, room: string, capacity: number) =>
          `${subject} · ${level}, ${day} ${time}: ${enrolled} enrolled for ${capacity} seats in ${room}.`,
        opportunityRoom: (room: string, capacity: number) => `${room} (${capacity} seats) is free at that time.`,
        moveTo: (room: string) => `Move to ${room}`,
        freeLabel: (subject: string, enrolled: number) => `Free for ${subject} · ${enrolled} enrolled`,
        moveHere: "Move here",
        moveHereLabel: (subject: string, room: string) => `Move ${subject} to ${room}, a free room that is large enough`,
        emptyEntity: "No classes this week.",
      },
      emptyTitle: "No time slots",
      emptyDescription: "Create the centre's weekly time slots.",
      noSubjectsTitle: "No {courses}",
      noSubjectsDescription: "First create {groups} and {courses}.",
    },
    users: {
      title: "Users",
      description: "The centre's team accounts.",
      newUser: "New user",
      editUser: "Edit user",
      caption: "Centre accounts",
      name: "Name",
      role: "Role",
      email: "Email",
      phone: "Phone",
      status: "Status",
      lastSignIn: "Last sign-in",
      never: "Never",
      active: "Active",
      inactive: "Deactivated",
      you: "You",
      deactivate: "Deactivate",
      reactivate: "Reactivate",
      deactivateConfirm: (name: string) => `Deactivate ${name}'s account?`,
      deactivateHint: "This person will no longer be able to sign in. Their history is kept.",
      deactivated: "Account deactivated",
      reactivated: "Account reactivated",
      assignments: "{Courses} taught",
      assignmentsHint: "Tick each {course} and {group} taught.",
      roleLocked: "The {instructor} role cannot be changed.",
      password: "Temporary password",
      passwordHint: "At least 8 characters. Share it with the person.",
      generate: "Generate",
      createdTitle: "Account created",
      createdDescription: "Pass on these credentials. The person can sign in right away and will choose their own password the first time they sign in.",
      copy: "Copy credentials",
      copied: "Credentials copied",
      emptyTitle: "No users",
      emptyDescription: "Create your team's accounts.",
    },
    students: {
      title: "{Learners}",
      description: "Full list, editing and deletion.",
      caption: "Centre {learners}",
      search: "Search for {a learner}",
      searchPlaceholder: "{Learner} name",
      filterLevel: "{Group}",
      allLevels: "All {groups}",
      filterStatus: "Payment",
      allStatuses: "All payment statuses",
      name: "{Learner}",
      level: "{Group}",
      guardian: "Guardian",
      unpaid: "Balance due",
      status: "Status",
      results: (count: number) => (count === 1 ? `${count} {learner}` : `${count} {learners}`),
      emptyTitle: "No {learners} found",
      emptyDescription: "Change the search or the filters.",
      edit: "Edit {learner}",
      delete: "Delete {learner}",
      deleteConfirm: (name: string) => `Delete ${name}?`,
      deleteHint: "Their enrolments, invoices, attendance records and reminders will also be deleted.",
      deleted: "{Learner} deleted",
      enrollments: {
        title: "Enrolments",
        description: "Fee and status for each {course}. Price reductions are granted through a discount.",
        price: "Monthly fee",
        active: "Active",
        inactive: "Stopped",
        stop: "Stop",
        resume: "Resume",
        add: "Enrol in {a course}",
        chooseSubject: "Choose {a course}",
        noOtherSubject: "The {learner} is already enrolled in every {course} of their {group}.",
        alreadyEnrolled: "The {learner} already has an enrolment for this {course}: use \"Resume\".",
        addPack: "Subscribe to a pack",
        choosePack: "Choose a pack",
        packAdded: "Pack subscribed. The first invoice has been created.",
        packActiveHint: "The {learner} has an active pack: to change plan, stop the pack first.",
        packNeedsStop: "To switch to a pack, first stop the individually paid {courses}.",
        saved: "Enrolment updated",
        added: "Enrolment added. The first invoice has been created.",
      },
    },
    reports: {
      title: "Reports",
      description: "Headcounts and attendance. Excel-compatible CSV export.",
      export: "Export to CSV",
      byLevel: "Headcount by {group}",
      bySubject: "Headcount by {course}",
      absenceRanking: "{Courses} ranked by absence rate",
      absenceRankingHint: "From highest to lowest rate.",
      period: "Period",
      periods: { "30": "Last 30 days", "90": "Last 90 days", all: "Since the start" } as Record<string, string>,
      level: "{Group}",
      subject: "{Course}",
      students: "{Learners}",
      enrollments: "Active enrolments",
      price: "Monthly fee",
      monthlyRevenue: "Monthly revenue (individual)",
      bySubjectHint: "Enrolments include {learners} on a pack; revenue only counts {courses} paid individually.",
      byPack: "Packs",
      byPackHint: "Active subscriptions and monthly revenue (subscription price).",
      pack: "Pack",
      subscribers: "Subscribers",
      packRevenue: "Monthly revenue",
      absences: "Absences",
      records: "Records",
      rate: "Absence rate",
      rank: "Rank",
      total: "Total",
      emptyTitle: "No data",
      emptyDescription: "Reports fill up as enrolments and attendance are recorded.",
    },
  },
  days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
  daysShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
};
