import type { AppLabels } from "@/lib/constants/labels";

/** Libellés anglais : teacher, assistant, table, errors, styleguide. */
export const EN_PART9: Pick<AppLabels, "teacher" | "assistant" | "table" | "errors" | "styleguide"> = {
  teacher: {
    home: {
      title: "Home",
      greeting: (name: string) => `Hello ${name}`,
      todaySessions: "Today's {sessions}",
      sessionsCount: (count: number) => (count === 1 ? `${count} {session}` : `${count} {sessions}`),
      takeAttendance: "Take attendance",
      editAttendance: "Edit attendance",
      attendanceDone: "Attendance taken",
      attendancePartial: (marked: number, total: number) => `${marked} / ${total} marked`,
      attendanceTodo: "Attendance to take",
      studentsCount: (count: number) => (count === 1 ? `${count} {learner}` : `${count} {learners}`),
      room: (room: string) => `Room: ${room}`,
      emptyTitle: "No {sessions} today",
      emptyDescription: "Your upcoming {sessions} are in your timetable.",
      seeSchedule: "View my timetable",
      stats: {
        sessionsToday: "{Sessions} today",
        sessionsTodayDetail: (done: number) =>
          done === 1 ? `Attendance taken for ${done} {session}` : `Attendance taken for ${done} {sessions}`,
        followedStudents: "{Learners} taught",
        followedStudentsDetail: (subjects: number) =>
          subjects === 1 ? `Across ${subjects} {course}` : `Across ${subjects} {courses}`,
        presenceRate: "Attendance rate",
        presenceRateDetail: "Last 30 days, all your {courses}",
      },
      mySessions: "My {sessions} today",
      sessionDetail: (time: string, room: string) => `${time} · ${room}`,
      students: {
        title: "My {learners}",
        caption: "{Learners} in your {courses}",
        name: "Name",
        level: "{Group}",
        subject: "{Course}",
        lastStatus: "Last {session}",
        notMarked: "No attendance yet",
        emptyTitle: "No {learners}",
        emptyDescription: "{Learners} enrolled in your {courses} will appear here.",
      },
    },
    schedule: {
      title: "My timetable",
      description: "Your {sessions} this week.",
      today: "Today",
      noSession: "No {sessions}",
      emptyTitle: "No {sessions} scheduled",
      emptyDescription: "The administration has not scheduled any {sessions} for you yet.",
      time: (start: string, end: string) => `${start} – ${end}`,
    },
    call: {
      close: "Leave attendance",
      closeConfirm: "Leave attendance? Unsaved marks will be lost.",
      progress: (current: number, total: number) => `{Learner} ${current} of ${total}`,
      marked: (marked: number, total: number) => `${marked} / ${total} marked`,
      previous: "Previous {learner}",
      next: "Next {learner}",
      present: "Present",
      absent: "Absent",
      notMarked: "Not marked",
      hint: "Swipe to change {learner}. Keyboard: arrows, P (present), A (absent).",
      summary: {
        title: "Summary",
        description: "Check the attendance. Tap {a learner} to correct it.",
        presentCount: (count: number) => `${count} present`,
        absentCount: (count: number) => `${count} absent`,
        missing: (count: number) =>
          count === 1 ? `${count} {learner} not marked` : `${count} {learners} not marked`,
        toggle: (name: string, status: string) => `${name}: ${status}. Tap to change.`,
        back: "Resume attendance",
        submit: "Submit attendance",
        submitting: "Saving…",
      },
      success: "Attendance saved",
      successDescription: (present: number, absent: number) => `${present} present, ${absent} absent.`,
      notTodayTitle: "{Session} not today",
      notTodayDescription: "Attendance can only be taken on the day of the {session}.",
      emptyTitle: "No {learners} enrolled",
      emptyDescription: "No {learners} are enrolled in this {course} yet.",
      notFoundTitle: "{Session} not found",
      notFoundDescription: "This {session} does not exist or is not assigned to you.",
      backHome: "Back to home",
      errors: {
        notToday: "Attendance can only be saved on the day of the {session}.",
        incomplete: "Mark every {learner} before submitting.",
      },
    },
  },
  assistant: {
    dashboard: {
      title: "Dashboard",
      stats: {
        unpaid: "Unpaid",
        unpaidHint: (amount: string) => `${amount} to collect`,
        overdue: "Overdue",
        overdueHint: (students: string, amount: string) => `${students} · ${amount}`,
        absencesToday: "Absences today",
        absencesTodayHint: "Reported by {instructors}",
        absenceAlerts: "Absence alerts",
        absenceAlertsHint: "3 or more consecutive absences",
        overduePayments: "Overdue payments",
        overduePaymentsDetail: (students: string, amount: string) => `${students} · ${amount}`,
        monthUnpaid: "Unpaid this month",
        monthUnpaidDetail: (count: number) =>
          count === 1 ? `${count} unpaid invoice this month` : `${count} unpaid invoices this month`,
        absencesTodayDetail: (alerts: number) =>
          alerts === 1 ? `${alerts} open absence alert` : `${alerts} open absence alerts`,
      },
      queue: {
        title: "Today's reminders",
        description: "{Learners} with overdue payments, from the oldest to the most recent.",
        lastFollowUp: (date: string) => `Last reminder on ${date}`,
        neverFollowedUp: "Never reminded",
        emptyTitle: "No reminders to send today",
        emptyDescription: "All {learners} with overdue payments have been reminded today, or no payment is overdue.",
      },
      alerts: {
        title: "Absence alerts",
        description:
          "{Learners} absent from 3 {sessions} in a row in {a course}. The alert closes after an \"absence\" reminder or when the {learner} comes back.",
        absences: (count: number, subject: string) => `${count} consecutive absences in ${subject}`,
        lastSession: (date: string) => `Last {session} on ${date}`,
        emptyTitle: "No absence alerts",
        emptyDescription: "No {learner} has missed 3 {sessions} in a row.",
      },
      openFile: "View profile",
    },
    search: {
      title: "{Learners}",
      description: "Search for {a learner} by name.",
      label: "Search for {a learner}",
      placeholder: "{Learner}'s name",
      clear: "Clear search",
      results: (count: number) => (count === 1 ? `${count} {learner}` : `${count} {learners}`),
      searching: "Searching…",
      emptyTitle: "No {learners} found",
      emptyDescription: "Check the spelling of the name, or enrol a new {learner}.",
      noStudentsTitle: "No {learners} enrolled",
      noStudentsDescription: "Enrolled {learners} will appear here.",
      newStudent: "New {learner}",
    },
    student: {
      back: "Back to {learners}",
      guardian: "Parent/guardian",
      noGuardian: "No parent/guardian provided",
      notes: "Notes",
      enrolledOn: (date: string) => `Enrolled on ${date}`,
      tabsLabel: "{Learner} history",
      tabs: { payments: "Payments", receipts: "Receipts", absences: "Absences", followUps: "Follow-ups" },
      sections: {
        subjects: "Paid {courses}",
        payments: "Payment history",
        absences: "Absence history",
        followUps: "Follow-up history",
      },
      subjects: {
        nextDue: (date: string) => `Next due date: ${date}`,
        upToDate: "No pending due dates",
        emptyTitle: "No {courses}",
        emptyDescription: "This {learner} is not enrolled in any {course}.",
      },
      payments: {
        caption: "{Learner}'s invoices",
        subject: "{Course} or pack",
        period: "Period",
        amount: "Amount",
        dueDate: "Due date",
        status: "Status",
        paidOn: "Paid on",
        markPaid: "Mark as paid",
        confirmTitle: "Confirm payment",
        confirmDescription: (amount: string, subject: string, period: string) =>
          `Full payment of ${amount} for ${subject}, ${period}.`,
        confirmLead: (subject: string, period: string) => `${subject}, ${period}.`,
        confirm: "Confirm payment",
        success: "Payment recorded",
        alreadyPaid: "This invoice is already paid.",
        emptyTitle: "No invoices",
        emptyDescription: "Invoices will appear here after enrolment.",
      },
      absences: {
        total: (count: number) => (count === 1 ? `${count} absence` : `${count} absences`),
        emptyTitle: "No absences",
        emptyDescription: "This {learner} has not missed any {sessions}.",
      },
      followUps: {
        by: (name: string) => `by ${name}`,
        emptyTitle: "No follow-ups",
        emptyDescription: "Recorded follow-ups will appear here.",
      },
      notFoundTitle: "{Learner} not found",
      notFoundDescription: "This {learner} does not exist or does not belong to your centre.",
    },
    newStudent: {
      title: "New {learner}",
      description: "Enrolment in four steps.",
      progress: (step: number, total: number) => `Step ${step} of ${total}`,
      steps: ["Photo and identity", "Parent/guardian", "{Group} and {courses}", "Summary"],
      fields: {
        photo: "{Learner}'s photo",
        photoHint: "Optional. Taken with the phone's camera.",
        takePhoto: "Take a photo",
        retakePhoto: "Retake the photo",
        removePhoto: "Remove the photo",
        compressing: "Preparing the photo…",
        fullName: "Full name",
        fullNamePlaceholder: "e.g. Salma Bennani",
        guardianName: "Parent/guardian name",
        guardianNamePlaceholder: "e.g. Mrs Bennani",
        guardianPhone: "Parent/guardian phone",
        guardianPhonePlaceholder: "06 12 34 56 78",
        notes: "Notes",
        notesPlaceholder: "Allergies, useful information…",
        level: "{Group}",
        billingCycle: "Billing cycle",
        billingCycleHint: "Day of the month on which each new invoice is due.",
        formula: "Plan",
        formulaUnit: "Individual {courses}",
        formulaPack: "Pack",
        packs: "Selected pack",
        packsHint: "The {learner} is enrolled in every {course} in the pack, on a single invoice.",
        subjects: "Paid {courses}",
        subjectsHint: "Tick the {courses} paid for by the {learner}.",
        noSubjects: "No {courses} are offered for this {group} yet.",
        total: "Monthly total",
      },
      summary: {
        identity: "{Learner}",
        guardian: "Parent/guardian",
        subjects: "{Courses}",
        firstInvoice: (start: string, end: string, cycle: string) =>
          `First invoice: period from ${start} to ${end}, due today (${cycle}). After that, one invoice every month on that day; if unpaid, it becomes overdue the same day.`,
        edit: "Edit",
      },
      previous: "Previous",
      next: "Next",
      submit: "Enrol the {learner}",
      submitting: "Enrolling…",
      success: "{Learner} enrolled",
      successDescription: "The first invoice has been created.",
      validation: {
        fullNameRequired: "Enter the {learner}'s name.",
        fullNameTooLong: "The name must not exceed 100 characters.",
        phoneInvalid: "Enter a valid number, for example 06 12 34 56 78.",
        notesTooLong: "Notes must not exceed 500 characters.",
        levelRequired: "Choose {a group}.",
        subjectsRequired: "Tick at least one {course}.",
        packRequired: "Choose a pack.",
        photoInvalid: "This file is not a valid image.",
        photoTooLarge: "The photo is too large, even after compression.",
      },
      errors: {
        photoUpload: "The photo could not be uploaded. Try again or enrol the {learner} without a photo.",
      },
      noLevelsTitle: "No {groups} set up",
      noLevelsDescription: "The administrator must first create the {groups} and {courses}.",
    },
    newTeacher: {
      title: "New {instructor}",
      description: "Create the account and assign the {courses} taught.",
      sections: {
        account: "Account",
        assignments: "{Courses} taught",
      },
      fields: {
        fullName: "Full name",
        fullNamePlaceholder: "e.g. Rachid Benali",
        phone: "Phone",
        phonePlaceholder: "06 12 34 56 78",
        email: "Email",
        emailPlaceholder: "firstname.lastname@centre.ma",
        password: "Temporary password",
        passwordHint: "At least 8 characters. Share it with the {instructor}.",
        generate: "Generate",
        showPassword: "Show password",
        hidePassword: "Hide password",
        assignmentsHint: "Tick each {course} and {group} taught.",
      },
      submit: "Create account",
      submitting: "Creating…",
      validation: {
        fullNameRequired: "Enter the {instructor}'s name.",
        phoneInvalid: "Enter a valid number, for example 06 12 34 56 78.",
        emailRequired: "Enter the {instructor}'s email.",
        emailInvalid: "This email is not valid.",
        passwordTooShort: "The password must contain at least 8 characters.",
        assignmentsRequired: "Tick at least one {course}.",
      },
      errors: {
        emailExists: "An account already exists with this email.",
        weakPassword: "This password is too weak. Use \"Generate\".",
      },
      success: {
        title: "Account created",
        description: "Send these credentials to the {instructor}. They can sign in right away.",
        email: "Email",
        password: "Temporary password",
        copy: "Copy credentials",
        copied: "Credentials copied",
        credentials: (email: string, password: string) =>
          `dirassty\nEmail: ${email}\nTemporary password: ${password}`,
        another: "Create another {instructor}",
      },
      noSubjectsTitle: "No {courses} set up",
      noSubjectsDescription: "The administrator must first create the {groups} and {courses}.",
    },
  },
  table: {
    rowActions: "Actions",
  },
  errors: {
    genericTitle: "Unable to display this page",
    genericDescription:
      "Check your internet connection, then try again. If the problem persists, contact the centre administrator.",
    notFoundTitle: "Page not found",
    notFoundDescription: "This page does not exist or has been moved.",
    backHome: "Back to home",
  },
  styleguide: {
    tokens: {
      title: "Style guide",
      description: "dirassty colours, typography and shapes.",
    },
    components: {
      title: "Components",
      description: "Buttons, badges, photos, tables and indicators.",
    },
    states: {
      title: "States",
      description: "Empty, loading and error states. Notifications.",
    },
    sections: {
      colors: "Colours",
      textShades: "Accessible text shades",
      typography: "Typography",
      spacing: "Spacing",
      buttons: "Buttons",
      callButtons: "Attendance mode buttons",
      badges: "Status badges",
      avatars: "{Learner} photos",
      table: "Table",
      stats: "Indicators",
      emptyState: "Empty state",
      loading: "Loading state",
      error: "Error state",
      toasts: "Notifications",
    },
    swatches: {
      primary: "Primary navy",
      brand: "Bright blue",
      highlight: "Amber accent",
      success: "Success green",
      danger: "Alert red",
      warning: "Warning orange",
      background: "App background",
      border: "Borders",
      secondaryText: "Secondary text",
      text: "Primary text",
    },
    textShadesHint: "Darker shades of the same hue, used for text to reach a 4.5:1 contrast ratio.",
    typography: {
      title: "Page title — 28 px, 700",
      section: "Section title — 20 px, 600",
      body: "Body — 15 px, 400. {Learners} who are up to date with their payments get a green badge.",
      caption: "Caption — 13 px, secondary grey",
      amount: "Amount",
      date: "Date",
    },
    buttons: {
      primary: "Save",
      secondary: "Secondary",
      outline: "Outline",
      ghost: "Ghost",
      destructive: "Delete",
      highlight: "Take attendance",
      link: "View profile",
    },
    avatars: {
      list: "List — 40 px",
      profile: "Profile — 96 px",
      call: "Attendance — 200 px",
    },
    table: {
      student: "{Learner}",
      level: "{Group}",
      amount: "Amount due",
      dueDate: "Due date",
      status: "Status",
    },
    stats: {
      collected: "Collected this month",
      expected: "Expected this month",
      unpaid: "Unpaid",
      absencesToday: "Absences today",
      vsLastMonth: "vs last month",
    },
    emptyState: {
      title: "No {learners} yet",
      description: "Enrolled {learners} will appear here. Add your first {learner}.",
      action: "Add {a learner}",
    },
    errorState: {
      title: "Unable to load {learners}",
      description: "The connection to the server failed. Check your internet connection, then try again.",
    },
    toasts: {
      successTrigger: "Success notification",
      success: "Payment recorded",
      successDescription: "The invoice is marked as paid.",
      errorTrigger: "Error notification",
      error: "Unable to save",
      errorDescription: "Check your connection, then try again.",
    },
  },
};
