import type { AppLabels } from "@/lib/constants/labels";

function capitalize(text: string): string {
  return text.charAt(0).toUpperCase() + text.slice(1);
}

/** 15 → "15:00". */
function hourRange(hour: number): string {
  return `${hour}:00–${hour + 1}:00`;
}

function plural(count: number, singular: string, pluralForm: string): string {
  return count === 1 ? `${count} ${singular}` : `${count} ${pluralForm}`;
}

/** Libellés anglais : cash, absenceAlerts, roomOccupancy, financeDashboard, centerSettings, followUp. */
export const EN_PART7: Pick<AppLabels, "cash" | "absenceAlerts" | "roomOccupancy" | "financeDashboard" | "centerSettings" | "followUp"> = {
  cash: {
    description: "Today's payments by payment method, cash expected in the drawer, counting and closing.",
    shared: "Shared centre cash desk",
    personal: (name: string | null) => (name ? `${name}'s cash desk` : "Personal cash desk"),
    closedTitle: "Cash desk closed",
    closedDescription:
      "It opens with the first payment of the day. You can also open it now with the opening float.",
    openingFloat: "Opening float",
    openingFloatHint: "Change in the drawer at the start of the day; 0 if the centre doesn't use one.",
    open: "Open the cash desk",
    opened: "Cash desk opened",
    floatTitle: "Opening float to confirm",
    floatDescription: "No payment has been recorded yet: check the change in the drawer. After the first payment, the float is locked.",
    floatSave: "Save the float",
    floatSaved: "Opening float saved",
    floatLocked: (amount: string) =>
      `A payment has already been recorded: the opening float stays at ${amount}. To change it, record a "Float adjustment" movement.`,
    amountInvalid: "Enter a positive amount, to the nearest cent (e.g. 250 or 250.50).",
    sessionOf: (date: string) => `Cash desk of ${date}`,
    openedAt: (time: string, name: string | null, amount: string) =>
      `Opened at ${time}${name ? ` by ${name}` : ""} · float ${amount}`,
    closedAt: (date: string, name: string | null) => `Closed on ${date}${name ? ` by ${name}` : ""}`,
    status: { open: "Open", closed: "Closed", validated: "Validated" },
    staleTitle: "Another cash desk is still open",
    staleDescription: "Count it and close it: new payments go into today's cash desk.",
    methods: { cash: "Cash", bank_transfer: "Bank transfer", card: "Card", cheque: "Cheque" },
    total: "Total collected",
    transactions: (count: number) => plural(count, "transaction", "transactions"),
    listTitle: "Payments",
    listEmpty: "No payments in this session.",
    cancellation: "Cancellation",
    receipt: (number: string) => `Receipt ${number}`,
    movementsTitle: "Cash movements",
    movementsEmpty: "No movements.",
    movementKinds: {
      refund: "Refund",
      expense: "Expense paid in cash",
      teacher_pay: "Payroll paid in cash",
      bank_deposit: "Bank deposit",
      float_change: "Float adjustment",
      correction: "Correction",
    },
    hiddenReason: "Details visible to the admin only",
    correctsSession: (date: string) => `Corrects the cash desk of ${date}`,
    correctionsTitle: "Corrections after closing",
    correctionLine: (date: string, name: string | null) => `On ${date}${name ? ` by ${name}` : ""}`,
    afterCorrections: "After corrections",
    validationNotes: "Validation note",
    addMovement: "Cash movement",
    movementTitle: "Cash movement",
    movementDescription: "Cash going out or coming in outside of payments: it counts towards the expected cash.",
    movementKind: "Type",
    movementAmount: "Amount",
    movementDirection: { in: "Added to the drawer", out: "Taken from the drawer" },
    movementReason: "Reason",
    movementReasonRequired: "Enter the reason for the movement.",
    movementReasonPlaceholder: "E.g. bank deposit, refund to Salma Bennani",
    movementSave: "Save the movement",
    movementSaved: "Movement saved",
    expected: {
      title: "Expected cash",
      formula: (float: string, cash: string, movements: string) =>
        `Float ${float} + cash collected ${cash} ${movements.startsWith("-") ? "−" : "+"} movements ${movements.replace(/^-/, "")}`,
      note: "Bank transfers, cards and cheques are reconciled separately: they are not part of the variance.",
    },
    counted: "Amount counted",
    countedHint: "The cash actually in the drawer.",
    variance: {
      none: "Cash desk balanced",
      shortage: (amount: string) => `Shortage: ${amount}`,
      surplus: (amount: string) => `Surplus: ${amount}`,
    },
    varianceReason: "Reason for the variance",
    varianceReasonPlaceholder: "E.g. wrong change given",
    varianceReasonRequired: "Enter the reason for the variance before closing.",
    notes: "Notes (optional)",
    close: "Close the cash desk",
    closeConfirmTitle: "Close the cash desk?",
    closeConfirmDescription: "Once closed, the session can no longer change: any correction will go through a transaction dated today.",
    closeConfirm: "Close",
    closedToast: "Cash desk closed",
    countedCash: "Counted",
    supportReadOnly: "Support mode: the cash desk cannot be viewed.",
    settings: {
      title: "Cash desk",
      description: "Daily cash closing: one shared session, or one per person at the front desk.",
      perAssistant: "One cash desk per person at the front desk",
      perAssistantHint:
        "Essential as soon as two people work at the front desk: each variance is attributed to someone. Cash desks already open still need closing; the following ones use this setting.",
      threshold: "Alert threshold (variance)",
      thresholdHint: (amount: string) => `A variance of more than ${amount} (shortage or surplus) alerts the admin.`,
      thresholdInvalid: "Enter a positive amount, to the nearest cent.",
    },
    notification: (amount: string, date: string) => `Cash variance of ${amount} on ${date}`,
    admin: {
      historyTitle: "Session history",
      historyDescription: "This month's sessions: collected, expected, counted, variance and reason. A validated session is permanently locked.",
      monthsLabel: "Month",
      month: (month: string) => capitalize(month),
      empty: "No cash sessions this month.",
      indicators: {
        shortage: "Shortages this month",
        surplus: "Surpluses this month",
        net: (amount: string) => `Net variance: ${amount}`,
        exact: "Sessions without variance",
        exactHint: (exact: number, total: number) => `${exact} out of ${total} closed sessions`,
        collected: "Collected in the cash desks",
        validated: (count: number) => `${count} validated`,
      },
      peopleTitle: "Variances by person",
      peopleDescription: "A one-off variance is human error; repeated variances in the same direction are a warning sign to deal with.",
      personLine: (sessions: number, short: number, surplus: number) =>
        `${plural(sessions, "session", "sessions")} · ${plural(short, "shortage", "shortages")} · ${plural(surplus, "surplus", "surpluses")}`,
      repeated: "Repeated variances in the same direction",
      unknownPerson: "Deleted account",
      columns: {
        date: "Date",
        holder: "Cash desk",
        collected: "Collected",
        expected: "Expected",
        counted: "Counted",
        variance: "Variance",
        status: "Status",
      },
      corrections: (amount: string) => `Corrections: ${amount}`,
      open: "Details",
      report: "PDF report",
      backToCash: "Back to the cash desk",
      detailTitle: (date: string) => `Session of ${date}`,
      validate: {
        button: "Validate",
        title: "Validate the session?",
        description: "Once validated, the session is permanently locked: no further correction can be linked to it.",
        notes: "Validation note (optional)",
        action: "Validate the session",
        done: "Session validated",
      },
      correct: {
        button: "Correct",
        title: "Cash correction",
        description:
          "A transaction dated today, in your cash desk for today, linked to this session. Positive amount: money goes back into the drawer; negative: it comes out.",
        direction: { in: "Money found (in)", out: "Money missing (out)" },
        amount: "Amount",
        reason: "Reason",
        reasonPlaceholder: "E.g. banknote found under the drawer",
        already: (amount: string) => `Already corrected for this session: ${amount}.`,
        action: "Save the correction",
        done: "Correction saved",
      },
      staleAlert: (date: string, holder: string) => `The cash desk of ${date} (${holder}) has not been closed.`,
      staleAction: "Open the cash desk",
      pdf: {
        title: (date: string) => `Cash report for ${date}`,
        session: (holder: string, status: string) => `${holder} · ${status}`,
        opened: (time: string, name: string | null) => `Opened at ${time}${name ? ` by ${name}` : ""}`,
        closed: (time: string, name: string | null) => `Closed at ${time}${name ? ` by ${name}` : ""}`,
        notClosed: "Not closed",
        float: "Opening float",
        expectedCash: "Expected cash",
        counted: "Counted",
        variance: "Variance",
        reason: "Reason",
        receipts: "Payments",
        time: "Time",
        student: "{Learner}",
        receipt: "Receipt",
        method: "Method",
        amount: "Amount",
        movements: "Cash movements",
        corrections: "Corrections after closing",
        validationNotes: "Validation note",
        noReceipts: "No payments.",
        dayTotal: "Total collected for the day",
        signature: "Signature",
        generatedAt: (date: string) => `Generated on ${date}`,
        empty: "No cash session on that day.",
      },
    },
  },
  absenceAlerts: {
    title: "Absences to report",
    description: "Let the parent/guardian know the same day: the message is already written, you just need to send it.",
    emptyTitle: "No absences to report",
    emptyDescription: "Absences recorded by {instructors} will appear here.",
    disabled: "Absence alerts are turned off in the centre settings.",
    notifyAll: (count: number) => `Notify all (${count})`,
    notify: "Notify the guardian",
    notifyAgain: "Remind",
    recordCall: "Call made",
    recordInPerson: "Seen in person",
    otherChannel: "Other means",
    notifiedVia: (channel: string, date: string, by: string | null) => (by ? `Notified ${channel} on ${date} by ${by}` : `Notified ${channel} on ${date}`),
    notNotified: "Parent/guardian not notified yet",
    channels: { whatsapp: "via WhatsApp", phone_call: "by phone", in_person: "in person" },
    channelNames: { whatsapp: "WhatsApp", phone_call: "Phone", in_person: "In person" },
    series: "Series of absences",
    seriesHint: "Several consecutive absences: the message mentions the series.",
    session: (date: string, time: string | null) => (time ? `${date} · ${time}` : date),
    guardian: (name: string | null, phone: string | null) => [name, phone].filter(Boolean).join(" · ") || "No parent/guardian on file",
    noPhone: "No number: enter one to send the message.",
    recorded: "Notification recorded",
    alreadyNotified: "The parent/guardian has already been notified for this {session}. Use \"Remind\".",
    sequence: {
      title: "Notify parents/guardians",
      progress: (index: number, total: number) => `Absence ${index} of ${total}`,
      preview: "Message",
      open: "Open WhatsApp",
      skip: "Skip",
      done: "All absences have been handled.",
      close: "Finish",
    },
    tokens: {
      student: "[élève]",
      date: "[date]",
      day: "[jour]",
      subject: "[matière]",
      time: "[heure]",
      teacher: "[professeur]",
      center: "[centre]",
    },
    template:
      "Bonjour, nous vous informons que [élève] était absent(e) au cours de [matière] du [date] à [heure]. Merci de nous contacter si nécessaire.\n[centre]",
    seriesTemplate:
      "Bonjour, nous vous informons que [élève] a manqué plusieurs séances consécutives de [matière], la dernière le [date] à [heure]. Merci de nous contacter rapidement.\n[centre]",
    noTime: "class time",
    settings: {
      title: "Absence alerts",
      description: "Message sent to the parent/guardian on WhatsApp when {a learner} is absent.",
      enabled: "Offer to notify parents/guardians",
      enabledHint: "Shows the \"Absences to report\" block on the front desk dashboard.",
      template: "Absence message",
      templateHint: "Variables replaced when sending:",
      reset: "Restore the suggested message",
      preview: "Preview",
      sample: { student: "Salma Bennani", date: "Tuesday 14 October", day: "Tuesday", subject: "Mathematics", time: "17:00", teacher: "Mr Alami" },
    },
  },
  roomOccupancy: {
    title: "Room occupancy",
    description: "Share of opening hours during which each room is in use. Opening hours: from the first to the last class of each day.",
    overall: "Occupancy rate",
    overallHint: "All rooms combined, over the week.",
    peak: "Peak hour",
    peakValue: (day: string, hour: number) => `${day} ${hourRange(hour)}`,
    peakDetail: (rooms: number, total: number) => `${rooms} of ${total} ${total === 1 ? "room" : "rooms"} in use`,
    noPeak: "No classes",
    fullHours: "Full hours",
    fullHoursValue: (count: number) => (count === 0 ? "None" : count === 1 ? "1 hour" : `${count} hours`),
    fullHoursHint: (count: number) =>
      count === 0
        ? "There is always at least one room free."
        : "All rooms are taken: one more room would let you open classes at those times.",
    roomsTitle: "By room",
    heatmapTitle: "By day and hour",
    heatmapCaption: "Share of rooms in use, in %.",
    used: (hours: string, open: string) => `${hours} h of classes out of ${open} h of opening hours`,
    fill: (percent: string) => `Fill rate ${percent}`,
    fillHint: "Enrolled {learners} compared with seats during its classes.",
    capacityUnknown: "Capacity to be set",
    status: { saturated: "Saturated", balanced: "Balanced", underused: "Underused" },
    advice: {
      saturated: "In use almost all the time: spread out classes or open another room.",
      overloaded: (count: number) => (count <= 1 ? `${count} class exceeds the room's capacity.` : `${count} classes exceed the room's capacity.`),
      underused: (hours: string) => `Free ${hours} h a week during opening hours: enough to open a class.`,
      balanced: "Good use.",
    },
    legend: "Legend",
    legendSteps: ["Free", "Under 25%", "25 to 50%", "50 to 75%", "75 to 99%", "Full"],
    closed: "Outside class hours",
    closedCell: (day: string, hour: number) => `${day} ${hourRange(hour)}: outside class hours`,
    cell: (day: string, hour: number, percent: string, rooms: number, total: number) =>
      `${day} ${hourRange(hour)}: ${percent} · ${rooms} of ${total} ${total === 1 ? "room" : "rooms"}`,
    hour: "Time",
    hourLabel: (hour: number) => `${hour}:00`,
    emptyTitle: "No classes scheduled",
    emptyDescription: "Room occupancy will appear as soon as the schedule contains classes.",
  },
  financeDashboard: {
    title: "Monthly result",
    scope: "Whole centre, all {groups} combined.",
    collected: "Revenue collected",
    expected: "Expected revenue",
    unpaid: (amount: string) => `Gap (unpaid): ${amount}`,
    payroll: "Payroll",
    payrollHint: "Fixed salaries and commissions",
    expenses: "Expenses this month",
    net: "Net income",
    netFormula: "Collected − payroll − expenses",
    positive: "Profit",
    negative: "Loss",
    margin: "Net margin",
    marginHint: "Net income relative to revenue collected",
    marginNone: "No payments collected yet this month",
    details: { payroll: "View payroll", expenses: "View expenses" },
    chart: {
      title: "Last twelve months",
      description: "Collected, payroll, expenses and net income, month by month (MAD).",
      series: { collected: "Collected", payroll: "Payroll", expenses: "Expenses", net: "Net income" },
      showTable: "Show table",
      hideTable: "Hide table",
      caption: "Monthly result over twelve months",
      month: "Month",
      note: "Payroll for past months: pay runs recorded in the application.",
    },
    discounts: {
      title: "Discounts this month",
      description: "Reductions granted on this month's invoices: lost revenue to keep an eye on.",
      total: "Total discounts",
      students: (count: number) => (count <= 1 ? `${count} {learner} concerned` : `${count} {learners} concerned`),
      empty: "No discounts on this month's invoices.",
      byReason: "By reason",
    },
    collection: {
      title: "Collection this month",
      description: (month: string) =>
        `Invoices whose period starts in ${month} (campaign included): expected, collected to date, still to collect.`,
      expected: "Forecast",
      expectedHint: (count: number) => plural(count, "invoice", "invoices"),
      collected: "Collected to date",
      collectedHint: (paid: number, total: number) => `${paid} of ${total} paid`,
      remaining: "Still to collect",
      rate: "Collection rate",
      rateNone: "No invoices this month",
      comparison: (rate: string, previousRate: string) =>
        `On the same day last month, ${previousRate} of the forecast had been collected; this month, ${rate}.`,
      comparisonNone: "No invoices last month to compare with.",
      chart: {
        title: "Collection curve",
        description: "Cumulative amount collected day by day, compared with the same day of the previous month (MAD).",
        series: { current: "This month", previous: "Previous month" },
        expectedLine: "Forecast",
        day: "Day",
        dayLabel: (day: number) => `Day ${day}`,
        showTable: "Show table",
        hideTable: "Hide table",
        caption: "Cumulative amount collected day by day, this month and the previous month",
      },
    },
  },
  centerSettings: {
    title: "Centre settings",
    description: "Contact details, payment receipts, automatic re-enrolment and absence alerts.",
    contactTitle: "Contact details",
    contactDescription: "Shown in the header and footer of receipts.",
    address: "Address",
    phone: "Phone",
    receiptsTitle: "Receipts",
    format: "Print format",
    formats: {
      a5: "A5 (sheet)",
      ticket_80mm: "80 mm ticket (thermal printer)",
    },
    formatHints: {
      a5: "Half an A4 sheet, portrait.",
      ticket_80mm: "80 mm wide till roll.",
    },
    template: "WhatsApp message",
    templateHint: "Variables replaced when sending:",
    templateReset: "Restore the suggested message",
    preview: "Preview",
    save: "Save",
    saved: "Settings saved",
    addressTooLong: "200 characters maximum.",
    phoneInvalid: "Invalid number. Example: 05 22 00 00 00.",
    templateTooLong: "1,000 characters maximum.",
    templateNeedsLink: "The message must contain [lien] so the parent/guardian receives the receipt.",
    sample: { student: "Salma Bennani", period: "October 2026", amount: "450 MAD", number: "2026-0042", link: "https://…" },
  },
  followUp: {
    channels: { phone: "Phone", whatsapp: "WhatsApp", in_person: "In person" },
    types: { payment: "Payment", absence: "Absence" },
    dialog: {
      trigger: "Record a follow-up",
      triggerShort: "Follow up",
      title: "Record a follow-up",
      description: (name: string) => `Follow-up with ${name}.`,
      type: "Reason",
      channel: "Channel",
      note: "Note",
      notePlaceholder: "E.g. the parent promises to pay on Friday.",
      submit: "Save",
      success: "Follow-up recorded",
    },
    validation: {
      noteTooLong: "The note must not exceed 500 characters.",
    },
  },
};
