import type { AppLabels } from "@/lib/constants/labels";

/** Libellés anglais : payroll, expenses, rooms. */
export const EN_PART5: Pick<AppLabels, "payroll" | "expenses" | "rooms"> = {
  payroll: {
    title: "{Instructor} payroll",
    description: "Amounts calculated automatically each month: fixed salary, or commission on the full price paid by enrolled {learners}.",
    month: "Month",
    previousMonth: "Previous month",
    nextMonth: "Next month",
    supportUnavailable: "A centre's payroll data cannot be viewed in support mode.",
    status: { draft: "Draft", validated: "Validated", paid: "Paid" },
    statusHints: {
      draft: "Amounts follow enrolments until validation.",
      validated: "Amounts are locked. Record payments as you go.",
      paid: "All payments for the month have been recorded.",
    },
    validatedBy: (name: string, date: string) => `Validated by ${name} on ${date}`,
    validatedOn: (date: string) => `Validated on ${date}`,
    columns: {
      teacher: "{Instructor}",
      mode: "Pay type",
      computed: "Calculated",
      adjustment: "Adjustment",
      final: "Final amount",
      payment: "Payment",
    },
    modes: { fixed_salary: "Fixed salary", commission: "Commission", none: "Not set up" },
    total: "Monthly payroll total",
    teachersCount: (count: number) => (count === 1 ? "1 {instructor}" : `${count} {instructors}`),
    emptyTitle: "No {instructors}",
    emptyDescription: "Create {instructor} accounts and assign them {courses} to calculate payroll.",
    showDetail: "Show calculation details",
    hideDetail: "Hide details",
    detail: {
      subject: "{Course}",
      level: "{Group}",
      price: "Monthly fee",
      enrolled: "Enrolled",
      rate: "Rate",
      subtotal: "Subtotal",
      formula: (price: string, enrolled: number, rate: string, subtotal: string) =>
        `${price} × ${enrolled} × ${rate} = ${subtotal}`,
      noRate: "Rate not set",
      noSubjects: "No {courses} assigned to this {instructor}.",
      fullPriceNote: "Calculated on the full price and all enrolled {learners}, paid or not, including discounts.",
      salary: (amount: string, date: string) => `Monthly salary of ${amount}, since ${date}.`,
      noSalary: "No salary set for this month.",
      notConfigured: "Choose how this {instructor} is paid.",
    },
    notPaid: "To pay",
    notYet: "After validation",
    paidOn: (date: string, method: string) => `Paid on ${date} · ${method}`,
    adjustment: {
      trigger: "Adjustment",
      title: (name: string) => `Adjustment — ${name}`,
      description: "Bonus, deduction or advance already paid. The calculated amount does not change: the adjustment is added to it.",
      kind: "Type",
      kinds: { bonus: "Bonus (+)", deduction: "Deduction or advance (−)" },
      amount: "Amount (MAD)",
      reason: "Reason",
      reasonRequired: "Enter the reason for the adjustment.",
      remove: "Remove adjustment",
      saved: "Adjustment saved",
    },
    validate: {
      trigger: "Validate payroll",
      title: (month: string) => `Validate payroll for ${month}?`,
      description: "Amounts will be locked: later changes to enrolments or rates will no longer affect them. You will then be able to record payments.",
      confirm: "Validate",
      done: "Payroll validated",
    },
    unlock: {
      trigger: "Unlock",
      title: "Unlock payroll?",
      description: "Payroll goes back to draft and will be recalculated. The unlock is recorded in the centre's log.",
      reason: "Reason for unlocking",
      reasonRequired: "Enter the reason for unlocking.",
      confirm: "Unlock",
      done: "Payroll unlocked",
    },
    pay: {
      trigger: "Mark as paid",
      title: (name: string) => `Payment — ${name}`,
      amount: "Amount paid",
      date: "Payment date",
      method: "Payment method",
      confirm: "Record payment",
      done: "Payment recorded",
    },
    exports: {
      payslip: "Payslip",
      summaryPdf: "Summary (PDF)",
      summaryCsv: "Summary (spreadsheet)",
    },
    settings: {
      title: "{Instructor} pay",
      description: "Pay type, salary or commission rate per {course}. Each change applies from the chosen date; history is kept.",
      edit: "Edit",
      dialogTitle: (name: string) => `Pay — ${name}`,
      mode: "Pay type",
      monthlyAmount: "Monthly salary (MAD)",
      rates: "Commission rate per {course}",
      rateFor: (subject: string, level: string) => `${subject} — ${level}`,
      ratePercent: "Rate (%)",
      effectiveFrom: "Effective from",
      effectiveFromHint: "Payrolls already validated do not change.",
      noAssignment: "No {courses} assigned: assign {courses} in Schedule or Users.",
      saved: "Pay settings saved",
      current: {
        salary: (amount: string) => `Salary ${amount} / month`,
        rates: (count: number) => (count === 1 ? "1 rate set" : `${count} rates set`),
        none: "To set up",
      },
      invalidAmount: "Enter a positive amount.",
      invalidRate: "A rate must be between 0 and 100.",
      history: "History",
      historyFrom: (date: string) => `since ${date}`,
      historyRange: (from: string, to: string) => `from ${from} to ${to}`,
    },
    pdf: {
      payslipTitle: "Payslip",
      summaryTitle: "Payroll summary",
      period: "Period",
      teacher: "{Instructor}",
      generatedAt: (date: string) => `Issued on ${date}`,
      signature: "{Instructor}'s signature",
    },
  },
  expenses: {
    title: "Centre expenses",
    description: "Rent, bills, supplies… They are included in the net income on the dashboard.",
    supportUnavailable: "A centre's expenses cannot be viewed in support mode.",
    month: "Month",
    previousMonth: "Previous month",
    nextMonth: "Next month",
    quickAdd: {
      title: "Add an expense",
      category: "Category",
      label: "Description",
      labelPlaceholder: "E.g. electricity bill",
      amount: "Amount (MAD)",
      date: "Date",
      method: "Payment",
      methodNone: "Not specified",
      recurring: "Every month",
      recurringHint: "Copied each month as a draft, to be confirmed.",
      receipt: "Proof of payment",
      receiptHint: "Photo or PDF, 3 MB maximum (optional).",
      add: "Add",
      added: "Expense added",
    },
    drafts: {
      title: "To confirm",
      description: "Recurring expenses copied for this month, with last month's amount. Adjust the amount if needed, then confirm.",
      confirm: "Confirm",
      confirmed: "Expense confirmed",
      discard: "Skip this month",
    },
    list: {
      title: "This month's expenses",
      empty: "No expenses recorded for this month.",
      filter: "Category",
      allCategories: "All categories",
      recurring: "Recurring",
      receipt: "Proof of payment",
      noReceipt: "No proof of payment",
      attach: "Attach",
      edit: "Edit",
      delete: "Delete",
      stopRecurring: "Stop recurring",
      stoppedRecurring: "Recurrence stopped",
      deleteTitle: (label: string) => `Delete "${label}"?`,
      deleteDescription: "The expense is removed from the totals. The deletion is recorded with its author in the centre's log.",
      deleted: "Expense deleted",
      recordedBy: (name: string) => `Entered by ${name}`,
      total: "Monthly total",
      count: (count: number) => (count === 1 ? "1 expense" : `${count} expenses`),
    },
    edit: {
      title: "Edit expense",
      notes: "Note",
      saved: "Expense saved",
    },
    breakdown: {
      title: "Breakdown by category",
      empty: "The breakdown appears as soon as the month's first expense is added.",
      share: (percent: string) => `${percent} of total`,
    },
    comparison: {
      title: "Compared with last month",
      current: "This month",
      previous: "Previous month",
      delta: "Variance",
      up: (amount: string, percent: string) => `+ ${amount} (${percent})`,
      down: (amount: string, percent: string) => `− ${amount} (${percent})`,
      same: "Unchanged",
      newSpend: "New expense",
      noPrevious: "No expenses last month.",
    },
    categories: {
      manage: "Categories",
      title: "Expense categories",
      description: "Add, rename or deactivate categories. A deactivated category is no longer offered; its expenses remain.",
      name: "Name",
      icon: "Icon",
      recurringDefault: "Recurring by default",
      add: "Add a category",
      save: "Save",
      saved: "Category saved",
      deactivate: "Deactivate",
      activate: "Reactivate",
      inactive: "Deactivated",
      nameRequired: "Enter a name (60 characters maximum).",
    },
    validation: {
      categoryRequired: "Choose a category.",
      labelRequired: "Enter a description (120 characters maximum).",
      amountInvalid: "Enter an amount greater than 0.",
      dateInvalid: "Invalid date.",
      receiptInvalid: "Proof of payment rejected: photo (JPEG, PNG, WebP) or PDF, 3 MB maximum.",
    },
  },
  rooms: {
    title: "Rooms",
    description: "Capacity, equipment and weekly occupancy of each room.",
    add: "New room",
    edit: "Edit",
    addTitle: "New room",
    editTitle: (name: string) => `Edit — ${name}`,
    name: "Name",
    capacity: "Capacity (seats)",
    capacityHint: "Number of {learners} the room can hold.",
    floor: "Floor or location",
    floorPlaceholder: "E.g. 1st floor",
    equipment: "Equipment",
    notes: "Notes",
    equipments: {
      whiteboard: "Whiteboard",
      projector: "Projector",
      screen: "Screen",
      computers: "Computers",
      speakers: "Sound system",
      air_conditioning: "Air conditioning",
    },
    capacityUnknown: "Capacity not set",
    places: (count: number) => (count === 1 ? "1 seat" : `${count} seats`),
    inactive: "Deactivated",
    activate: "Reactivate",
    deactivate: "Deactivate",
    deactivateHint: "A deactivated room is no longer offered in the schedule; its current classes remain.",
    delete: "Delete",
    deleteTitle: (name: string) => `Delete room "${name}"?`,
    deleteDescription: "Only possible if no classes are scheduled in it.",
    inUse: "This room has classes in the schedule: move them or deactivate the room.",
    duplicate: "A room with this name already exists.",
    saved: "Room saved",
    deleted: "Room deleted",
    activated: "Room reactivated",
    deactivated: "Room deactivated",
    nameRequired: "Enter a name (40 characters maximum).",
    capacityInvalid: "Enter a number between 1 and 500.",
    week: {
      title: "This week's classes",
      empty: "No classes in this room.",
      hours: (hours: string) => `${hours} h of classes per week`,
      slots: (count: number) => (count === 1 ? "1 class" : `${count} classes`),
      enrolled: (count: number) => (count === 1 ? "1 enrolled" : `${count} enrolled`),
      overCapacity: (enrolled: number, capacity: number) => `${enrolled} enrolled for ${capacity} seats`,
      overCapacityShort: "Room too small",
    },
    emptyTitle: "No rooms",
    emptyDescription: "Add your rooms: they will be offered in the schedule, with their capacity.",
    summary: (rooms: number, overloaded: number) =>
      overloaded > 0
        ? `${rooms === 1 ? "1 room" : `${rooms} rooms`} · ${overloaded === 1 ? "1 class exceeds" : `${overloaded} classes exceed`} capacity`
        : rooms === 1
          ? "1 room"
          : `${rooms} rooms`,
  },
};
