import type { AppLabels } from "@/lib/constants/labels";

/** Libellés anglais : welcome, suspended, pastDueBanner, supportBanner, spaces, placeholder, actions, contact, billing, packs, discounts, paymentMethods, receipts, payment. */
export const EN_PART4: Pick<AppLabels, "welcome" | "suspended" | "pastDueBanner" | "supportBanner" | "spaces" | "placeholder" | "actions" | "contact" | "billing" | "packs" | "discounts" | "paymentMethods" | "receipts" | "payment"> = {
  welcome: {
    title: "Welcome",
    description: "Choose your password to access your space.",
    checking: "Checking the link…",
    invalidTitle: "Invalid or expired link",
    invalidDescription: "Ask the platform manager for a new invitation.",
    password: "Password",
    passwordHint: "At least 8 characters.",
    confirm: "Confirm password",
    submit: "Save and go to my space",
    submitting: "Saving…",
    tooShort: "At least 8 characters.",
    mismatch: "The two passwords do not match.",
    weak: "Password too weak: choose a longer or more varied one.",
    failed: "Could not save. Try again.",
    signedInAs: (email: string) => `Account: ${email}`,
  },
  suspended: {
    title: "Access suspended",
    description: (center: string) =>
      `Access${center ? ` to ${center}` : ""} is suspended: the subscription has not been paid. Your data is kept and access will be restored as soon as payment is settled.`,
    cancelledTitle: "Subscription cancelled",
    cancelledDescription: (center: string) =>
      `The subscription${center ? ` for ${center}` : ""} has been cancelled. Your data remains available for export for 90 days on request.`,
    contact: (name: string | null) => (name ? `To settle your account, contact ${name}:` : "To settle your account, contact us:"),
    retry: "I've paid, try again",
    restoredTitle: "Access restored",
    restoredDescription: "Your centre is active again.",
    continue: "Continue",
  },
  pastDueBanner: {
    message: (days: number, date: string) =>
      days > 0
        ? `Subscription payment overdue: access will be suspended in ${days} day${days === 1 ? "" : "s"} (on ${date}).`
        : `Subscription payment overdue: access will be suspended today.`,
    due: (date: string) => `Due date: ${date}.`,
  },
  supportBanner: {
    message: (center: string, time: string) => `Support mode — read-only — ${center} (until ${time}).`,
    leave: "Leave support mode",
  },
  spaces: {
    assistant: "Front desk",
    teacher: "{Instructor} space",
    admin: "Administration",
    platform: "Platform console",
  },
  placeholder: {
    title: "Screen in preparation",
    description: "This screen will be available in a future stage of the project.",
  },
  actions: {
    errors: {
      forbidden: "This action is not allowed for your account.",
      moduleDisabled: "This feature is not included in the centre's plan.",
      invalid: "Check the form fields.",
      notFound: "Item not found. Refresh the page.",
      unexpected: "Something went wrong. Try again in a moment.",
    },
  },
  contact: {
    call: "Call",
    whatsapp: "WhatsApp",
    callLabel: (name: string) => `Call ${name}`,
    whatsappLabel: (name: string) => `Message ${name} on WhatsApp`,
  },
  billing: {
    cycle: { 1: "Cycle on the 1st", 15: "Cycle on the 15th" } as Record<number, string>,
    perMonth: "/ month",
    period: (start: string, end: string) => `From ${start} to ${end}`,
    daysOverdue: (days: number) => (days <= 1 ? "1 day overdue" : `${days} days overdue`),
    invoicesCount: (count: number) => (count <= 1 ? "1 invoice" : `${count} invoices`),
    studentsCount: (count: number) => (count <= 1 ? "1 {learner}" : `${count} {learners}`),
  },
  packs: {
    pack: "Pack",
    label: (name: string) => `Pack ${name}`,
    includes: (subjects: string) => `Includes: ${subjects}`,
    subscribers: (count: number) => (count === 1 ? `${count} subscriber` : `${count} subscribers`),
    inactive: "No longer offered",
    coveredByPack: (name: string) => `Included in the ${name} pack`,
  },
  discounts: {
    title: "Discounts",
    badge: (value: string, reason: string) => `Discount ${value} — ${reason}`,
    more: (count: number) => `+${count}`,
    reasons: {
      sibling: "siblings",
      social: "social circumstances",
      merit: "merit",
      referral: "referral",
      other: "other",
    },
    reasonOptions: {
      sibling: "Siblings",
      social: "Social circumstances",
      merit: "Merit",
      referral: "Referral",
      other: "Other",
    },
    types: { percentage: "Percentage", fixed_amount: "Fixed amount" },
    scopes: { all_subjects: "All {courses}", specific_subject: "One {course}" },
    scopeAll: "all {courses}",
    appliesTo: (target: string) => `On ${target}`,
    validFrom: (date: string) => `Since ${date}`,
    validRange: (from: string, to: string) => `From ${from} to ${to}`,
    grantedBy: (name: string, date: string) => `Granted by ${name} on ${date}`,
    grantedOn: (date: string) => `Granted on ${date}`,
    states: { active: "Active", inactive: "Deactivated", expired: "Ended", upcoming: "Upcoming" },
    conflict: "Overlaps another discount: the one most favourable to the {learner} is applied.",
    emptyTitle: "No discounts",
    emptyDescription: "Discounts granted by the management appear here.",
    emptyAdminDescription: "Grant a discount: the net amount due is recalculated on unpaid invoices.",
    readOnlyHint: "Only the management can grant or change a discount.",
    add: "Grant a discount",
    edit: "Edit discount",
    activate: "Reactivate",
    deactivate: "Deactivate",
    delete: "Delete",
    form: {
      title: "Grant a discount",
      editTitle: "Edit discount",
      description: "The net amount due is recalculated on unpaid invoices. Paid invoices do not change.",
      type: "Discount type",
      percentValue: "Percentage (%)",
      amountValue: "Amount deducted (MAD)",
      amountHint: "Deducted every month from each invoice concerned.",
      scope: "Scope",
      target: "{Course} or pack",
      chooseTarget: "Choose…",
      reason: "Reason",
      reasonNote: "Details",
      reasonNoteHint: "Required for the \"Other\" reason.",
      validFrom: "Start",
      validTo: "End (optional)",
      validToHint: "Empty: discount with no end date.",
      save: "Save discount",
      saved: "Discount saved",
      activated: "Discount reactivated",
      deactivated: "Discount deactivated",
      deleted: "Discount deleted",
      deleteTitle: "Delete this discount?",
      deleteDescription:
        "Unpaid invoices are recalculated without it. Invoices already paid keep the discount applied. To keep a record, choose \"Deactivate\" instead.",
    },
    validation: {
      valueRequired: "Enter a value greater than 0.",
      percentMax: "A percentage cannot exceed 100.",
      amountMax: "Amount too high.",
      targetRequired: "Choose the {course} or pack.",
      noteRequired: "Specify the reason.",
      noteTooLong: "200 characters maximum.",
      dateInvalid: "Invalid date.",
      endBeforeStart: "The end must be after the start.",
    },
    invoice: {
      full: "Full price",
      discount: "Discount",
      net: "Net amount due",
      conflict: "Several discounts possible: the most favourable one is applied.",
    },
  },
  paymentMethods: { cash: "Cash", bank_transfer: "Bank transfer", card: "Card", cheque: "Cheque" },
  receipts: {
    title: "Payment receipt",
    cancellationTitle: "Cancellation receipt",
    number: (number: string) => `Receipt no. ${number}`,
    cancellationNumber: (number: string) => `Cancellation no. ${number}`,
    issuedAt: (date: string) => `Issued on ${date}`,
    student: "{Learner}",
    level: "{Group}",
    period: "Period",
    subject: "{Course}",
    rate: "Rate",
    paid: "Paid",
    lines: "Details",
    linePeriod: (from: string, to: string) => `from ${from} to ${to}`,
    totalFull: "Total at full price",
    totalDiscount: "Discounts",
    total: "Total paid",
    totalCancelled: "Total cancelled",
    method: "Payment method",
    balanceDue: "Balance due",
    nothingDue: "Nothing outstanding",
    cashier: "Collected by",
    cancelledBy: "Cancelled by",
    cancels: (number: string) => `Cancels receipt no. ${number}`,
    cancelReason: "Reason",
    cancelledNotice: (number: string, date: string) => `Receipt cancelled on ${date} (cancellation receipt no. ${number}).`,
    thanks: "Thank you for your trust.",
    editedWith: "Issued with dirassty",
    phone: (phone: string) => `Tel. ${phone}`,
    print: "Print",
    printAgain: "Reprint",
    close: "Close",
    back: "Back",
    whatsapp: "Share on WhatsApp",
    whatsappAgain: "Resend on WhatsApp",
    view: "View receipt",
    printed: (date: string) => `Printed on ${date}`,
    sent: (date: string) => `Sent on WhatsApp on ${date}`,
    cancelled: "Cancelled",
    cancellation: "Cancellation",
    sectionTitle: "Receipts",
    sectionDescription: "Every payment collected produces a numbered receipt. A receipt cannot be edited: a mistake is corrected with a cancellation receipt.",
    emptyTitle: "No receipts",
    emptyDescription: "Receipts will appear here after the first payment is collected.",
    notFound: "Receipt not found.",
    tokens: {
      student: "[élève]",
      period: "[période]",
      amount: "[montant]",
      center: "[centre]",
      link: "[lien]",
      number: "[numéro]",
    },
    whatsappTemplate:
      "Bonjour, voici le reçu [numéro] de [élève] pour [période] : [montant] réglés.\nReçu : [lien]\nMerci de votre confiance.\n[centre]",
    share: {
      title: "Share the receipt on WhatsApp",
      noPhone: "No parent/guardian number is recorded for this {learner}. Enter the number to use.",
      phone: "Parent/guardian WhatsApp number",
      phoneInvalid: "Invalid number. Example: 06 12 34 56 78.",
      send: "Open WhatsApp",
      preparing: "Preparing the receipt…",
      opened: "WhatsApp opened: check the message, then send it.",
      popupBlocked: "The browser blocked WhatsApp from opening. Allow pop-ups for this site.",
    },
    cancel: {
      trigger: "Cancel receipt",
      title: (number: string) => `Cancel receipt no. ${number}?`,
      description:
        "A cancellation receipt, numbered in sequence, is issued and linked to this receipt. The invoices concerned become payable again.",
      reason: "Reason for cancellation",
      reasonRequired: "Enter the reason for cancellation.",
      confirm: "Issue the cancellation receipt",
      done: "Cancellation receipt issued",
    },
  },
  payment: {
    trigger: "Collect payment",
    payThis: "Collect",
    title: "Payment collection",
    description: (name: string) => `Choose the invoices being paid by ${name}'s parent/guardian.`,
    invoices: "Invoices to pay",
    selectAll: "Select all",
    method: "Payment method",
    total: "Total to collect",
    totalFull: "Full price",
    totalDiscount: "Discounts",
    confirm: (amount: string) => `Collect ${amount}`,
    noneSelected: "Select at least one invoice.",
    nothingToPay: "No invoices to pay.",
    success: "Payment recorded",
    receiptReady: (number: string, amount: string) => `Receipt no. ${number} · ${amount}`,
    recorded: (amount: string) => `${amount} collected`,
    receiptHint: "Give the receipt to the parent/guardian: print it or send it on WhatsApp.",
    alreadyPaid: "One of the invoices is already paid. Refresh the page.",
    overdue: "Overdue",
    due: (date: string) => `Due ${date}`,
  },
};
