import type { AppLabels } from "@/lib/constants/labels";

/** Libellés anglais : absencesPage, dashboard, roles, nav, passwords, centerAddress, centerHost, auth, branding. */
export const EN_PART2: Pick<AppLabels, "absencesPage" | "dashboard" | "roles" | "nav" | "passwords" | "centerAddress" | "centerHost" | "auth" | "branding"> = {
  absencesPage: {
    title: "Absences",
    description: (date: string) => `{Learners} absent on ${date}.`,
    date: "Date",
    today: "Today",
    count: (count: number) => (count === 1 ? "1 absence" : `${count} absences`),
    subject: "{Course}",
    teacher: "{Instructor}",
    openFile: "View profile",
    emptyTitle: "No absences",
    emptyDescription: "No {learner} was marked absent on that day.",
    streak: (count: number) => `${count} absences in a row`,
  },
  dashboard: {
    statsTitle: "Statistics",
    detail: "View details",
    moreActions: (label: string) => `Actions — ${label}`,
    students: {
      title: "{Learner} list",
      caption: "The centre's {learners}",
      name: "Name",
      level: "{Group}",
      subjects: "{Course}",
      status: "Status",
      phone: "Parent's phone",
      actions: "Actions",
      sortBy: (column: string) => `Sort by ${column}`,
      search: "Search the list",
      searchPlaceholder: "{Learner}'s name",
      openFile: "View profile",
      call: "Call",
      whatsapp: "WhatsApp",
      rowActions: (name: string) => `Actions — ${name}`,
      emptyTitle: "No {learners}",
      emptyDescription: "Enrolled {learners} will appear here.",
      noMatch: "No {learner} matches this search.",
    },
    reminder: {
      title: "Reminder",
      cardTitle: "Today's follow-ups",
      cardDescription: (count: number) =>
        count === 0
          ? "No {learner} to follow up today."
          : count === 1
            ? "1 overdue {learner} to contact today."
            : `${count} overdue {learners} to contact today.`,
      link: "View list",
      dismiss: "Hide reminder",
    },
    presence: {
      title: "Attendance by {course}",
      ring: "attendance",
      detail: (level: string, students: number) => `${level} · ${students === 1 ? "1 {learner}" : `${students} {learners}`}`,
      link: "View details",
      emptyTitle: "No attendance recorded",
      emptyDescription: "Rates will appear after attendance is first taken.",
    },
  },
  roles: {
    admin: "Administrator",
    super_admin: "Platform owner",
    assistant: "Assistant",
    teacher: "{Instructor}",
  },
  nav: {
    mainLabel: "Main navigation",
    searchStudent: "Search for {a learner}",
    styleguideTokens: "Style guide",
    styleguideComponents: "Components",
    styleguideStates: "States",
    dashboard: "Dashboard",
    students: "{Learners}",
    newStudent: "New {learner}",
    newTeacher: "New {instructor}",
    home: "Home",
    schedule: "Timetable",
    subjects: "{Groups} and {courses}",
    planning: "Schedule",
    users: "Users",
    reports: "Reports",
    absences: "Absences",
    platformCenters: "Centres",
    platformCatalogue: "Catalogue",
    platformBilling: "Billing",
    platformSettings: "Settings",
    branding: "Branding",
    settings: "Settings",
    payroll: "Payroll",
    expenses: "Expenses",
    rooms: "Rooms",
    reenrollment: "Re-enrolment",
    cash: "Cash desk",
    sessions: "Today's {sessions}",
    resources: "Resources",
    short: {
      sessions: "{Sessions}",
      dashboard: "Home",
      subjects: "{Courses}",
      newStudent: "Enrol",
      newTeacher: "{Instructor}",
    },
  },
  passwords: {
    reset: "Reset password",
    resetFor: (name: string) => `Reset password — ${name}`,
    resetAdmin: "Reset the administrator's password",
    resetTitle: (name: string) => `New password for ${name}`,
    resetDescription:
      "The current password is never visible. You set a new, temporary one: the person is signed out of all their devices and must replace it the next time they sign in.",
    modeLegend: "Temporary password",
    modeGenerate: "Generate automatically (10 easy-to-read characters)",
    modeManual: "Enter it myself",
    manualLabel: "Temporary password",
    manualHint: "At least 8 characters.",
    confirm: "Reset",
    confirming: "Resetting…",
    cancel: "Cancel",
    doneTitle: "Temporary password",
    doneDescription: "It will never be shown again: copy it or send it now.",
    password: "Temporary password",
    loginCode: "Login code",
    address: "Sign-in address",
    copy: "Copy",
    copied: "Copied.",
    message: "WhatsApp message (editable)",
    whatsapp: "Send on WhatsApp",
    noPhone: "No phone number on file: give the password in person.",
    done: "I have passed on the password",
    staffMessage: (name: string, url: string, password: string) =>
      `Hello ${name}, your password has been reset. Sign in at ${url} with the temporary password ${password}, then choose a new one.`,
    studentMessage: (name: string, url: string, code: string, password: string) =>
      `Hello, here is ${name}'s new access: ${url} — code ${code}, temporary password ${password}. A new password will be requested at sign-in.`,
    lastReset: (date: string, by: string) => `Password reset on ${date} by ${by}`,
    lastResetByYou: (date: string) => `Password reset on ${date} by you`,
    unknownActor: "a manager",
    errors: {
      forbidden: "Access denied: you cannot reset this account's password.",
      rate_limited: "Too many resets in one hour. Try again later.",
      inactive: "This account is deactivated: reactivate it first.",
      not_found: "Account not found.",
      failed: "The password could not be changed. Try again.",
    },
    admins: {
      title: "Centre administrator",
      titlePlural: "Centre administrators",
      none: "No administrator.",
      lastSignIn: "Last sign-in",
      never: "Never signed in",
    },
    mine: {
      menu: "My password",
      title: "My password",
      description: "Enter your current password, then the new one.",
      current: "Current password",
      next: "New password",
      confirm: "Confirm new password",
      submit: "Save",
      submitting: "Saving…",
      saved: "Password changed. Your other devices have been signed out.",
      wrongCurrent: "Current password is incorrect.",
      back: "Back",
    },
    forced: {
      title: "Choose your new password",
      description:
        "Your password was set by a manager. Choose a personal one to continue: only you will know it.",
      submit: "Confirm and continue",
    },
    validation: {
      required: "Enter a password.",
      tooShort: "At least 8 characters.",
      tooLong: "72 characters at most.",
      mismatch: "The two passwords do not match.",
      sameAsOld: "Choose a password different from the current one.",
      weak: "Password too weak: add letters, numbers or symbols.",
      currentRequired: "Enter your current password.",
    },
    strength: {
      label: "Strength",
      levels: ["", "Weak", "Fair", "Good", "Excellent"],
    },
    sessionClosed: "Your session was closed (password changed). Please sign in again.",
    unavailable: "Service temporarily unavailable. Try again.",
  },
  centerAddress: {
    label: "Centre address",
    preview: "Preview",
    copy: "Copy",
    copied: "Address copied.",
    copyFailed: "Could not copy: select the address manually.",
    open: "Open",
    checking: "Checking address…",
    status: {
      available: "Address available.",
      current: "The centre's current address.",
      taken: "Address already used by another centre.",
      reserved: "Address reserved for the platform.",
      invalid: "2 to 63 characters: lowercase letters, numbers and hyphens (not at the start or end).",
    },
    change: "Change address",
    changeTitle: "Change the centre's address",
    changeDescription:
      "The old address will keep redirecting to the new one. The centre's accounts will have to sign in again: let the centre know.",
    newSlug: "New address",
    confirmLabel: (from: string, to: string) => `I confirm the change from ${from} to ${to}.`,
    submit: "Change address",
    submitting: "Changing…",
    changed: "Centre address changed.",
    cancel: "Cancel",
  },
  centerHost: {
    unavailable: "Service temporarily unavailable. Try again in a few moments.",
    notFoundTitle: "Centre not found",
    notFoundDescription: "No centre matches this address. Check the address your centre gave you.",
    notFoundLink: (root: string) => `Go to ${root}`,
    wrongCenter: "This account does not belong to this centre. Sign in from your centre's address:",
    platformAccount: "This is a platform console account. Sign in from its address:",
    transferred:
      "Your centre now has its own address. Sign in again here (just once), then bookmark this address:",
  },
  auth: {
    login: {
      title: "Sign in",
      description: "Access your centre's workspace.",
      email: "Email",
      emailPlaceholder: "name@centre.ma",
      password: "Password",
      showPassword: "Show password",
      hidePassword: "Hide password",
      submit: "Sign in",
      submitting: "Signing in…",
      forgotten: "Forgotten your password? Contact your centre's administrator.",
    },
    validation: {
      emailRequired: "Enter your email.",
      emailInvalid: "This email is not valid.",
      passwordRequired: "Enter your password.",
    },
    errors: {
      invalidInput: "Check the form fields.",
      invalidCredentials: "Incorrect email or password.",
      rateLimited: "Too many attempts. Wait a few minutes, then try again.",
      unavailable: "Unable to sign in right now. Check your internet connection, then try again.",
      inactive: "This account is deactivated. Contact your centre's administrator.",
    },
    inactive: {
      title: "Inactive account",
      description:
        "Your account is deactivated or not linked to any centre. Contact your centre's administrator to reactivate it.",
      retry: "Check again",
    },
    userMenu: {
      label: "Account menu",
      myPhoto: "My photo",
      signOut: "Sign out",
    },
    photo: {
      title: "My photo",
      description: "Visible to your centre's team.",
      adminTitle: (name: string) => `${name}'s photo`,
      adminDescription: "Visible to the centre's team.",
      label: "Photo",
      hint: "Taken with the camera, or chosen from your files.",
      save: "Save photo",
      remove: "Remove photo",
      saved: "Photo saved",
      removed: "Photo removed",
      change: (name: string) => `Change photo — ${name}`,
      uploadFailed: "The photo could not be uploaded. Try again.",
    },
  },
  branding: {
    title: "Branding",
    description: "Name, logo and colours for your interface, sign-in screen and emails.",
    standardOnly: "Standard plan: the interface uses the platform's colours. White label is enabled on request.",
    identity: "Identity",
    brandName: "Brand name",
    brandNameHint: "Shown in the browser tab, the sign-in screen and emails.",
    images: "Images",
    logo: "Logo",
    logoHint: "PNG, SVG or WebP, ideally with a transparent background, 2 MB maximum.",
    favicon: "Tab icon (favicon)",
    faviconHint: "Square, PNG or ICO, 64 × 64 px recommended.",
    loginBackground: "Sign-in screen background",
    loginBackgroundHint: "Landscape image, 1920 × 1080 px recommended.",
    choose: "Choose an image",
    replace: "Replace",
    remove: "Remove",
    uploading: "Uploading…",
    uploadFailed: "The image could not be uploaded (PNG, JPEG, WebP, SVG or ICO format, 2 MB maximum).",
    colors: "Colours",
    primary: "Primary colour",
    primaryHint: "Sidebar, buttons, links, focus.",
    secondary: "Secondary colour",
    secondaryHint: "Gradients and app background.",
    accent: "Accent colour",
    accentHint: "Highlights and indicators.",
    colorInvalid: "Colour in #RRGGBB format.",
    preview: "Preview",
    previewButton: "Primary button",
    emails: "Emails",
    senderName: "Sender name",
    supportEmail: "Reply-to and support address",
    supportPhone: "Support phone",
    domain: "Custom domain",
    domainHint: (target: string) =>
      `The client creates a CNAME record for their domain (e.g. app.mycentre.ma) pointing to ${target}, then you verify it.`,
    domainInvalid: "Invalid domain (e.g. app.mycentre.ma).",
    domainVerified: "Domain verified",
    domainPending: "Awaiting verification",
    verify: "Verify domain",
    verifying: "Verifying…",
    verifiedOk: "Domain verified: it points to the platform.",
    verifiedKo: (target: string) => `The domain does not point to ${target} yet (DNS propagation can take a few hours).`,
    noTarget: "DNS target not configured: set PLATFORM_CNAME_TARGET or ROOT_DOMAIN.",
    save: "Save branding",
    saving: "Saving…",
    saved: "Branding saved",
    edit: "Edit branding",
    optional: "optional",
  },
};
