import type { AppLabels } from "@/lib/constants/labels";

/** Ordinal anglais : 1 → "1st", 2 → "2nd", 11 → "11th". */
function ordinal(value: number): string {
  const lastTwo = value % 100;
  if (lastTwo >= 11 && lastTwo <= 13) return `${value}th`;
  switch (value % 10) {
    case 1:
      return `${value}st`;
    case 2:
      return `${value}nd`;
    case 3:
      return `${value}rd`;
    default:
      return `${value}th`;
  }
}

/** Libellés anglais : app, common, theme, currency, status, notifications, studentAccess, studentLogin, resources, studentSpace, attendanceMarkers, sessions, attendanceConflicts, attendanceSheet. */
export const EN_PART1: Pick<
  AppLabels,
  | "app"
  | "common"
  | "theme"
  | "currency"
  | "status"
  | "notifications"
  | "studentAccess"
  | "studentLogin"
  | "resources"
  | "studentSpace"
  | "attendanceMarkers"
  | "sessions"
  | "attendanceConflicts"
  | "attendanceSheet"
> = {
  app: {
    name: "dirassty",
    tagline: "Run your centre, simply.",
    poweredBy: "Powered by dirassty",
    metaDescription: "Subscriptions, payments and attendance for your language or tutoring centre.",
  },
  common: {
    loading: "Loading…",
    retry: "Try again",
    cancel: "Cancel",
    confirm: "Confirm",
    save: "Save",
    search: "Search",
    back: "Back",
    close: "Close",
    more: "More",
    openMenu: "Open menu",
    skipToContent: "Skip to main content",
    signOut: "Sign out",
    language: "Language",
    seeAll: "See all",
    show: "Show",
    none: "—",
  },
  theme: {
    toggleToDark: "Switch to dark theme",
    toggleToLight: "Switch to light theme",
  },
  currency: {
    code: "MAD",
  },
  status: {
    upToDate: "Up to date",
    overdue: "Overdue",
    pending: "Pending",
    paid: "Paid",
    present: "Present",
    absent: "Absent",
    absence: "Absence",
    followUp: "Follow-up due",
    followedUp: "Followed up",
  },
  notifications: {
    title: "Notifications",
    open: (count: number) => (count === 0 ? "Notifications" : `Notifications — ${count} new`),
    description: "Reminders and notes from the last 14 days, alerts to handle.",
    empty: "No notifications yet.",
    kinds: {
      followUp: "Reminder",
      note: "Profile note",
      absenceAlert: "Absence alert",
      cashVariance: "Cash variance",
      attendanceConflict: "Attendance mismatch",
    },
    by: (name: string) => `by ${name}`,
    priority: "Priority",
  },
  studentAccess: {
    title: "{Learner} access",
    description: "The {learner} signs in to their space (learning platform) with a code provided by the centre. No personal data is asked of them.",
    none: "No access yet.",
    active: "Access active",
    inactive: "Access disabled",
    code: "Sign-in code",
    openedOn: (date: string) => `Opened on ${date}`,
    disabledOn: (date: string) => `Disabled on ${date}`,
    open: "Open access",
    disable: "Disable access",
    enable: "Re-enable access",
    disableTitle: "Disable the {learner}'s access?",
    disableDescription: "The {learner} will no longer be able to sign in. Nothing is deleted: access can be re-enabled.",
    opened: "Access opened.",
    disabled: "Access disabled.",
    enabled: "Access re-enabled.",
    failed: "The access could not be created. Try again.",
    newStudentOption: "Open {learner} access",
    newStudentHint: "The {learner} will sign in to their space with a code and a password, shown only once after enrolment.",
    credentials: {
      title: "{Learner} sign-in details",
      description: "Write them down or send them to the parent/guardian: the password will not be shown again.",
      url: "Sign-in address",
      code: "Code",
      password: "Password",
      copy: "Copy",
      copied: "Copied.",
      whatsapp: "Send to parent/guardian",
      done: "I've noted it",
      message: (name: string, url: string, code: string, password: string) =>
        `Hello, here is ${name}'s access to their space: ${url} — code ${code}, temporary password ${password}. A personal password will be requested at first sign-in.`,
    },
  },
  studentLogin: {
    title: "{Learner} space",
    description: "Sign in with the code and password given by your centre.",
    code: "Code",
    codePlaceholder: "E.g. 7K4Q 2MXP",
    password: "Password",
    submit: "Sign in",
    submitting: "Signing in…",
    invalid: "Incorrect code or password.",
    codeRequired: "Enter your code (8 characters).",
    passwordRequired: "Enter your password.",
    disabled: "Your access is disabled. Contact your centre.",
    rateLimited: "Too many attempts. Wait a minute, then try again.",
    unavailable: "Unable to sign in right now. Check your internet connection, then try again.",
    staffLink: "Are you a staff member? Staff sign-in",
    studentLink: "Are you {a learner}? {Learner} sign-in",
  },
  resources: {
    title: "My resources",
    description: "Exercises, exams and course summaries for your {courses}. A published resource appears in the space of {learners} enrolled in the {course} and {group}.",
    new: "Publish a resource",
    newTitle: "New resource",
    editTitle: "Edit resource",
    back: "My resources",
    types: { exercise: "Exercise", exam: "Exam", summary: "Course summary", other: "Other" },
    filterSubject: "Filter by {course}",
    allSubjects: "All {courses}",
    emptyTitle: "No resources",
    emptyDescription: "Publish a first exercise, an exam paper or a course summary.",
    noAssignmentsTitle: "No {courses}",
    noAssignmentsDescription: "The administration has not assigned you any {courses} yet.",
    published: "Published",
    draft: "Draft",
    publishedOn: (date: string) => `Published on ${date}`,
    updatedOn: (date: string) => `Edited on ${date}`,
    dueOn: (date: string) => `Due on ${date}`,
    open: "Open file",
    edit: "Edit",
    publish: "Publish",
    unpublish: "Unpublish",
    delete: "Delete",
    deleteTitle: "Delete the resource?",
    deleteDescription: "The resource and its file are permanently deleted; {learners} will no longer see it.",
    deleted: "Resource deleted.",
    publishedToast: "Resource published.",
    unpublishedToast: "Resource unpublished: {learners} no longer see it.",
    saved: "Resource saved.",
    fields: {
      type: "Type",
      subject: "{Course} and {group}",
      subjectPlaceholder: "Choose {a course}",
      title: "Title",
      titlePlaceholder: "E.g. Set 3 — Derivatives",
      description: "Description",
      descriptionHint: "Instructions, related chapter… (optional)",
      file: "File",
      fileHint: "PDF or image (JPEG, PNG, WebP), 8 MB maximum.",
      currentFile: (name: string) => `Current file: ${name}`,
      replaceFile: "Replace the file (optional)",
      dueDate: "Due on (optional)",
      dueDateHint: "For an exercise or exam to hand in.",
      publishNow: "Publish now",
      publishNowHint: "Otherwise, the resource stays as a draft: only you can see it.",
    },
    submit: "Save",
    submitting: "Saving…",
    validation: {
      titleRequired: "Enter a title.",
      titleTooLong: "150 characters maximum.",
      descriptionTooLong: "2,000 characters maximum.",
      subjectRequired: "Choose {a course}.",
      fileRequired: "Add a file (PDF or image).",
      fileTooLarge: "File too large: 8 MB maximum.",
      fileInvalid: "Format not accepted: PDF, JPEG, PNG or WebP only.",
      dueDateInvalid: "Invalid date.",
    },
    errors: {
      upload: "The file could not be uploaded. Try again.",
    },
  },
  studentSpace: {
    title: "My space",
    welcome: (name: string) => `Hello ${name}`,
    description: (center: string, level: string) => `${center} · ${level}`,
    comingSoonTitle: "No resources yet",
    comingSoon: "Your exercises, exams and course summaries will appear here as soon as your {instructors} publish them.",
    newCount: (count: number) => `${count} new`,
    dueCount: (count: number) => (count === 1 ? "1 upcoming due date" : `${count} upcoming due dates`),
    dueSoonTitle: "Due soon",
    resourcesTitle: "My resources",
    filterSubject: "Filter by {course}",
    allSubjects: "All {courses}",
    typeGroups: { exercise: "Exercises", exam: "Exams", summary: "Course summaries", other: "Other documents" },
    new: "New",
    open: "Open",
    download: "Download",
    by: (name: string) => `By ${name}`,
    publishedOn: (date: string) => `Published on ${date}`,
    dueIn: (days: number) =>
      days < 0 ? "Past due" : days === 0 ? "Due today" : days === 1 ? "Due tomorrow" : `Due in ${days} days`,
    dueOn: (date: string) => `on ${date}`,
    emptySubjectTitle: "Nothing in this {course}",
    emptySubjectDescription: "No resources published in this {course} yet.",
    signOut: "Sign out",
  },
  /** À quel titre une présence a été saisie. */
  attendanceMarkers: { teacher: "{Instructor}", assistant: "Front desk", admin: "Administration" },
  sessions: {
    title: "Today's {sessions}",
    description: "All {sessions} in real time. Open {a session} to take attendance on behalf of the {instructor} if they could not do it.",
    dayLabel: (date: string) => `{Sessions} on ${date}`,
    today: "Today",
    previousDay: "Previous day",
    nextDay: "Next day",
    rangeHint: "Attendance can be taken or corrected up to 7 days after the {session}.",
    emptyTitle: "No {sessions} that day",
    emptyDescription: "The schedule has no {sessions} on this day of the week.",
    state: { upcoming: "Upcoming", ongoing: "In progress", done: "Finished" },
    progress: (marked: number, total: number) => `${marked} / ${total} marked`,
    notMarked: "Attendance not taken",
    absents: (count: number) => (count === 1 ? "1 absent" : `${count} absent`),
    byTeacher: "Taken by the {instructor}",
    byStaff: "Taken by the front desk",
    byBoth: "{Instructor} and front desk",
    conflicts: (count: number) => (count === 1 ? "1 mismatched entry" : `${count} mismatched entries`),
    take: "Take attendance",
    edit: "Correct attendance",
    lastMarked: (time: string) => `Last entry at ${time}`,
    roster: {
      back: "Today's {sessions}",
      description: "Mark each {learner} present or absent. The administration can see who took attendance and when.",
      allPresent: "All present",
      present: "Present",
      absent: "Absent",
      notMarked: "Not marked",
      markedBy: (role: string, name: string, time: string) => `${role} · ${name} · ${time}`,
      save: "Save attendance",
      saving: "Saving…",
      saved: (count: number) => (count === 1 ? "1 attendance record saved." : `${count} attendance records saved.`),
      nothingToSave: "Mark at least one {learner}.",
      unmarked: (count: number) => (count === 1 ? "1 {learner} without a status" : `${count} {learners} without a status`),
      emptyTitle: "No {learners} enrolled",
      emptyDescription: "Nobody is enrolled in this {session} on this date.",
      notFoundTitle: "{Session} not found",
      notFoundDescription: "This {session} does not exist, does not take place that day, or the date is outside the last 7 days.",
      teacherOf: (name: string) => `{Instructor}: ${name}`,
    },
  },
  attendanceConflicts: {
    title: "Attendance mismatches",
    description: "The {instructor} and the front desk entered different statuses. The most recent entry is shown; choose the one to keep.",
    banner: (count: number) =>
      count === 1
        ? "One attendance record differs between the {instructor} and the front desk."
        : `${count} attendance records differ between the {instructor} and the front desk.`,
    review: "Review mismatches",
    session: (subject: string, date: string) => `${subject} · ${date}`,
    entry: (role: string, name: string, status: string, time: string) => `${role} (${name}): ${status}, ${time}`,
    displayed: (status: string) => `Shown: ${status}`,
    keep: (status: string) => `Keep "${status}"`,
    resolved: "Status kept.",
    notification: (subject: string, date: string) => `${subject}, {session} on ${date}`,
  },
  attendanceSheet: {
    title: "Attendance",
    description: "The {learner}'s attendance and absences, by {course}.",
    filtersLabel: "Attendance filters",
    period: "Period",
    periods: { month: "This month", quarter: "This term", all: "Full history" },
    subject: "{Course}",
    allSubjects: "All {courses}",
    totalAbsences: "Absences",
    sessions: "Recorded {sessions}",
    rate: "Attendance rate",
    noRate: "—",
    bySubject: "By {course}",
    absencesCount: (count: number) => (count === 1 ? "1 absence" : `${count} absences`),
    markedBy: (role: string, name: string, time: string) => `Entered by ${name} (${role}), ${time}`,
    history: "Entry history",
    historyItem: (role: string, name: string, status: string, time: string) => `${role} (${name}): ${status}, ${time}`,
    sessionsCount: (count: number) => (count === 1 ? "1 {session}" : `${count} {sessions}`),
    streaksTitle: "Consecutive absences",
    streak: (length: number, subject: string) => `${length} consecutive absences in ${subject}`,
    streakRange: (from: string, to: string) => `from ${from} to ${to}`,
    streakOngoing: "Ongoing streak",
    streaksEmpty: "No consecutive absence streak in this period.",
    alertTriggered: "Alert triggered",
    alertHint: "An alert is created at the 3rd consecutive absence in the same {course}.",
    listTitle: "Missed {sessions}",
    listCaption: "Missed {sessions}, from most recent to oldest",
    date: "Date",
    time: "Time",
    teacher: "{Instructor}",
    note: "Reason or note",
    noNote: "No reason",
    noTime: "Time not scheduled",
    position: (position: number, length: number) => `${ordinal(position)} of ${length} in a row`,
    emptyTitle: "No absences",
    emptyDescription: "No missed {sessions} in this period.",
    noSessionsTitle: "No recorded {sessions}",
    noSessionsDescription: "Attendance will appear once it has been taken.",
    followUpsTitle: "Absence reminders",
    followUpsEmpty: "No absence reminders sent to the parent/guardian.",
    followUpBy: (name: string) => `by ${name}`,
    editNote: "Reason",
    editNoteLabel: (date: string) => `Reason for the absence on ${date}`,
    notePlaceholder: "E.g. ill, medical certificate received",
    noteSaved: "Reason saved",
    noteTooLong: "300 characters maximum.",
    exportPdf: "Export as PDF",
    pdfTitle: "Attendance report",
    pdfStudent: "{Learner}",
    pdfLevel: "{Group}",
    pdfGuardian: "Parent/guardian",
    pdfPeriod: "Period",
    pdfGeneratedOn: (date: string) => `Issued on ${date}`,
    pdfPage: (page: number, total: number) => `Page ${page} / ${total}`,
    viewAttendance: "View attendance",
    teacherScope: "You only see absences for your {courses}.",
  },
};
