import type { AppLabels } from "@/lib/constants/labels";

function plural(n: number, singular: string, pluralForm: string): string {
  return n === 1 ? `1 ${singular}` : `${n} ${pluralForm}`;
}

/** Libellés anglais : platform. */
export const EN_PART3: Pick<AppLabels, "platform"> = {
  platform: {
    moduleCatalogue: {
      finance: {
        name: "Finance",
        description: "{Instructor} payroll (fixed salary, commissions), printable and WhatsApp receipts, expenses and net revenue, discounts, daily cash desk.",
      },
      reenrollment: {
        name: "Re-enrolment",
        description: "Automatic monthly re-enrolment campaigns, {learner} intentions, payment reminders.",
      },
      absence_tracking: {
        name: "Absence tracking",
        description: "Detailed attendance report, alert after three absences, absences to report and WhatsApp messages to the guardian.",
      },
      white_label: {
        name: "White label",
        description: "Interface in the centre's colours: name, logo, favicon, colours, custom domain.",
      },
      lms: {
        name: "Learning platform",
        description: "{Instructor} space to publish (exercises, exams, course summaries) and {learner} space to view them.",
      },
    },
    centerTypeNames: {
      soutien_scolaire: "Tutoring centre",
      centre_formation: "Training centre",
      institut_langue: "Language institute",
      auto_ecole: "Driving school",
      soutien_universitaire: "University tutoring centre",
      personnalise: "Custom",
    },
    brand: "dirassty",
    centerStatus: {
      trial: "Trial",
      active: "Active",
      past_due: "Overdue",
      suspended: "Suspended",
      cancelled: "Cancelled",
    },
    /** Packs (noms du catalogue ; anciennes formules pour l'historique). */
    plan: {
      starter: "Starter",
      premium: "Premium",
      standard: "Standard",
      white_label: "White label",
    },
    interval: {
      month: "per month",
      year: "per year",
    },
    intervalShort: {
      month: "/ month",
      year: "/ year",
    },
    paymentMethod: {
      bank_transfer: "Bank transfer",
      cash: "Cash",
      card: "Card",
    },
    noDueDate: "No due date",
    notSet: "Not set",
    daysRemaining: (days: number) =>
      days === 0
        ? "Due today"
        : days > 0
          ? `${plural(days, "day", "days")} left`
          : `${plural(-days, "day", "days")} overdue`,
    dashboard: {
      title: "Platform dashboard",
      description: "Overview of centres, subscriptions and collected payments.",
      centersByStatus: "Centres by status",
      mrr: "Monthly recurring revenue",
      mrrDetail: "Active and overdue centres, annual plans converted to monthly",
      collected: "Collected this month",
      students: "Learners on the platform",
      users: "User accounts",
      overdueTitle: "Centres with overdue payments",
      overdueDescription: "Past due date, from the oldest to the most recent.",
      overdueEmpty: "No overdue centres",
      overdueEmptyDescription: "All due dates are up to date.",
      daysLate: (days: number) => `${plural(days, "day", "days")} overdue`,
      dueSince: (date: string) => `Due ${date}`,
      amountDue: "Amount due",
      director: "Director",
      call: "Call",
      email: "Email",
      callLabel: (name: string) => `Call the director of ${name}`,
      emailLabel: (name: string) => `Email the director of ${name}`,
      openCenter: "View profile",
      upcomingTitle: "Due in the next 7 days",
      upcomingEmpty: "Nothing due in the next 7 days.",
      dueOn: (date: string) => `Due on ${date}`,
      remindersTitle: "Prepared reminders",
      remindersDescription:
        "Emails prepared every night (7 days before, 1 day before, due date, suspension). Automatic sending will be enabled with the email service.",
      remindersEmpty: "No reminders prepared recently.",
      reminderKinds: {
        due_in_7: "Due in 7 days",
        due_in_1: "Due tomorrow",
        due_today: "Due today",
        suspended: "Access suspended",
        owner_digest: "Summary",
      },
      reminderPending: "To send",
      reminderSent: "Sent",
      noRecipient: "No email",
    },
    centers: {
      title: "Centres",
      description: "All centres on the platform.",
      searchLabel: "Search for a centre",
      searchPlaceholder: "Centre name or address",
      search: "Search",
      filterStatus: "Filter by status",
      filterType: "Filter by institution type",
      filterPlan: "Filter by pack",
      allStatuses: "All statuses",
      allTypes: "All types",
      allPlans: "All packs",
      caption: "List of centres",
      address: "Address",
      name: "Centre",
      type: "Type",
      plan: "Pack",
      status: "Status",
      activatedAt: "Activation",
      dueDate: "Due date",
      remaining: "Time left",
      students: "Learners",
      price: "Price",
      count: (n: number) => plural(n, "centre", "centres"),
      empty: "No centres",
      emptyDescription: "No centre matches these criteria.",
    },
    center: {
      back: "All centres",
      notFound: "Centre not found",
      identity: "Details",
      slug: "Centre address",
      formerSlugs: (list: string) => `Former addresses (redirected to the current one): ${list}`,
      type: "Institution type",
      createdAt: "Created on",
      activatedAt: "Activated on",
      cancelledAt: "Cancelled on",
      contact: "Director's contact",
      notes: "Internal notes",
      noNotes: "No notes.",
      subscription: "Subscription",
      plan: "Pack",
      price: "Price",
      dueDate: "Due date",
      periodStart: "Current period since",
      graceDays: "Grace period",
      graceDaysValue: (days: number) => plural(days, "day", "days"),
      autoRenew: "Automatic renewal",
      yes: "Yes",
      no: "No",
      students: "Learners",
      users: "Accounts",
      payments: "Payment history",
      paymentsEmpty: "No payments recorded.",
      paidAt: "Paid on",
      amount: "Amount",
      periodCovered: "Period covered",
      method: "Method",
      reference: "Reference",
      recordedBy: "Recorded by",
      history: "History",
      historyEmpty: "No events.",
      automatic: "Automatic",
      branding: "White label",
      brandingStandard: "White label module not enabled: the interface uses dirassty's colours.",
      brandingEmpty: "No branding settings saved.",
      brandName: "Brand name",
      colors: "Colours",
      customDomain: "Custom domain",
      domainVerified: "Verified",
      domainPending: "Pending verification",
      supportContact: "Support",
      usersTitle: "Centre accounts",
      usersEmpty: "No accounts.",
      userName: "Name",
      userEmail: "Email",
      userRole: "Role",
      userState: "Status",
      userActive: "Active",
      userInactive: "Disabled",
      lastSignIn: "Last sign-in",
      never: "Never",
      vocabulary: "Vocabulary",
      periodRange: (from: string, to: string) => `From ${from} to ${to}`,
    },
    events: {
      "center.created": "Centre created",
      "center.status_changed": "Status changed",
      "center.period_changed": "Due date changed",
      "center.pricing_changed": "Price changed",
      "center.vocabulary_changed": "Institution type changed",
      "center.identity_changed": "Name or address changed",
      "subscription.plan_changed": "Plan changed",
      "center.plan_changed": "Pack changed",
      "center.module_enabled": "Module enabled",
      "center.module_disabled": "Module turned off",
      "plan.updated": "Catalogue pack updated",
      "subscription.auto_renew_changed": "Renewal changed",
      "subscription.payment_recorded": "Payment recorded",
      "branding.updated": "White label updated",
      "center.details_changed": "Details changed",
      "center.admin_invited": "Administrator invited",
      "platform.settings_changed": "Settings changed",
      "center.admin_password_reset": "Admin password reset",
      "center.password_link_sent": "Password link sent",
      "support.started": "Support access opened",
      "support.ended": "Support access closed",
    },
    eventFallback: "Action",
    modules: {
      title: "Modules",
      description:
        "Features enabled for this centre. Its pack enables them; a module can also be enabled or turned off individually.",
      disableHint: "Turning off a module hides its screens and blocks its access on the server; no data is deleted.",
      inPlan: "Included in the pack",
      notInPlan: "Not in the pack",
      source: { plan: "From the pack", manual: "Individually", trial: "Trial" },
      enabled: "Enabled",
      disabled: "Off",
      switchLabel: (name: string) => `${name} module`,
      trial: "Trial",
      trialHint: "Enable this out-of-pack module as a trial",
      enabledSince: (date: string) => `Enabled on ${date}`,
      saved: "Module updated.",
      readOnly: "Read-only in support mode.",
    },
    catalogue: {
      title: "Catalogue",
      description: "Commercial packs and optional modules. A centre's price remains that of its subscription.",
      plans: "Packs",
      modules: "Modules",
      monthlyPrice: "Catalogue price (MAD per month)",
      centersCount: (n: number) => plural(n, "centre", "centres"),
      includes: "Included modules",
      inPlans: "In packs",
      noPlan: "No pack: enabled individually",
      edit: "Edit",
      editTitle: (name: string) => `Edit the ${name} pack`,
      name: "Name",
      descriptionLabel: "Description",
      saved: "Pack updated.",
      categories: {
        gestion: "Management",
        finance: "Finance",
        suivi: "Monitoring",
        marque: "Branding",
        pedagogie: "Teaching",
      },
      core: {
        title: "Core, always on",
        items: [
          "Three roles: administration, front desk, {instructor}",
          "{Learners}, enrolments, {course} packs, invoices and payments",
          "Schedule and rooms with conflict detection",
          "Attendance taken by the {instructor} and by the front desk",
          "Staff, statistics and vocabulary by institution type",
        ],
      },
      rule: {
        title: "Rule for future requests",
        items: [
          "Useful to most centres: the feature joins the core.",
          "Useful to a group of centres: it becomes a module in an existing pack or a new pack.",
          "Specific to a single client: declined, or billed as custom work and delivered as a module behind a switch, never as a copy of the code.",
        ],
      },
    },
    reason: (text: string) => `Reason: ${text}`,
    validation: {
      nameRequired: "Enter a name.",
      tooLong: "This text is too long.",
      phoneInvalid: "Invalid number (e.g. 06 12 34 56 78).",
      emailRequired: "Enter an email.",
      emailInvalid: "This email is not valid.",
      slugInvalid: "2 to 63 characters: lowercase letters, numbers and hyphens.",
      slugReserved: "This address is reserved for the platform.",
      typeRequired: "Choose an institution type.",
      termRequired: "Enter this term.",
      amountInvalid: "Invalid amount (e.g. 490 or 490.50).",
      graceInvalid: "Between 0 and 60 days.",
      dateInvalid: "Invalid date.",
      dueAfterActivation: "The due date must come after the activation date.",
      reasonRequired: "Enter a reason.",
      planRequired: "Choose a pack.",
    },
    errors: {
      emailExists: "This email already has an account on the platform.",
      inviteFailed: "The invitation could not be sent. Try again.",
      slugTaken: "This address is already used by another centre.",
    },
    newCenter: {
      title: "New centre",
      open: "New centre",
      steps: ["Identity", "Institution type", "Pack and price", "Administrator account"],
      progress: (current: number, total: number) => `Step ${current} of ${total}`,
      previous: "Previous",
      next: "Next",
      submit: "Create the centre and invite the admin",
      submitting: "Creating…",
      success: "Centre created",
      successDescription: (email: string) => `Invitation sent to ${email}.`,
      name: "Centre name",
      namePlaceholder: "Centre Al Amal — Rabat",
      slug: "Centre address",
      slugHint: "The centre's subdomain (e.g. al-amal). Lowercase letters, numbers and hyphens.",
      ownerName: "Director's name",
      ownerPhone: "Director's phone",
      ownerEmail: "Director's email",
      notes: "Internal notes",
      notesHint: "Visible only in the console.",
      optional: "optional",
      typeLegend: "Institution type",
      typeHint: "Sets the vocabulary of the centre's entire interface.",
      customTitle: "Custom vocabulary",
      customHint: "Enter each term in the singular and plural, with its gender for agreement.",
      termKeys: {
        learner: "Learner",
        group: "Group",
        course: "Course",
        instructor: "Instructor",
        session: "Session",
      },
      singular: "Singular",
      plural: "Plural",
      gender: "Gender",
      masculine: "Masculine",
      feminine: "Feminine",
      preview: (learners: string, instructors: string, courses: string) => `${learners} · ${instructors} · ${courses}`,
      plan: "Pack",
      planPrice: (price: string) => `Catalogue price: ${price} per month`,
      price: "Amount (MAD)",
      interval: "Billing period",
      intervalOptions: { month: "Monthly", year: "Annual" },
      graceDays: "Grace period (days)",
      graceHint: "After the due date, the centre remains usable for this many days before suspension.",
      status: "Start",
      statusOptions: { trial: "Trial period", active: "Active from activation" },
      activationDate: "Activation date",
      firstDueDate: "First due date",
      firstDueHint: "Suggested automatically: activation + one month (or one year). Can be changed.",
      adminName: "Centre administrator's name",
      adminEmail: "Administrator's email",
      adminEmailHint: "They receive an invitation and choose their password on first sign-in.",
      adminPhone: "Administrator's phone",
      summary: "Summary",
    },
    accessLink: {
      title: "Access link to send",
      description: (email: string) =>
        `The email service could not send the message (sending limit reached). Copy this link and send it to ${email}, for example via WhatsApp: it lets them choose their password.`,
      personal: "Personal, single-use link: share it only with this person.",
      copy: "Copy link",
      copied: "Link copied",
      continue: "Continue",
    },
    actions: {
      title: "Actions",
      recordPayment: "Record a payment",
      dueDate: "Change due date",
      pricing: "Plan and price",
      details: "Edit details",
      suspend: "Suspend",
      reactivate: "Reactivate",
      cancel: "Cancel subscription",
      resendInvitation: "Resend invitation",
      invitationSent: "Invitation resent",
      passwordLink: "Send a password link",
      passwordLinkSent: "Password link sent",
      saved: "Changes saved",
      save: "Save",
      saving: "Saving…",
      paymentTitle: "Record a payment",
      paymentDescription: (period: string) =>
        `The payment covers ${period} from the current due date and puts the centre back in service.`,
      periodMonth: "one month",
      periodYear: "one year",
      paymentAmount: "Amount (MAD)",
      paymentDate: "Payment date",
      paymentMethod: "Payment method",
      paymentReference: "Reference",
      paymentReferenceHint: "Transfer or receipt no.… (optional)",
      paymentSaved: "Payment recorded",
      dueDateTitle: "Change due date",
      dueDateDescription:
        "Set or extend the due date. An overdue centre whose due date is in the future again becomes active.",
      newDueDate: "New due date",
      reasonOptional: "Reason (optional)",
      reason: "Reason",
      reasonPlaceholder: "E.g. extension granted until the bank transfer",
      pricingTitle: "Plan and price",
      detailsTitle: "Centre details",
      statusTitle: {
        active: "Reactivate the centre",
        suspended: "Suspend the centre",
        cancelled: "Cancel the centre",
      },
      support: "Support access (read-only)",
      supportTitle: "Read-only support access",
      supportDescription:
        "You view the centre's Administration space for 1 hour, without being able to change anything. Access is logged and a banner stays visible.",
      supportSubmit: "Open support access",
      supportReasonPlaceholder: "E.g. the director reports a problem with the schedule",
      statusDescription: {
        active:
          "The centre's accounts regain access immediately. If the due date has passed, extend it: otherwise the daily check will suspend the centre again.",
        suspended: "Sign-in will be blocked for all of the centre's accounts. Data is kept.",
        cancelled: "Permanent action: the centre can no longer be reactivated. Data remains exportable for 90 days.",
      },
      statusSaved: {
        active: "Centre reactivated",
        suspended: "Centre suspended",
        cancelled: "Centre cancelled",
      },
    },
    settings: {
      title: "Platform settings",
      description: "Contact shown to suspended centres so they can settle their subscription.",
      contactTitle: "Settlement contact",
      name: "Display name",
      namePlaceholder: "dirassty customer service",
      phone: "Phone",
      email: "Email",
      saved: "Settings saved",
      updatedAt: (date: string) => `Last updated: ${date}`,
    },
    billing: {
      title: "Billing",
      description: "Subscription payments from all centres.",
      monthsTitle: "Collected by month",
      monthsDescription:
        "Current month forecast: this month's due dates for centres in service, at their plan's price.",
      month: "Month",
      collected: "Collected",
      expected: "Forecast",
      gap: "Variance",
      currentMonth: "This month",
      paymentsTitle: "All payments",
      center: "Centre",
      empty: "No payments",
      emptyDescription: "Recorded subscription payments will appear here.",
    },
  },
};
